// ==========================================================
// Color management: ICC profile conversions with Little CMS
//
// This file is part of FreeImage 3
//
// COVERED CODE IS PROVIDED UNDER THIS LICENSE ON AN "AS IS" BASIS, WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, WITHOUT LIMITATION, WARRANTIES
// THAT THE COVERED CODE IS FREE OF DEFECTS, MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE
// OR NON-INFRINGING. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE COVERED
// CODE IS WITH YOU. SHOULD ANY COVERED CODE PROVE DEFECTIVE IN ANY RESPECT, YOU (NOT
// THE INITIAL DEVELOPER OR ANY OTHER CONTRIBUTOR) ASSUME THE COST OF ANY NECESSARY
// SERVICING, REPAIR OR CORRECTION. THIS DISCLAIMER OF WARRANTY CONSTITUTES AN ESSENTIAL
// PART OF THIS LICENSE. NO USE OF ANY COVERED CODE IS AUTHORIZED HEREUNDER EXCEPT UNDER
// THIS DISCLAIMER.
//
// Use at your own risk!
//
// Code generated by Marius Șucan with Anthropic Claude
// ==========================================================

#include <chrono>
#include <memory>
#include <mutex>
#include <string>
#include <vector>

// windows.h has to precede FreeImage.h
#ifdef _WIN32
#ifndef NOMINMAX
#define NOMINMAX
#endif
#include <windows.h>
#include <wchar.h>
#elif defined(__linux__)
#include <dlfcn.h>
#include <stdint.h>
#endif

#include "FreeImage.h"
#include "Utilities.h"

#define CMS_NO_REGISTER_KEYWORD 1
#include "../LibLCMS2/include/lcms2.h"

// images smaller than this are converted on one thread
#define ICC_PARALLEL_PIXELS 16384

// the number of FICMS_PROFILE_* profiles
#define ICC_BUILTIN_COUNT 7

// FreeImage's 24- and 32-bit pixels and palette entries
#if FREEIMAGE_COLORORDER == FREEIMAGE_COLORORDER_BGR
#define ICC_TYPE_RGB_8	TYPE_BGR_8
#define ICC_TYPE_RGBA_8	TYPE_BGRA_8
#else
#define ICC_TYPE_RGB_8	TYPE_RGB_8
#define ICC_TYPE_RGBA_8	TYPE_RGBA_8
#endif

namespace {

enum Model {
	MODEL_NONE = 0,
	MODEL_GRAY,
	MODEL_RGB,
	MODEL_CMYK
};

enum Layout {
	LAYOUT_NONE = 0,
	LAYOUT_INDEXED,		// 1-, 4- or 8-bit palette
	LAYOUT_GRAY8,		// 8-bit linear grey ramp without transparency
	LAYOUT_555,
	LAYOUT_565,
	LAYOUT_RGB8,
	LAYOUT_RGBA8,
	LAYOUT_CMYK8,
	LAYOUT_GRAY16,
	LAYOUT_RGB16,
	LAYOUT_RGBA16,
	LAYOUT_CMYK16,
	LAYOUT_GRAYF,
	LAYOUT_RGBF,
	LAYOUT_RGBAF
};

struct Pixels {
	Layout layout;
	Model model;
	unsigned depth;		// 8, 16 or 32 (float) bits per sample
	bool alpha;			// an alpha channel or a transparency table
	bool reversed;		// FIC_MINISWHITE
	unsigned colors;	// palette entries
};

// ----------------------------------------------------------
//   Pixel layouts
// ----------------------------------------------------------

static bool
IsGreyPalette(const RGBQUAD *palette, unsigned count) {
	for (unsigned i = 0; i < count; i++) {
		if ((palette[i].rgbRed != palette[i].rgbGreen) || (palette[i].rgbRed != palette[i].rgbBlue)) {
			return false;
		}
	}
	return true;
}

// NULL, or why the image cannot be color managed
static const char *
AnalysePixels(FIBITMAP *dib, Pixels &px) {
	memset(&px, 0, sizeof(px));

	const bool cmyk = (FreeImage_GetICCProfile(dib)->flags & FIICC_COLOR_IS_CMYK) != 0;
	const unsigned bpp = FreeImage_GetBPP(dib);

	switch (FreeImage_GetImageType(dib)) {
		case FIT_BITMAP:
			px.depth = 8;
			switch (bpp) {
				case 1:
				case 4:
				case 8:
				{
					const RGBQUAD *palette = FreeImage_GetPalette(dib);
					px.colors = FreeImage_GetColorsUsed(dib);
					if (!palette || !px.colors) {
						return "the image has no palette";
					}
					px.layout = LAYOUT_INDEXED;
					px.model = IsGreyPalette(palette, px.colors) ? MODEL_GRAY : MODEL_RGB;
					px.alpha = FreeImage_IsTransparent(dib) && (FreeImage_GetTransparencyCount(dib) > 0);
					if ((bpp == 8) && (px.colors == 256) && !px.alpha) {
						const FREE_IMAGE_COLOR_TYPE color_type = FreeImage_GetColorType(dib);
						if ((color_type == FIC_MINISBLACK) || (color_type == FIC_MINISWHITE)) {
							px.layout = LAYOUT_GRAY8;
							px.reversed = (color_type == FIC_MINISWHITE);
						}
					}
					return NULL;
				}
				case 16:
					px.layout = IS_FORMAT_RGB565(dib) ? LAYOUT_565 : LAYOUT_555;
					px.model = MODEL_RGB;
					return NULL;
				case 24:
					px.layout = LAYOUT_RGB8;
					px.model = MODEL_RGB;
					return NULL;
				case 32:
					px.layout = cmyk ? LAYOUT_CMYK8 : LAYOUT_RGBA8;
					px.model = cmyk ? MODEL_CMYK : MODEL_RGB;
					px.alpha = !cmyk;
					return NULL;
			}
			break;
		case FIT_UINT16:
			px.layout = LAYOUT_GRAY16;
			px.model = MODEL_GRAY;
			px.depth = 16;
			px.reversed = (FreeImage_GetColorType(dib) == FIC_MINISWHITE);
			return NULL;
		case FIT_RGB16:
			px.layout = LAYOUT_RGB16;
			px.model = MODEL_RGB;
			px.depth = 16;
			return NULL;
		case FIT_RGBA16:
			px.layout = cmyk ? LAYOUT_CMYK16 : LAYOUT_RGBA16;
			px.model = cmyk ? MODEL_CMYK : MODEL_RGB;
			px.depth = 16;
			px.alpha = !cmyk;
			return NULL;
		case FIT_FLOAT:
			px.layout = LAYOUT_GRAYF;
			px.model = MODEL_GRAY;
			px.depth = 32;
			return NULL;
		case FIT_RGBF:
			px.layout = LAYOUT_RGBF;
			px.model = MODEL_RGB;
			px.depth = 32;
			return NULL;
		case FIT_RGBAF:
			if (cmyk) {
				return "floating-point CMYK images are not supported";
			}
			px.layout = LAYOUT_RGBAF;
			px.model = MODEL_RGB;
			px.depth = 32;
			px.alpha = true;
			return NULL;
		default:
			break;
	}
	return "unsupported image type";
}

static cmsUInt32Number
LayoutFormat(Layout layout, bool reversed) {
	switch (layout) {
		case LAYOUT_GRAY8:	return reversed ? TYPE_GRAY_8_REV : TYPE_GRAY_8;
		case LAYOUT_RGB8:	return ICC_TYPE_RGB_8;
		case LAYOUT_RGBA8:	return ICC_TYPE_RGBA_8;
		case LAYOUT_CMYK8:	return TYPE_CMYK_8;
		case LAYOUT_GRAY16:	return reversed ? TYPE_GRAY_16_REV : TYPE_GRAY_16;
		case LAYOUT_RGB16:	return TYPE_RGB_16;
		case LAYOUT_RGBA16:	return TYPE_RGBA_16;
		case LAYOUT_CMYK16:	return TYPE_CMYK_16;
		case LAYOUT_GRAYF:	return TYPE_GRAY_FLT;
		case LAYOUT_RGBF:	return TYPE_RGB_FLT;
		case LAYOUT_RGBAF:	return TYPE_RGBA_FLT;
		default:			return 0;
	}
}

static unsigned
PixelBytes(cmsUInt32Number format) {
	const unsigned bytes = T_BYTES(format) ? T_BYTES(format) : 8;
	return bytes * (T_CHANNELS(format) + T_EXTRA(format));
}

// the pixel format of a new image in the destination model: same precision, alpha kept when it can be
static Layout
OutputLayout(const Pixels &px, Model model) {
	switch (model) {
		case MODEL_RGB:
			if (px.depth == 8) return px.alpha ? LAYOUT_RGBA8 : LAYOUT_RGB8;
			if (px.depth == 16) return px.alpha ? LAYOUT_RGBA16 : LAYOUT_RGB16;
			return px.alpha ? LAYOUT_RGBAF : LAYOUT_RGBF;
		case MODEL_GRAY:
			// a transparent palette keeps its transparency table
			if (px.depth == 8) return ((px.layout == LAYOUT_INDEXED) && px.alpha) ? LAYOUT_INDEXED : LAYOUT_GRAY8;
			if (px.depth == 16) return LAYOUT_GRAY16;
			return LAYOUT_GRAYF;
		case MODEL_CMYK:
			return (px.depth == 8) ? LAYOUT_CMYK8 : LAYOUT_CMYK16;
		default:
			return LAYOUT_NONE;
	}
}

// the pixel format an in-place conversion leaves, or LAYOUT_NONE
static Layout
InPlaceLayout(const Pixels &px, Model model) {
	switch (px.layout) {
		case LAYOUT_INDEXED:
			return (model == MODEL_CMYK) ? LAYOUT_NONE : LAYOUT_INDEXED;
		case LAYOUT_GRAY8:
			if (model == MODEL_GRAY) return LAYOUT_GRAY8;
			return (model == MODEL_RGB) ? LAYOUT_INDEXED : LAYOUT_NONE;
		case LAYOUT_RGB8:
		case LAYOUT_RGBA8:
		case LAYOUT_RGB16:
		case LAYOUT_RGBA16:
		case LAYOUT_RGBF:
		case LAYOUT_RGBAF:
			return (model == MODEL_RGB) ? px.layout : LAYOUT_NONE;
		case LAYOUT_GRAY16:
		case LAYOUT_GRAYF:
			return (model == MODEL_GRAY) ? px.layout : LAYOUT_NONE;
		case LAYOUT_CMYK8:
			if (model == MODEL_CMYK) return LAYOUT_CMYK8;
			return (model == MODEL_RGB) ? LAYOUT_RGBA8 : LAYOUT_NONE;
		case LAYOUT_CMYK16:
			if (model == MODEL_CMYK) return LAYOUT_CMYK16;
			return (model == MODEL_RGB) ? LAYOUT_RGBA16 : LAYOUT_NONE;
		default:
			return LAYOUT_NONE;
	}
}

static FIBITMAP *
AllocateLayout(Layout layout, int width, int height) {
	switch (layout) {
		case LAYOUT_GRAY8:
		{
			FIBITMAP *dib = FreeImage_Allocate(width, height, 8);
			if (dib) {
				RGBQUAD *palette = FreeImage_GetPalette(dib);
				CREATE_GREYSCALE_PALETTE(palette, 256);
			}
			return dib;
		}
		case LAYOUT_RGB8:
			return FreeImage_Allocate(width, height, 24, FI_RGBA_RED_MASK, FI_RGBA_GREEN_MASK, FI_RGBA_BLUE_MASK);
		case LAYOUT_RGBA8:
		case LAYOUT_CMYK8:
			return FreeImage_Allocate(width, height, 32, FI_RGBA_RED_MASK, FI_RGBA_GREEN_MASK, FI_RGBA_BLUE_MASK);
		case LAYOUT_GRAY16:
			return FreeImage_AllocateT(FIT_UINT16, width, height);
		case LAYOUT_RGB16:
			return FreeImage_AllocateT(FIT_RGB16, width, height);
		case LAYOUT_RGBA16:
		case LAYOUT_CMYK16:
			return FreeImage_AllocateT(FIT_RGBA16, width, height);
		case LAYOUT_GRAYF:
			return FreeImage_AllocateT(FIT_FLOAT, width, height);
		case LAYOUT_RGBF:
			return FreeImage_AllocateT(FIT_RGBF, width, height);
		case LAYOUT_RGBAF:
			return FreeImage_AllocateT(FIT_RGBAF, width, height);
		default:
			return NULL;
	}
}

// ----------------------------------------------------------
//   Device CMYK: the conversions FreeImage's loaders use
// ----------------------------------------------------------

// as ConvertCMYKtoRGBA(): R = (1 - C)(1 - K), 8-bit output in FreeImage's color order
static void
DeviceCMYKToRGB8(const BYTE *src, BYTE *dst, unsigned width) {
	for (unsigned x = 0; x < width; x++) {
		const unsigned K = 255 - src[3];
		dst[FI_RGBA_RED]	= (BYTE)(((255 - src[0]) * K) / 255);
		dst[FI_RGBA_GREEN]	= (BYTE)(((255 - src[1]) * K) / 255);
		dst[FI_RGBA_BLUE]	= (BYTE)(((255 - src[2]) * K) / 255);
		src += 4;
		dst += 3;
	}
}

static void
DeviceCMYKToRGB16(const WORD *src, WORD *dst, unsigned width) {
	for (unsigned x = 0; x < width; x++) {
		const unsigned K = 65535 - src[3];
		dst[0] = (WORD)(((65535 - src[0]) * K) / 65535);
		dst[1] = (WORD)(((65535 - src[1]) * K) / 65535);
		dst[2] = (WORD)(((65535 - src[2]) * K) / 65535);
		src += 4;
		dst += 3;
	}
}

// full black generation; the exact inverse of DeviceCMYKToRGB*
template <class T> static void
RGBToDeviceCMYK(const T *src, unsigned step, bool grey, unsigned r, unsigned g, unsigned b, T *dst, unsigned width) {
	const unsigned MAX_VAL = (sizeof(T) == 1) ? 255 : 65535;
	for (unsigned x = 0; x < width; x++) {
		if (grey) {
			dst[0] = dst[1] = dst[2] = 0;
			dst[3] = (T)(MAX_VAL - src[0]);
		} else {
			const unsigned R = src[r], G = src[g], B = src[b];
			const unsigned M = MAX(R, MAX(G, B));
			if (M == 0) {
				dst[0] = dst[1] = dst[2] = 0;
				dst[3] = (T)MAX_VAL;
			} else {
				dst[0] = (T)(MAX_VAL - (MAX_VAL * R + M - 1) / M);
				dst[1] = (T)(MAX_VAL - (MAX_VAL * G + M - 1) / M);
				dst[2] = (T)(MAX_VAL - (MAX_VAL * B + M - 1) / M);
				dst[3] = (T)(MAX_VAL - M);
			}
		}
		src += step;
		dst += 4;
	}
}

static void
PackOpaque8(const BYTE *rgb, BYTE *rgba, unsigned width) {
	for (unsigned x = 0; x < width; x++) {
		rgba[0] = rgb[0];
		rgba[1] = rgb[1];
		rgba[2] = rgb[2];
		rgba[3] = 0xFF;
		rgb += 3;
		rgba += 4;
	}
}

static void
PackOpaque16(const WORD *rgb, WORD *rgba, unsigned width) {
	for (unsigned x = 0; x < width; x++) {
		rgba[0] = rgb[0];
		rgba[1] = rgb[1];
		rgba[2] = rgb[2];
		rgba[3] = 0xFFFF;
		rgb += 3;
		rgba += 4;
	}
}

// ----------------------------------------------------------
//   Built-in profiles
// ----------------------------------------------------------

static bool
SetDescription(cmsHPROFILE profile, const char *text) {
	cmsMLU *mlu = cmsMLUalloc(cmsGetProfileContextID(profile), 1);
	const bool done = mlu && cmsMLUsetASCII(mlu, "en", "US", text) && cmsWriteTag(profile, cmsSigProfileDescriptionTag, mlu);
	if (mlu) {
		cmsMLUfree(mlu);
	}
	return done;
}

static cmsHPROFILE
CreateBuiltInProfile(cmsContext context, int which) {
	static const cmsCIExyY D65 = { 0.3127, 0.3290, 1.0 };
	static const cmsCIExyY D50 = { 0.3457, 0.3585, 1.0 };
	static const cmsCIExyYTRIPLE SRGB = { { 0.6400, 0.3300, 1.0 }, { 0.3000, 0.6000, 1.0 }, { 0.1500, 0.0600, 1.0 } };
	static const cmsCIExyYTRIPLE ADOBE = { { 0.6400, 0.3300, 1.0 }, { 0.2100, 0.7100, 1.0 }, { 0.1500, 0.0600, 1.0 } };
	static const cmsCIExyYTRIPLE P3 = { { 0.6800, 0.3200, 1.0 }, { 0.2650, 0.6900, 1.0 }, { 0.1500, 0.0600, 1.0 } };
	static const cmsCIExyYTRIPLE ROMM = { { 0.7347, 0.2653, 1.0 }, { 0.1596, 0.8404, 1.0 }, { 0.0366, 0.0001, 1.0 } };
	static const cmsFloat64Number SRGB_CURVE[5] = { 2.4, 1.0 / 1.055, 0.055 / 1.055, 1.0 / 12.92, 0.04045 };

	const cmsCIExyY *white = &D65;
	const cmsCIExyYTRIPLE *primaries = &SRGB;
	cmsToneCurve *curve = NULL;
	const char *name = NULL;

	switch (which) {
		case FICMS_PROFILE_SRGB:
			curve = cmsBuildParametricToneCurve(context, 4, SRGB_CURVE);
			name = "sRGB (FreeImage)";
			break;
		case FICMS_PROFILE_LINEAR_SRGB:
			curve = cmsBuildGamma(context, 1.0);
			name = "Linear sRGB (FreeImage)";
			break;
		case FICMS_PROFILE_GRAY:
			curve = cmsBuildParametricToneCurve(context, 4, SRGB_CURVE);
			name = "Gray, sRGB tone curve (FreeImage)";
			break;
		case FICMS_PROFILE_LINEAR_GRAY:
			curve = cmsBuildGamma(context, 1.0);
			name = "Linear gray (FreeImage)";
			break;
		case FICMS_PROFILE_ADOBE_RGB:
			curve = cmsBuildGamma(context, 563.0 / 256.0);
			primaries = &ADOBE;
			name = "Adobe RGB (1998) compatible (FreeImage)";
			break;
		case FICMS_PROFILE_DISPLAY_P3:
			curve = cmsBuildParametricToneCurve(context, 4, SRGB_CURVE);
			primaries = &P3;
			name = "Display P3 (FreeImage)";
			break;
		case FICMS_PROFILE_PROPHOTO_RGB:
			curve = cmsBuildGamma(context, 1.8);
			white = &D50;
			primaries = &ROMM;
			name = "ProPhoto RGB (FreeImage)";
			break;
		default:
			return NULL;
	}
	if (!curve) {
		return NULL;
	}

	cmsHPROFILE profile = NULL;
	if ((which == FICMS_PROFILE_GRAY) || (which == FICMS_PROFILE_LINEAR_GRAY)) {
		profile = cmsCreateGrayProfileTHR(context, cmsD50_xyY(), curve);
	} else {
		cmsToneCurve *curves[3] = { curve, curve, curve };
		profile = cmsCreateRGBProfileTHR(context, white, primaries, curves);
	}
	cmsFreeToneCurve(curve);

	if (profile && !SetDescription(profile, name)) {
		cmsCloseProfile(profile);
		profile = NULL;
	}
	return profile;
}

static BYTE *
SaveBuiltInProfile(cmsHPROFILE profile, DWORD *size) {
	cmsUInt32Number length = 0;
	if (!cmsSaveProfileToMem(profile, NULL, &length) || (length < 128)) {
		return NULL;
	}
	BYTE *data = (BYTE*)malloc(length);
	if (data && cmsSaveProfileToMem(profile, data, &length)) {
		// a fixed creation date and no primary platform: the same bytes on every run and system
		static const BYTE DATE[12] = { 0x07, 0xEA, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
		memcpy(data + 24, DATE, sizeof(DATE));
		memset(data + 40, 0, 4);
		*size = length;
		return data;
	}
	free(data);
	return NULL;
}

// created once, kept until the process ends
struct BuiltInProfiles {
	BYTE *data[ICC_BUILTIN_COUNT];
	DWORD size[ICC_BUILTIN_COUNT];

	BuiltInProfiles() {
		cmsContext context = cmsCreateContext(NULL, NULL);
		for (int i = 0; i < ICC_BUILTIN_COUNT; i++) {
			data[i] = NULL;
			size[i] = 0;
			cmsHPROFILE profile = context ? CreateBuiltInProfile(context, i) : NULL;
			if (profile) {
				data[i] = SaveBuiltInProfile(profile, &size[i]);
				cmsCloseProfile(profile);
			}
		}
		if (context) {
			cmsDeleteContext(context);
		}
	}
};

static const BuiltInProfiles &
GetBuiltInProfiles() {
	static const BuiltInProfiles profiles;
	return profiles;
}

// the profile FreeImage assumes for images of this model and depth without one
static int
DefaultProfile(Model model, unsigned depth) {
	if (model == MODEL_GRAY) {
		return (depth == 32) ? FICMS_PROFILE_LINEAR_GRAY : FICMS_PROFILE_GRAY;
	}
	return (depth == 32) ? FICMS_PROFILE_LINEAR_SRGB : FICMS_PROFILE_SRGB;
}

// ----------------------------------------------------------
//   Profiles and the Little CMS context
// ----------------------------------------------------------

static Model
ModelOf(cmsHPROFILE profile) {
	switch (cmsGetDeviceClass(profile)) {
		case cmsSigInputClass:
		case cmsSigDisplayClass:
		case cmsSigOutputClass:
		case cmsSigColorSpaceClass:
			break;
		default:
			return MODEL_NONE;
	}
	switch (cmsGetColorSpace(profile)) {
		case cmsSigGrayData:	return MODEL_GRAY;
		case cmsSigRgbData:		return MODEL_RGB;
		case cmsSigCmykData:	return MODEL_CMYK;
		default:				return MODEL_NONE;
	}
}

// Little CMS errors go to FreeImage_OutputMessageProc unless muted
class Context {
public:
	cmsContext id;
	bool mute;

	Context() : id(NULL), mute(false) {
		id = cmsCreateContext(NULL, this);
		if (id) {
			cmsSetLogErrorHandlerTHR(id, Log);
		}
	}
	~Context() {
		if (id) {
			cmsDeleteContext(id);
		}
	}
	cmsHPROFILE Open(const void *data, DWORD size) {
		if (!id || !data || (size < 128)) {
			return NULL;
		}
		return cmsOpenProfileFromMemTHR(id, data, size);
	}

private:
	static void Log(cmsContext id, cmsUInt32Number, const char *text) {
		const Context *self = (const Context *)cmsGetContextUserData(id);
		if (self && !self->mute && text) {
			FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: Little CMS: %s", text);
		}
	}
	Context(const Context &);
	Context &operator=(const Context &);
};

struct Profile {
	cmsHPROFILE handle;		// NULL for device CMYK
	Model model;
	const void *bytes;		// the profile, to recognise two equal ones
	DWORD size;
	bool tag;				// the result carries this profile

	Profile() : handle(NULL), model(MODEL_NONE), bytes(NULL), size(0), tag(false) {
	}
	~Profile() {
		if (handle) {
			cmsCloseProfile(handle);
		}
	}
	bool Same(const Profile &other) const {
		return bytes && other.bytes && (size == other.size) && ((bytes == other.bytes) || (memcmp(bytes, other.bytes, size) == 0));
	}

private:
	Profile(const Profile &);
	Profile &operator=(const Profile &);
};

// the image's profile, even when the caller passes the image's own profile
static void
AttachProfile(FIBITMAP *dib, const void *data, DWORD size) {
	FIICCPROFILE *icc = FreeImage_GetICCProfile(dib);
	const BYTE *current = (const BYTE*)icc->data;
	const BYTE *bytes = (const BYTE*)data;
	if (current && (bytes >= current) && (bytes < current + icc->size)) {
		if ((bytes == current) && (size == icc->size)) {
			return;
		}
		void *copy = malloc(size);
		if (copy) {
			memcpy(copy, data, size);
			FreeImage_CreateICCProfile(dib, copy, (long)size);
			free(copy);
		} else {
			FreeImage_DestroyICCProfile(dib);
		}
		return;
	}
	FreeImage_CreateICCProfile(dib, (void*)data, (long)size);
}

// the most transforms a display keeps
#define ICC_CACHED_TRANSFORMS 8

// the transforms of one display's loads, which repeat a few profile pairs; shared by threads
class TransformCache {
public:
	TransformCache() : m_context(cmsCreateContext(NULL, NULL)), m_uses(0) {
	}
	~TransformCache() {
		m_entries.clear();
		if (m_context) {
			cmsDeleteContext(m_context);
		}
	}

	// empty when the profiles cannot be linked; out's bytes have to live as long as the cache
	std::shared_ptr<void> Get(const Profile &in, const Profile &out, cmsUInt32Number in_format, cmsUInt32Number out_format, cmsUInt32Number intent, cmsUInt32Number flags) {
		std::shared_ptr<void> transform;
		if (!m_context || !in.bytes || !out.bytes) {
			return transform;
		}
		{
			std::lock_guard<std::mutex> guard(m_lock);
			for (size_t i = 0; i < m_entries.size(); i++) {
				Entry &entry = m_entries[i];
				if ((entry.out == out.bytes) && (entry.out_size == out.size) && (entry.in_format == in_format) && (entry.out_format == out_format) &&
					(entry.intent == intent) && (entry.flags == flags) && (entry.in.size() == in.size) && !memcmp(&entry.in[0], in.bytes, in.size)) {
					entry.used = ++m_uses;
					return entry.transform;
				}
			}
		}
		// made outside the lock: a device link takes tens of milliseconds
		cmsHTRANSFORM created = cmsCreateTransformTHR(m_context, in.handle, in_format, out.handle, out_format, intent, flags);
		if (!created) {
			return transform;
		}
		transform.reset(created, cmsDeleteTransform);
		Entry entry;
		entry.in.assign((const BYTE*)in.bytes, (const BYTE*)in.bytes + in.size);
		entry.out = out.bytes;
		entry.out_size = out.size;
		entry.in_format = in_format;
		entry.out_format = out_format;
		entry.intent = intent;
		entry.flags = flags;
		entry.transform = transform;
		std::lock_guard<std::mutex> guard(m_lock);
		if (m_entries.size() >= ICC_CACHED_TRANSFORMS) {
			size_t oldest = 0;
			for (size_t i = 1; i < m_entries.size(); i++) {
				if (m_entries[i].used < m_entries[oldest].used) {
					oldest = i;
				}
			}
			m_entries.erase(m_entries.begin() + oldest);
		}
		entry.used = ++m_uses;
		m_entries.push_back(entry);
		return transform;
	}

private:
	struct Entry {
		std::vector<BYTE> in;
		const void *out;
		DWORD out_size;
		cmsUInt32Number in_format;
		cmsUInt32Number out_format;
		cmsUInt32Number intent;
		cmsUInt32Number flags;
		std::shared_ptr<void> transform;
		unsigned long long used;
	};

	std::mutex m_lock;
	cmsContext m_context;
	std::vector<Entry> m_entries;
	unsigned long long m_uses;

	TransformCache(const TransformCache &);
	TransformCache &operator=(const TransformCache &);
};

struct RowBuffers {
	BYTE *a;
	BYTE *b;
	BYTE *c;

	RowBuffers() : a(NULL), b(NULL), c(NULL) {
	}
	~RowBuffers() {
		free(a);
		free(b);
		free(c);
	}
	bool Allocate(size_t size_a, size_t size_b, size_t size_c) {
		a = size_a ? (BYTE*)malloc(size_a) : NULL;
		b = size_b ? (BYTE*)malloc(size_b) : NULL;
		c = size_c ? (BYTE*)malloc(size_c) : NULL;
		return (a || !size_a) && (b || !size_b) && (c || !size_c);
	}

private:
	RowBuffers(const RowBuffers &);
	RowBuffers &operator=(const RowBuffers &);
};

// ----------------------------------------------------------
//   The conversion
// ----------------------------------------------------------

class ColorConverter {
public:
	explicit ColorConverter(int flags) : m_flags(flags), m_dib(NULL), m_width(0), m_height(0),
		m_transform(NULL), m_device_in(false), m_device_out(false), m_step(0), m_grey(false),
		m_in_format(0), m_out_format(0), m_ignore_embedded(false), m_embedded(false), m_cache(NULL) {
		memset(&m_px, 0, sizeof(m_px));
	}
	~ColorConverter() {
		if (m_transform && !m_cached_transform) {
			cmsDeleteTransform(m_transform);
		}
	}

	bool SetSource(FIBITMAP *dib);
	bool SetDestination(const void *data, DWORD size, Model required, Model if_null);
	bool SetProof(const void *data, DWORD size);
	FIBITMAP *Convert();
	BOOL Apply();

	Model SourceModel() const {
		return m_px.model;
	}
	// the image is taken as its type's default, whatever profile it embeds; call before SetSource
	void IgnoreEmbedded() {
		m_ignore_embedded = true;
	}
	bool EmbeddedSource() const {
		return m_embedded;
	}
	// the transform comes from the cache, which outlives the converter
	void UseCache(TransformCache *cache) {
		m_cache = cache;
	}
	// FreeImage's default space: grey for grey images, else RGB
	Model DefaultModel() const {
		return (m_px.model == MODEL_GRAY) ? MODEL_GRAY : MODEL_RGB;
	}

private:
	Context m_context;
	int m_flags;
	FIBITMAP *m_dib;
	Pixels m_px;
	int m_width;
	int m_height;
	Profile m_source;
	Profile m_destination;
	Profile m_proof;
	Profile m_device;		// sRGB or grey sRGB, the other side of device CMYK
	cmsHTRANSFORM m_transform;
	bool m_device_in;		// device CMYK source
	bool m_device_out;		// device CMYK destination
	unsigned m_step;		// samples per pixel read by the device CMYK separation
	bool m_grey;			// the separation reads grey
	cmsUInt32Number m_in_format;
	cmsUInt32Number m_out_format;
	bool m_ignore_embedded;
	bool m_embedded;		// the source is the embedded profile
	TransformCache *m_cache;
	std::shared_ptr<void> m_cached_transform;

	bool OpenBuiltIn(Profile &profile, Model model, unsigned depth);
	bool OpenGiven(Profile &profile, const void *data, DWORD size, const char *what);
	bool IsIdentity() const;
	bool CreateTransform(bool same_buffer);
	void Tag(FIBITMAP *dib) const;
	bool Run(FIBITMAP *target, Layout out, bool in_place);
	bool RunTable(FIBITMAP *target, Layout out, bool in_place);
	bool RunRows(FIBITMAP *target, Layout out, bool in_place);
	void Row(const BYTE *src, BYTE *dst, BYTE *buffer_a, BYTE *buffer_b) const;
	void Separate(const BYTE *src, BYTE *dst, unsigned width, unsigned depth) const;

	ColorConverter(const ColorConverter &);
	ColorConverter &operator=(const ColorConverter &);
};

bool ColorConverter::
OpenBuiltIn(Profile &profile, Model model, unsigned depth) {
	DWORD size = 0;
	const void *data = FreeImage_GetBuiltInICCProfile(DefaultProfile(model, depth), &size);
	profile.handle = data ? m_context.Open(data, size) : NULL;
	if (!profile.handle) {
		FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: the built-in profiles are not available");
		return false;
	}
	profile.model = model;
	profile.bytes = data;
	profile.size = size;
	profile.tag = false;
	return true;
}

bool ColorConverter::
OpenGiven(Profile &profile, const void *data, DWORD size, const char *what) {
	if ((size < 128) || (size > 0x7FFFFFFF)) {
		FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: the %s profile has an invalid size", what);
		return false;
	}
	profile.handle = m_context.Open(data, size);
	if (!profile.handle) {
		FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: the %s profile is invalid", what);
		return false;
	}
	profile.model = ModelOf(profile.handle);
	if (profile.model == MODEL_NONE) {
		FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: the %s profile is not a grey, RGB or CMYK device profile", what);
		return false;
	}
	profile.bytes = data;
	profile.size = size;
	profile.tag = true;
	return true;
}

bool ColorConverter::
SetSource(FIBITMAP *dib) {
	if (!m_context.id || !FreeImage_HasPixels(dib)) {
		return false;
	}
	const char *error = AnalysePixels(dib, m_px);
	if (error) {
		FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: %s", error);
		return false;
	}
	m_dib = dib;
	m_width = (int)FreeImage_GetWidth(dib);
	m_height = (int)FreeImage_GetHeight(dib);

	const FIICCPROFILE *icc = FreeImage_GetICCProfile(dib);
	if (!m_ignore_embedded && icc->data && icc->size) {
		m_context.mute = true;
		cmsHPROFILE handle = m_context.Open(icc->data, icc->size);
		m_context.mute = false;
		if (!handle) {
			FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: the embedded profile is invalid and is ignored");
		} else {
			const Model model = ModelOf(handle);
			const bool indexed = (m_px.layout == LAYOUT_INDEXED) || (m_px.layout == LAYOUT_GRAY8);
			// a grey palette may come with an RGB profile
			if ((model == m_px.model) || (indexed && (m_px.model == MODEL_GRAY) && (model == MODEL_RGB))) {
				m_px.model = model;
				m_source.handle = handle;
				m_source.model = model;
				m_source.bytes = icc->data;
				m_source.size = icc->size;
				m_embedded = true;
			} else {
				cmsCloseProfile(handle);
				FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: the embedded profile does not match the pixels and is ignored");
			}
		}
	}
	if (!m_source.handle) {
		if (m_px.model == MODEL_CMYK) {
			m_source.model = MODEL_CMYK;
		} else if (!OpenBuiltIn(m_source, m_px.model, m_px.depth)) {
			return false;
		}
	}
	return true;
}

bool ColorConverter::
SetDestination(const void *data, DWORD size, Model required, Model if_null) {
	if (data) {
		if (!OpenGiven(m_destination, data, size, "destination")) {
			return false;
		}
		if ((required != MODEL_NONE) && (m_destination.model != required)) {
			FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: the destination profile is not a%s profile", (required == MODEL_CMYK) ? " CMYK" : (required == MODEL_RGB) ? "n RGB" : " grey");
			return false;
		}
		return true;
	}
	if (if_null == MODEL_CMYK) {
		m_destination.model = MODEL_CMYK;
		return true;
	}
	return OpenBuiltIn(m_destination, if_null, m_px.depth);
}

bool ColorConverter::
SetProof(const void *data, DWORD size) {
	if (!data) {
		FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: soft proofing needs the profile of the proofing device");
		return false;
	}
	if (!OpenGiven(m_proof, data, size, "proofing")) {
		return false;
	}
	m_proof.tag = false;
	return true;
}

bool ColorConverter::
IsIdentity() const {
	if (m_proof.handle || (m_source.model != m_destination.model)) {
		return false;
	}
	if (!m_source.handle && !m_destination.handle) {
		return true;
	}
	return m_source.Same(m_destination);
}

// the Little CMS stage, none when both sides are the same profile and the samples can be copied
bool ColorConverter::
CreateTransform(bool same_buffer) {
	const Profile &in = m_device_in ? m_device : m_source;
	const Profile &out = m_device_out ? m_device : m_destination;
	if (!m_proof.handle && in.Same(out) && (m_device_out || (m_in_format == m_out_format))) {
		return true;
	}

	cmsUInt32Number flags = 0;
	if (m_flags & FICMS_BLACKPOINT_COMPENSATION) {
		flags |= cmsFLAGS_BLACKPOINTCOMPENSATION;
	}
	if (!same_buffer && T_EXTRA(m_in_format) && T_EXTRA(m_out_format)) {
		flags |= cmsFLAGS_COPY_ALPHA;
	}
	// Little CMS's precalculated 16-bit tables are coarser than its 8-bit path: 16 bits are computed exactly
	if ((T_BYTES(m_in_format) == 2) || (T_BYTES(m_out_format) == 2)) {
		flags |= cmsFLAGS_NOOPTIMIZE;
	}
	const cmsUInt32Number intent = (cmsUInt32Number)(m_flags & 0xFF);

	if (m_proof.handle) {
		flags |= cmsFLAGS_SOFTPROOFING;
		if (m_flags & FICMS_GAMUT_CHECK) {
			flags |= cmsFLAGS_GAMUTCHECK;
		}
		const cmsUInt32Number proof_intent = (m_flags & FICMS_SIMULATE_PAPER) ? INTENT_ABSOLUTE_COLORIMETRIC : INTENT_RELATIVE_COLORIMETRIC;
		m_transform = cmsCreateProofingTransformTHR(m_context.id, in.handle, m_in_format, out.handle, m_out_format, m_proof.handle, intent, proof_intent, flags);
		// without a gamut table Little CMS 2.19 still takes its gamut-check path and crashes
		if (m_transform && (flags & cmsFLAGS_GAMUTCHECK) && !cmsGetTransformGamutCheckPipeline(m_transform)) {
			cmsDeleteTransform(m_transform);
			m_transform = NULL;
			FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: the proofing profile cannot be used for a gamut check");
			return false;
		}
	} else if (m_cache) {
		m_cached_transform = m_cache->Get(in, out, m_in_format, m_out_format, intent, flags);
		m_transform = m_cached_transform.get();
	} else {
		m_transform = cmsCreateTransformTHR(m_context.id, in.handle, m_in_format, out.handle, m_out_format, intent, flags);
	}
	if (!m_transform) {
		FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: the profiles cannot be linked");
		return false;
	}
	return true;
}

// the destination profile, or none for FreeImage's default space
void ColorConverter::
Tag(FIBITMAP *dib) const {
	// before the source profile, which may be the image's own, is replaced
	const bool converted = !IsIdentity();
	if (m_destination.tag) {
		AttachProfile(dib, m_destination.bytes, m_destination.size);
	} else {
		FreeImage_DestroyICCProfile(dib);
	}
	FIICCPROFILE *icc = FreeImage_GetICCProfile(dib);
	if (m_destination.model == MODEL_CMYK) {
		icc->flags |= FIICC_COLOR_IS_CMYK;
	} else {
		icc->flags &= ~FIICC_COLOR_IS_CMYK;
	}
	// the CICP tag describes the samples before the conversion
	if (converted) {
		FreeImage_SetMetadata(FIMD_CUSTOM, dib, "CICP", NULL);
	}
}

bool ColorConverter::
Run(FIBITMAP *target, Layout out, bool in_place) {
	m_device_in = (m_source.model == MODEL_CMYK) && !m_source.handle;
	m_device_out = (m_destination.model == MODEL_CMYK) && !m_destination.handle;
	m_grey = m_device_out && (m_source.model == MODEL_GRAY);
	if (m_device_in || m_device_out) {
		if (!OpenBuiltIn(m_device, m_grey ? MODEL_GRAY : MODEL_RGB, (m_px.depth == 8) ? 8 : 16)) {
			return false;
		}
	}
	if ((m_px.layout == LAYOUT_INDEXED) || (m_px.layout == LAYOUT_GRAY8)) {
		return RunTable(target, out, in_place);
	}
	return RunRows(target, out, in_place);
}

// device CMYK from the stage's output, or from the source when there is no stage
void ColorConverter::
Separate(const BYTE *src, BYTE *dst, unsigned width, unsigned depth) const {
	if (depth == 8) {
		RGBToDeviceCMYK<BYTE>(src, m_step, m_grey, FI_RGBA_RED, FI_RGBA_GREEN, FI_RGBA_BLUE, dst, width);
	} else {
		RGBToDeviceCMYK<WORD>((const WORD*)src, m_step, m_grey, 0, 1, 2, (WORD*)dst, width);
	}
}

// palettes and 8-bit grey: the 256 possible values go through a table
bool ColorConverter::
RunTable(FIBITMAP *target, Layout out, bool in_place) {
	const bool alpha = m_px.alpha && (out == LAYOUT_RGBA8);
	const bool grey_in = (m_px.model == MODEL_GRAY);

	if (grey_in) {
		m_in_format = alpha ? TYPE_GRAYA_8 : TYPE_GRAY_8;
	} else {
		m_in_format = alpha ? ICC_TYPE_RGBA_8 : ICC_TYPE_RGB_8;
	}
	if (m_device_out) {
		m_out_format = m_grey ? TYPE_GRAY_8 : ICC_TYPE_RGB_8;
	} else if (out == LAYOUT_INDEXED) {
		m_out_format = (m_destination.model == MODEL_GRAY) ? TYPE_GRAY_8 : ICC_TYPE_RGB_8;
	} else {
		m_out_format = LayoutFormat(out, false);
	}
	if (!CreateTransform(false)) {
		return false;
	}

	// the entries in the stage's input format
	BYTE entries[256 * 4];
	{
		const RGBQUAD *palette = FreeImage_GetPalette(m_dib);
		const BYTE *table = FreeImage_GetTransparencyTable(m_dib);
		const unsigned count = (alpha && table) ? FreeImage_GetTransparencyCount(m_dib) : 0;
		const unsigned bytes = PixelBytes(m_in_format);
		for (unsigned i = 0; i < 256; i++) {
			RGBQUAD color = { 0, 0, 0, 0 };
			if (i < m_px.colors) {
				color = palette[i];
			}
			const BYTE a = (i < count) ? table[i] : 0xFF;
			BYTE *entry = entries + i * bytes;
			if (grey_in) {
				entry[0] = color.rgbRed;
				if (alpha) entry[1] = a;
			} else {
				entry[FI_RGBA_RED] = color.rgbRed;
				entry[FI_RGBA_GREEN] = color.rgbGreen;
				entry[FI_RGBA_BLUE] = color.rgbBlue;
				if (alpha) entry[FI_RGBA_ALPHA] = a;
			}
		}
	}

	// the converted entries in the output format
	const unsigned lut_bytes = m_device_out ? 4 : PixelBytes(m_out_format);
	BYTE lut[256 * 4];
	BYTE middle[256 * 4];
	const BYTE *p = entries;
	if (m_transform) {
		BYTE *t = m_device_out ? middle : lut;
		cmsDoTransform(m_transform, p, t, 256);
		p = t;
	}
	if (m_device_out) {
		m_step = m_transform ? PixelBytes(m_out_format) : PixelBytes(m_in_format);
		Separate(p, lut, 256, 8);
		p = lut;
	}
	if (p != lut) {
		memcpy(lut, p, 256 * lut_bytes);
	}

	if (out == LAYOUT_INDEXED) {
		// the palette changes, the indices stay
		RGBQUAD *palette = FreeImage_GetPalette(target);
		const bool grey_out = (m_destination.model == MODEL_GRAY);
		for (unsigned i = 0; i < m_px.colors; i++) {
			const BYTE *entry = lut + i * lut_bytes;
			if (grey_out) {
				palette[i].rgbRed = palette[i].rgbGreen = palette[i].rgbBlue = entry[0];
			} else {
				palette[i].rgbRed = entry[FI_RGBA_RED];
				palette[i].rgbGreen = entry[FI_RGBA_GREEN];
				palette[i].rgbBlue = entry[FI_RGBA_BLUE];
			}
		}
		return true;
	}

	const bool threaded = (m_height > 1) && ((UINT64)m_width * (UINT64)m_height >= ICC_PARALLEL_PIXELS);
	const unsigned width = (unsigned)m_width;

	if (in_place) {
		// an 8-bit grey ramp keeps its palette: the values change
		BYTE index[256];
		for (unsigned i = 0; i < 256; i++) {
			index[i] = m_px.reversed ? (BYTE)(255 - lut[i]) : lut[i];
		}
		#pragma omp parallel for schedule(static) default(shared) if(threaded)
		for (int y = 0; y < m_height; y++) {
			BYTE *bits = FreeImage_GetScanLine(target, y);
			for (unsigned x = 0; x < width; x++) {
				bits[x] = index[bits[x]];
			}
		}
		return true;
	}

	const unsigned bpp = FreeImage_GetBPP(m_dib);
	#pragma omp parallel for schedule(static) default(shared) if(threaded)
	for (int y = 0; y < m_height; y++) {
		const BYTE *src = FreeImage_GetScanLine(m_dib, y);
		BYTE *dst = FreeImage_GetScanLine(target, y);
		for (unsigned x = 0; x < width; x++) {
			unsigned i;
			if (bpp == 8) {
				i = src[x];
			} else if (bpp == 4) {
				i = (x & 1) ? (src[x >> 1] & 0x0F) : (src[x >> 1] >> 4);
			} else {
				i = (src[x >> 3] >> (7 - (x & 7))) & 1;
			}
			const BYTE *entry = lut + i * lut_bytes;
			for (unsigned k = 0; k < lut_bytes; k++) {
				dst[k] = entry[k];
			}
			dst += lut_bytes;
		}
	}
	return true;
}

// one row: expansion or device CMYK, the Little CMS stage, the device CMYK separation
void ColorConverter::
Row(const BYTE *src, BYTE *dst, BYTE *buffer_a, BYTE *buffer_b) const {
	const unsigned width = (unsigned)m_width;
	const bool copy_out = !m_transform && !m_device_out;
	const BYTE *p = src;

	if ((m_px.layout == LAYOUT_555) || (m_px.layout == LAYOUT_565)) {
		BYTE *t = copy_out ? dst : buffer_a;
		if (m_px.layout == LAYOUT_565) {
			FreeImage_ConvertLine16To24_565(t, (BYTE*)p, (int)width);
		} else {
			FreeImage_ConvertLine16To24_555(t, (BYTE*)p, (int)width);
		}
		p = t;
	} else if (m_device_in) {
		BYTE *t = copy_out ? dst : buffer_a;
		if (m_px.depth == 8) {
			DeviceCMYKToRGB8(p, t, width);
		} else {
			DeviceCMYKToRGB16((const WORD*)p, (WORD*)t, width);
		}
		p = t;
	}
	if (m_transform) {
		BYTE *t = m_device_out ? buffer_b : dst;
		cmsDoTransform(m_transform, p, t, width);
		p = t;
	}
	if (m_device_out) {
		Separate(p, dst, width, (m_px.depth == 8) ? 8 : 16);
		p = dst;
	}
	if (p != dst) {
		memcpy(dst, p, (size_t)width * PixelBytes(m_out_format));
	}
}

// every other layout: row by row
bool ColorConverter::
RunRows(FIBITMAP *target, Layout out, bool in_place) {
	const bool d8 = (m_px.depth == 8);
	// CMYK to RGBA in place: through a row buffer, alpha set opaque
	const bool opaque = in_place && (out != m_px.layout);

	if (m_device_in) {
		m_in_format = d8 ? ICC_TYPE_RGB_8 : TYPE_RGB_16;
	} else if ((m_px.layout == LAYOUT_555) || (m_px.layout == LAYOUT_565)) {
		m_in_format = ICC_TYPE_RGB_8;
	} else {
		m_in_format = LayoutFormat(m_px.layout, m_px.reversed);
	}
	if (m_device_out) {
		if (m_grey) {
			m_out_format = d8 ? TYPE_GRAY_8 : TYPE_GRAY_16;
		} else {
			m_out_format = d8 ? ICC_TYPE_RGB_8 : TYPE_RGB_16;
		}
	} else if (opaque) {
		m_out_format = d8 ? ICC_TYPE_RGB_8 : TYPE_RGB_16;
	} else {
		m_out_format = LayoutFormat(out, (out == m_px.layout) && m_px.reversed);
	}
	const bool same_buffer = in_place && !opaque && !m_device_in;
	if (!CreateTransform(same_buffer)) {
		return false;
	}
	if (m_device_out) {
		m_step = m_transform ? T_CHANNELS(m_out_format) + T_EXTRA(m_out_format) : T_CHANNELS(m_in_format) + T_EXTRA(m_in_format);
	}
	if (in_place && !m_transform && !m_device_in) {
		// nothing changes
		return true;
	}

	const size_t width = (size_t)m_width;
	const bool expand = m_device_in || (m_px.layout == LAYOUT_555) || (m_px.layout == LAYOUT_565);
	const size_t size_a = expand ? width * PixelBytes(m_in_format) : 0;
	const size_t size_b = (m_device_out && m_transform) ? width * PixelBytes(m_out_format) : 0;
	const size_t size_c = opaque ? width * PixelBytes(m_out_format) : 0;

	const bool threaded = (m_height > 1) && ((UINT64)m_width * (UINT64)m_height >= ICC_PARALLEL_PIXELS);
	bool failed = false;

	#pragma omp parallel default(shared) if(threaded)
	{
		RowBuffers buffers;
		if (!buffers.Allocate(size_a, size_b, size_c)) {
			#pragma omp critical
			failed = true;
		}
		// nothing is written unless every thread has its buffers
		#pragma omp barrier
		if (!failed) {
			#pragma omp for schedule(static)
			for (int y = 0; y < m_height; y++) {
				BYTE *dst = FreeImage_GetScanLine(target, y);
				if (opaque) {
					Row(dst, buffers.c, buffers.a, buffers.b);
					if (d8) {
						PackOpaque8(buffers.c, dst, (unsigned)width);
					} else {
						PackOpaque16((const WORD*)buffers.c, (WORD*)dst, (unsigned)width);
					}
				} else {
					Row(in_place ? dst : FreeImage_GetScanLine(m_dib, y), dst, buffers.a, buffers.b);
				}
			}
		}
	}
	if (failed) {
		FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: %s", FI_MSG_ERROR_MEMORY);
		return false;
	}
	return true;
}

FIBITMAP *ColorConverter::
Convert() {
	const Layout out = OutputLayout(m_px, m_destination.model);
	if (out == LAYOUT_NONE) {
		return NULL;
	}
	if (out == m_px.layout) {
		// the same pixel format: a copy converted in place
		FIBITMAP *dst = FreeImage_Clone(m_dib);
		if (!dst) {
			return NULL;
		}
		if (!IsIdentity() && !Run(dst, out, true)) {
			FreeImage_Unload(dst);
			return NULL;
		}
		Tag(dst);
		return dst;
	}
	FIBITMAP *dst = AllocateLayout(out, m_width, m_height);
	if (!dst) {
		FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: %s", FI_MSG_ERROR_DIB_MEMORY);
		return NULL;
	}
	FreeImage_CloneMetadata(dst, m_dib);
	if (!Run(dst, out, false)) {
		FreeImage_Unload(dst);
		return NULL;
	}
	Tag(dst);
	return dst;
}

BOOL ColorConverter::
Apply() {
	if (IsIdentity()) {
		Tag(m_dib);
		return TRUE;
	}
	const Layout out = InPlaceLayout(m_px, m_destination.model);
	if (out == LAYOUT_NONE) {
		FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: this conversion changes the pixel format, use FreeImage_ConvertToICCProfile");
		return FALSE;
	}
	if (!Run(m_dib, out, true)) {
		return FALSE;
	}
	Tag(m_dib);
	return TRUE;
}

// ----------------------------------------------------------
//   The display's profile
// ----------------------------------------------------------

// the largest display profile read
#define ICC_DISPLAY_MAX_SIZE (16 * 1024 * 1024)

// what FIF_LOAD_DISPLAY_ICC converts to
struct DisplayState {
	std::vector<BYTE> rgb;		// the display's profile, or sRGB
	std::vector<BYTE> grey;		// the display's greys, for grey images
	int flags;					// rendering intent | FICMS_BLACKPOINT_COMPENSATION
	bool srgb;					// rgb and grey are FreeImage's sRGB and grey
	mutable TransformCache transforms;

	DisplayState() : flags(0), srgb(true) {
	}
};

// the system's display profile: key identifies it, bytes holds it once read
struct DisplayQuery {
	std::vector<BYTE> key;
	std::vector<BYTE> bytes;
#ifdef _WIN32
	std::wstring path;
#endif
};

static void
Append(std::vector<BYTE> &to, const void *data, size_t size) {
	const BYTE *bytes = (const BYTE*)data;
	to.insert(to.end(), bytes, bytes + size);
}

#ifdef _WIN32

// DISPLAYCONFIG_* structures, declared here: WINVER 0x0500 and older SDKs hide or lack them
struct DisplayConfigHeader {		// DISPLAYCONFIG_DEVICE_INFO_HEADER
	UINT32 type;
	UINT32 size;
	LUID adapter;
	UINT32 id;
};

struct DisplayConfigPath {			// DISPLAYCONFIG_PATH_INFO
	LUID source_adapter;
	UINT32 source_id;
	UINT32 source_mode;
	UINT32 source_status;
	LUID target_adapter;
	UINT32 target_id;
	UINT32 target_fields[9];
	UINT32 flags;
};

struct DisplayConfigMode {			// DISPLAYCONFIG_MODE_INFO
	UINT64 fields[8];
};

struct DisplayConfigSourceName {	// DISPLAYCONFIG_SOURCE_DEVICE_NAME
	DisplayConfigHeader header;
	WCHAR gdi_name[CCHDEVICENAME];
};

struct DisplayConfigColor {			// DISPLAYCONFIG_GET_ADVANCED_COLOR_INFO, with _2's activeColorMode
	DisplayConfigHeader header;
	UINT32 bits;
	UINT32 encoding;
	UINT32 depth;
	UINT32 mode;
};

static_assert(sizeof(DisplayConfigPath) == 72, "DISPLAYCONFIG_PATH_INFO");
static_assert(sizeof(DisplayConfigMode) == 64, "DISPLAYCONFIG_MODE_INFO");
static_assert(sizeof(DisplayConfigSourceName) == 84, "DISPLAYCONFIG_SOURCE_DEVICE_NAME");
static_assert(sizeof(DisplayConfigColor) == 36, "DISPLAYCONFIG_GET_ADVANCED_COLOR_INFO_2");

#define ICC_QDC_ONLY_ACTIVE_PATHS				0x00000002
#define ICC_DISPLAYCONFIG_SOURCE_NAME			1
#define ICC_DISPLAYCONFIG_ADVANCED_COLOR		9
#define ICC_DISPLAYCONFIG_ADVANCED_COLOR_2		15

typedef HMONITOR (WINAPI *MonitorFromPointProc)(POINT, DWORD);
typedef BOOL (WINAPI *GetMonitorInfoWProc)(HMONITOR, MONITORINFO*);
typedef HDC (WINAPI *CreateICWProc)(LPCWSTR, LPCWSTR, LPCWSTR, const void*);
typedef BOOL (WINAPI *GetICMProfileWProc)(HDC, LPDWORD, LPWSTR);
typedef BOOL (WINAPI *DeleteDCProc)(HDC);
typedef LONG (WINAPI *GetDisplayConfigBufferSizesProc)(UINT32, UINT32*, UINT32*);
typedef LONG (WINAPI *QueryDisplayConfigProc)(UINT32, UINT32*, DisplayConfigPath*, UINT32*, DisplayConfigMode*, void*);
typedef LONG (WINAPI *DisplayConfigGetDeviceInfoProc)(DisplayConfigHeader*);

// user32 and gdi32, resolved when a display profile is first needed: no import library
struct DisplayAPI {
	MonitorFromPointProc monitor_from_point;
	GetMonitorInfoWProc get_monitor_info;
	CreateICWProc create_ic;
	GetICMProfileWProc get_icm_profile;
	DeleteDCProc delete_dc;
	GetDisplayConfigBufferSizesProc buffer_sizes;
	QueryDisplayConfigProc query_config;
	DisplayConfigGetDeviceInfoProc device_info;

	DisplayAPI() {
		HMODULE user32 = LoadLibraryW(L"user32.dll");
		HMODULE gdi32 = LoadLibraryW(L"gdi32.dll");
		monitor_from_point = user32 ? (MonitorFromPointProc)GetProcAddress(user32, "MonitorFromPoint") : NULL;
		get_monitor_info = user32 ? (GetMonitorInfoWProc)GetProcAddress(user32, "GetMonitorInfoW") : NULL;
		buffer_sizes = user32 ? (GetDisplayConfigBufferSizesProc)GetProcAddress(user32, "GetDisplayConfigBufferSizes") : NULL;
		query_config = user32 ? (QueryDisplayConfigProc)GetProcAddress(user32, "QueryDisplayConfig") : NULL;
		device_info = user32 ? (DisplayConfigGetDeviceInfoProc)GetProcAddress(user32, "DisplayConfigGetDeviceInfo") : NULL;
		create_ic = gdi32 ? (CreateICWProc)GetProcAddress(gdi32, "CreateICW") : NULL;
		get_icm_profile = gdi32 ? (GetICMProfileWProc)GetProcAddress(gdi32, "GetICMProfileW") : NULL;
		delete_dc = gdi32 ? (DeleteDCProc)GetProcAddress(gdi32, "DeleteDC") : NULL;
	}
};

static const DisplayAPI &
GetDisplayAPI() {
	static const DisplayAPI api;
	return api;
}

// HDR or Auto Color Management: Windows itself converts what applications draw from sRGB
static bool
AdvancedColorActive(const DisplayAPI &api, const WCHAR *device) {
	if (!api.buffer_sizes || !api.query_config || !api.device_info) {
		return false;
	}
	std::vector<DisplayConfigPath> paths;
	std::vector<DisplayConfigMode> modes;
	LONG result = ERROR_INSUFFICIENT_BUFFER;
	// the configuration may change between the two calls
	for (int attempt = 0; (attempt < 4) && (result == ERROR_INSUFFICIENT_BUFFER); attempt++) {
		UINT32 path_count = 0, mode_count = 0;
		if (api.buffer_sizes(ICC_QDC_ONLY_ACTIVE_PATHS, &path_count, &mode_count) != ERROR_SUCCESS) {
			return false;
		}
		paths.resize(path_count + 1);
		modes.resize(mode_count + 1);
		result = api.query_config(ICC_QDC_ONLY_ACTIVE_PATHS, &path_count, &paths[0], &mode_count, &modes[0], NULL);
		paths.resize(path_count);
	}
	if (result != ERROR_SUCCESS) {
		return false;
	}
	for (size_t i = 0; i < paths.size(); i++) {
		DisplayConfigSourceName name;
		memset(&name, 0, sizeof(name));
		name.header.type = ICC_DISPLAYCONFIG_SOURCE_NAME;
		name.header.size = sizeof(name);
		name.header.adapter = paths[i].source_adapter;
		name.header.id = paths[i].source_id;
		if ((api.device_info(&name.header) != ERROR_SUCCESS) || wcsncmp(name.gdi_name, device, CCHDEVICENAME)) {
			continue;
		}
		DisplayConfigColor color;
		memset(&color, 0, sizeof(color));
		color.header.type = ICC_DISPLAYCONFIG_ADVANCED_COLOR_2;
		color.header.size = sizeof(color);
		color.header.adapter = paths[i].target_adapter;
		color.header.id = paths[i].target_id;
		if (api.device_info(&color.header) == ERROR_SUCCESS) {
			// wide color gamut or HDR
			return (color.mode != 0);
		}
		// before Windows 11 24H2: advancedColorEnabled
		color.header.type = ICC_DISPLAYCONFIG_ADVANCED_COLOR;
		color.header.size = sizeof(color) - sizeof(color.mode);
		return (api.device_info(&color.header) == ERROR_SUCCESS) && (color.bits & 0x2);
	}
	return false;
}

// the primary monitor's profile: its file and when that changed
static void
QuerySystem(DisplayQuery &query) {
	const DisplayAPI &api = GetDisplayAPI();
	if (!api.monitor_from_point || !api.get_monitor_info || !api.create_ic || !api.get_icm_profile || !api.delete_dc) {
		return;
	}
	const POINT origin = { 0, 0 };
	HMONITOR monitor = api.monitor_from_point(origin, MONITOR_DEFAULTTOPRIMARY);
	MONITORINFOEXW info;
	memset(&info, 0, sizeof(info));
	info.cbSize = sizeof(info);
	if (!monitor || !api.get_monitor_info(monitor, (MONITORINFO*)&info)) {
		return;
	}
	if (AdvancedColorActive(api, info.szDevice)) {
		static const char ADVANCED[] = "advanced color";
		Append(query.key, ADVANCED, sizeof(ADVANCED));
		return;
	}
	HDC ic = api.create_ic(info.szDevice, NULL, NULL, NULL);
	if (!ic) {
		return;
	}
	std::vector<WCHAR> path(MAX_PATH + 1, 0);
	DWORD length = (DWORD)path.size();
	BOOL found = api.get_icm_profile(ic, &length, &path[0]);
	if (!found && (GetLastError() == ERROR_INSUFFICIENT_BUFFER) && (length > path.size()) && (length < 32768)) {
		path.assign(length + 1, 0);
		length = (DWORD)path.size();
		found = api.get_icm_profile(ic, &length, &path[0]);
	}
	api.delete_dc(ic);
	path.back() = 0;
	WIN32_FILE_ATTRIBUTE_DATA data;
	if (!found || !GetFileAttributesExW(&path[0], GetFileExInfoStandard, &data)) {
		return;
	}
	query.path = &path[0];
	Append(query.key, query.path.c_str(), query.path.size() * sizeof(WCHAR));
	Append(query.key, &data.nFileSizeHigh, sizeof(data.nFileSizeHigh));
	Append(query.key, &data.nFileSizeLow, sizeof(data.nFileSizeLow));
	Append(query.key, &data.ftLastWriteTime, sizeof(data.ftLastWriteTime));
}

static void
ReadSystem(DisplayQuery &query) {
	if (query.path.empty()) {
		return;
	}
	FILE *file = _wfopen(query.path.c_str(), L"rb");
	if (!file) {
		return;
	}
	if (fseek(file, 0, SEEK_END) == 0) {
		const long size = ftell(file);
		if ((size >= 128) && (size <= ICC_DISPLAY_MAX_SIZE) && (fseek(file, 0, SEEK_SET) == 0)) {
			query.bytes.resize((size_t)size);
			if (fread(&query.bytes[0], 1, (size_t)size, file) != (size_t)size) {
				query.bytes.clear();
			}
		}
	}
	fclose(file);
}

#elif defined(__linux__)

// libxcb, loaded when a display profile is first needed; X11 wire structures, declared here
struct XcbConnection;

struct XcbScreen {
	uint32_t root;
};

struct XcbScreenIterator {
	XcbScreen *data;
	int rem;
	int index;
};

struct XcbCookie {
	unsigned int sequence;
};

struct XcbAtomReply {
	uint8_t response_type;
	uint8_t pad0;
	uint16_t sequence;
	uint32_t length;
	uint32_t atom;
};

struct XcbPropertyReply {
	uint8_t response_type;
	uint8_t format;
	uint16_t sequence;
	uint32_t length;
	uint32_t type;
	uint32_t bytes_after;
	uint32_t value_len;
	uint8_t pad0[12];
};

template <class T> static bool
Resolve(void *library, const char *name, T &function) {
	void *address = dlsym(library, name);
	memcpy(&function, &address, sizeof(function));
	return (address != NULL);
}

// not Xlib: its error handlers end the process
struct XcbAPI {
	XcbConnection *(*connect)(const char*, int*);
	int (*has_error)(XcbConnection*);
	void (*disconnect)(XcbConnection*);
	const void *(*get_setup)(XcbConnection*);
	XcbScreenIterator (*roots)(const void*);
	void (*next_screen)(XcbScreenIterator*);
	XcbCookie (*intern_atom)(XcbConnection*, uint8_t, uint16_t, const char*);
	XcbAtomReply *(*intern_atom_reply)(XcbConnection*, XcbCookie, void**);
	XcbCookie (*get_property)(XcbConnection*, uint8_t, uint32_t, uint32_t, uint32_t, uint32_t, uint32_t);
	XcbPropertyReply *(*get_property_reply)(XcbConnection*, XcbCookie, void**);
	void *(*value)(const XcbPropertyReply*);
	int (*value_length)(const XcbPropertyReply*);
	bool usable;

	XcbAPI() : usable(false) {
		void *library = dlopen("libxcb.so.1", RTLD_LAZY | RTLD_LOCAL);
		usable = library &&
			Resolve(library, "xcb_connect", connect) &&
			Resolve(library, "xcb_connection_has_error", has_error) &&
			Resolve(library, "xcb_disconnect", disconnect) &&
			Resolve(library, "xcb_get_setup", get_setup) &&
			Resolve(library, "xcb_setup_roots_iterator", roots) &&
			Resolve(library, "xcb_screen_next", next_screen) &&
			Resolve(library, "xcb_intern_atom", intern_atom) &&
			Resolve(library, "xcb_intern_atom_reply", intern_atom_reply) &&
			Resolve(library, "xcb_get_property", get_property) &&
			Resolve(library, "xcb_get_property_reply", get_property_reply) &&
			Resolve(library, "xcb_get_property_value", value) &&
			Resolve(library, "xcb_get_property_value_length", value_length);
	}
};

static const XcbAPI &
GetXcbAPI() {
	static const XcbAPI api;
	return api;
}

// _ICC_PROFILE on the root window of $DISPLAY's screen (ICC Profiles in X)
static void
QuerySystem(DisplayQuery &query) {
	const char *display = getenv("DISPLAY");
	if (!display || !*display) {
		return;
	}
	const XcbAPI &api = GetXcbAPI();
	if (!api.usable) {
		return;
	}
	int screen = 0;
	XcbConnection *connection = api.connect(NULL, &screen);
	if (!connection) {
		return;
	}
	if (!api.has_error(connection)) {
		XcbScreenIterator roots = api.roots(api.get_setup(connection));
		for (int i = 0; (i < screen) && (roots.rem > 0); i++) {
			api.next_screen(&roots);
		}
		if ((roots.rem > 0) && roots.data) {
			static const char NAME[] = "_ICC_PROFILE";
			void *error = NULL;
			XcbAtomReply *atom = api.intern_atom_reply(connection, api.intern_atom(connection, 1, (uint16_t)(sizeof(NAME) - 1), NAME), &error);
			free(error);
			if (atom && atom->atom) {
				error = NULL;
				XcbPropertyReply *property = api.get_property_reply(connection,
					api.get_property(connection, 0, roots.data->root, atom->atom, 0, 0, ICC_DISPLAY_MAX_SIZE / 4), &error);
				free(error);
				if (property && (property->format == 8) && !property->bytes_after) {
					const int length = api.value_length(property);
					if (length > 0) {
						Append(query.bytes, api.value(property), (size_t)length);
					}
				}
				free(property);
			}
			free(atom);
		}
	}
	api.disconnect(connection);
	query.key = query.bytes;
}

static void
ReadSystem(DisplayQuery &) {
}

#else

static void
QuerySystem(DisplayQuery &) {
}

static void
ReadSystem(DisplayQuery &) {
}

#endif // _WIN32

static void
BuiltInBytes(int which, std::vector<BYTE> &to) {
	DWORD size = 0;
	const void *data = FreeImage_GetBuiltInICCProfile(which, &size);
	to.clear();
	if (data) {
		Append(to, data, size);
	}
}

// FreeImage's sRGB or grey through the profile comes back within two 8-bit steps (colord's sRGB.icc: one)
static bool
Equivalent(const Context &context, cmsHPROFILE builtin, cmsHPROFILE profile, bool grey) {
	const cmsUInt32Number format = grey ? TYPE_GRAY_16 : TYPE_RGB_16;
	cmsHTRANSFORM transform = cmsCreateTransformTHR(context.id, builtin, format, profile, format, INTENT_RELATIVE_COLORIMETRIC, cmsFLAGS_NOOPTIMIZE);
	if (!transform) {
		return false;
	}
	const unsigned N = 17;
	const unsigned count = grey ? 1024 : N * N * N;
	std::vector<WORD> in(grey ? count : count * 3), out(in.size());
	for (unsigned i = 0; i < count; i++) {
		if (grey) {
			in[i] = (WORD)(i * 65535 / (count - 1));
		} else {
			in[3 * i] = (WORD)((i / (N * N)) * 65535 / (N - 1));
			in[3 * i + 1] = (WORD)(((i / N) % N) * 65535 / (N - 1));
			in[3 * i + 2] = (WORD)((i % N) * 65535 / (N - 1));
		}
	}
	cmsDoTransform(transform, &in[0], &out[0], count);
	cmsDeleteTransform(transform);
	for (size_t i = 0; i < in.size(); i++) {
		if (abs((int)in[i] - (int)out[i]) > 2 * 257) {
			return false;
		}
	}
	return true;
}

// the largest profile checked for being sRGB or grey in all but name
#define ICC_TWIN_MAX_SIZE (1024 * 1024)
// the most profiles whose answer is kept
#define ICC_TWIN_ENTRIES 16

// embedded profiles that FreeImage's sRGB or grey stand for; each is checked once
class TwinCache {
public:
	bool IsTwin(const void *bytes, DWORD size) {
		if (!bytes || (size < 128) || (size > ICC_TWIN_MAX_SIZE)) {
			return false;
		}
		{
			std::lock_guard<std::mutex> guard(m_lock);
			for (size_t i = 0; i < m_entries.size(); i++) {
				if ((m_entries[i].bytes.size() == size) && !memcmp(&m_entries[i].bytes[0], bytes, size)) {
					return m_entries[i].twin;
				}
			}
		}
		Entry entry;
		entry.twin = Check(bytes, size);
		entry.bytes.assign((const BYTE*)bytes, (const BYTE*)bytes + size);
		std::lock_guard<std::mutex> guard(m_lock);
		if (m_entries.size() >= ICC_TWIN_ENTRIES) {
			m_entries.erase(m_entries.begin());
		}
		m_entries.push_back(entry);
		return entry.twin;
	}

private:
	struct Entry {
		std::vector<BYTE> bytes;
		bool twin;
	};

	std::mutex m_lock;
	std::vector<Entry> m_entries;

	static bool Check(const void *bytes, DWORD size) {
		Context context;
		context.mute = true;
		cmsHPROFILE profile = context.Open(bytes, size);
		const Model model = profile ? ModelOf(profile) : MODEL_NONE;
		bool twin = false;
		if ((model == MODEL_RGB) || (model == MODEL_GRAY)) {
			DWORD builtin_size = 0;
			const void *builtin_data = FreeImage_GetBuiltInICCProfile((model == MODEL_GRAY) ? FICMS_PROFILE_GRAY : FICMS_PROFILE_SRGB, &builtin_size);
			cmsHPROFILE builtin = context.Open(builtin_data, builtin_size);
			twin = builtin && Equivalent(context, builtin, profile, (model == MODEL_GRAY));
			if (builtin) {
				cmsCloseProfile(builtin);
			}
		}
		if (profile) {
			cmsCloseProfile(profile);
		}
		return twin;
	}
};

static TwinCache &
GetTwinCache() {
	// never destroyed: a load may still run while the process ends
	static TwinCache *cache = new TwinCache;
	return *cache;
}

// a grey profile whose tone curve is the luminance the display shows for (v, v, v)
static bool
DisplayGrey(const Context &context, cmsHPROFILE display, std::vector<BYTE> &grey) {
	const unsigned N = 4096;
	cmsHPROFILE xyz = cmsCreateXYZProfileTHR(context.id);
	cmsHTRANSFORM transform = xyz ? cmsCreateTransformTHR(context.id, display, TYPE_RGB_16, xyz, TYPE_XYZ_DBL, INTENT_RELATIVE_COLORIMETRIC, cmsFLAGS_NOOPTIMIZE) : NULL;
	if (xyz) {
		cmsCloseProfile(xyz);
	}
	if (!transform) {
		return false;
	}
	std::vector<WORD> rgb(N * 3);
	std::vector<cmsCIEXYZ> out(N);
	for (unsigned i = 0; i < N; i++) {
		rgb[3 * i] = rgb[3 * i + 1] = rgb[3 * i + 2] = (WORD)((i * 65535 + (N - 1) / 2) / (N - 1));
	}
	cmsDoTransform(transform, &rgb[0], &out[0], N);
	cmsDeleteTransform(transform);
	const double white = out[N - 1].Y;
	if (!(white > 0)) {
		return false;
	}
	// a tone curve has to rise
	std::vector<WORD> curve(N);
	double previous = 0;
	for (unsigned i = 0; i < N; i++) {
		double y = out[i].Y / white;
		y = (y < previous) ? previous : (y > 1) ? 1 : y;
		previous = y;
		curve[i] = (WORD)(y * 65535 + 0.5);
	}
	cmsToneCurve *tone = cmsBuildTabulatedToneCurve16(context.id, N, &curve[0]);
	cmsHPROFILE profile = tone ? cmsCreateGrayProfileTHR(context.id, cmsD50_xyY(), tone) : NULL;
	if (tone) {
		cmsFreeToneCurve(tone);
	}
	bool done = profile && SetDescription(profile, "Display grey (FreeImage)");
	if (done) {
		DWORD size = 0;
		BYTE *data = SaveBuiltInProfile(profile, &size);
		done = (data != NULL);
		if (data) {
			grey.assign(data, data + size);
			free(data);
		}
	}
	if (profile) {
		cmsCloseProfile(profile);
	}
	return done;
}

// what loads convert to for this display profile; sRGB for none, a profile Little CMS cannot convert to, or an sRGB twin
static std::shared_ptr<DisplayState>
BuildDisplayState(const std::vector<BYTE> &bytes, int flags, bool *usable) {
	std::shared_ptr<DisplayState> state = std::make_shared<DisplayState>();
	state->flags = flags;
	bool linked = false;
	if (bytes.size() >= 128) {
		Context context;
		context.mute = true;
		DWORD srgb_size = 0;
		const void *srgb_data = FreeImage_GetBuiltInICCProfile(FICMS_PROFILE_SRGB, &srgb_size);
		cmsHPROFILE srgb = context.Open(srgb_data, srgb_size);
		cmsHPROFILE profile = context.Open(&bytes[0], (DWORD)bytes.size());
		if (srgb && profile && (ModelOf(profile) == MODEL_RGB)) {
			const cmsUInt32Number bpc = (flags & FICMS_BLACKPOINT_COMPENSATION) ? cmsFLAGS_BLACKPOINTCOMPENSATION : 0;
			cmsHTRANSFORM transform = cmsCreateTransformTHR(context.id, srgb, TYPE_RGB_8, profile, TYPE_RGB_8, (cmsUInt32Number)(flags & 0xFF), bpc);
			if (transform) {
				cmsDeleteTransform(transform);
				linked = true;
				if (!Equivalent(context, srgb, profile, false)) {
					state->rgb = bytes;
					state->srgb = false;
					if (!DisplayGrey(context, profile, state->grey)) {
						BuiltInBytes(FICMS_PROFILE_GRAY, state->grey);
					}
				}
			}
		}
		if (profile) {
			cmsCloseProfile(profile);
		}
		if (srgb) {
			cmsCloseProfile(srgb);
		}
	}
	if (state->srgb) {
		BuiltInBytes(FICMS_PROFILE_SRGB, state->rgb);
		BuiltInBytes(FICMS_PROFILE_GRAY, state->grey);
	}
	if (usable) {
		*usable = linked;
	}
	return state;
}

// the state the loads share, built again when the system reports another profile
class DisplayCache {
public:
	DisplayCache() : m_flags(FICMS_INTENT_RELATIVE_COLORIMETRIC | FICMS_BLACKPOINT_COMPENSATION), m_pinned(false) {
	}

	// the system is asked at most once a second; FreeImage_OutputMessageProc never runs under the lock
	std::shared_ptr<const DisplayState> Current() {
		std::lock_guard<std::mutex> guard(m_lock);
		const std::chrono::steady_clock::time_point now = std::chrono::steady_clock::now();
		if (m_state && (m_pinned || (now - m_checked < std::chrono::seconds(1)))) {
			return m_state;
		}
		DisplayQuery query;
		QuerySystem(query);
		m_checked = now;
		if (!m_state || (query.key != m_key)) {
			ReadSystem(query);
			m_state = BuildDisplayState(query.bytes, m_flags, NULL);
			m_key.swap(query.key);
		}
		return m_state;
	}

	// NULL goes back to the system's profile
	bool Pin(const void *profile, DWORD size, int flags) {
		std::shared_ptr<const DisplayState> state;
		if (profile) {
			if ((size < 128) || (size > ICC_DISPLAY_MAX_SIZE)) {
				return false;
			}
			std::vector<BYTE> bytes;
			Append(bytes, profile, size);
			bool usable = false;
			state = BuildDisplayState(bytes, flags, &usable);
			if (!usable) {
				return false;
			}
		}
		std::lock_guard<std::mutex> guard(m_lock);
		m_state = state;
		m_key.clear();
		m_flags = flags;
		m_pinned = (profile != NULL);
		return true;
	}

private:
	std::mutex m_lock;
	std::shared_ptr<const DisplayState> m_state;
	std::vector<BYTE> m_key;
	std::chrono::steady_clock::time_point m_checked;
	int m_flags;
	bool m_pinned;
};

static DisplayCache &
GetDisplayCache() {
	// never destroyed: a load may still run while the process ends
	static DisplayCache *cache = new DisplayCache;
	return *cache;
}

// ----------------------------------------------------------
//   Loading for the display
// ----------------------------------------------------------

// dib in the display's colors, in place or as a replacement; false when a needed replacement could not be made
static bool
ToDisplay(const DisplayState &display, FIBITMAP *dib, FIBITMAP **replacement) {
	*replacement = NULL;
	switch (FreeImage_GetImageType(dib)) {
		case FIT_BITMAP:
		case FIT_UINT16:
		case FIT_RGB16:
		case FIT_RGBA16:
			break;
		default:
			// float images hold scene light for the tone mappers; the other types hold no colors
			return true;
	}
	Pixels px;
	if (AnalysePixels(dib, px)) {
		return true;
	}
	const bool grey = (px.model == MODEL_GRAY);
	const std::vector<BYTE> &target = grey ? display.grey : display.rgb;
	// CMYK becomes RGB; 555/565 cannot hold the display's colors
	const bool convert = (px.layout == LAYOUT_CMYK8) || (px.layout == LAYOUT_CMYK16) || (px.layout == LAYOUT_555) || (px.layout == LAYOUT_565);
	if (target.empty()) {
		return !convert;
	}
	// a profile sRGB or grey in all but name converts as FreeImage's: on an sRGB display, not at all
	const FIICCPROFILE *icc = FreeImage_GetICCProfile(dib);
	const bool twin = icc->data && (px.model != MODEL_CMYK) && GetTwinCache().IsTwin(icc->data, (DWORD)icc->size);

	// an embedded profile that cannot be linked is left out the second time
	for (int attempt = 0; attempt < 2; attempt++) {
		ColorConverter converter(display.flags);
		converter.UseCache(&display.transforms);
		if (attempt || twin) {
			converter.IgnoreEmbedded();
		}
		if (converter.SetSource(dib) && converter.SetDestination(&target[0], (DWORD)target.size(), grey ? MODEL_GRAY : MODEL_RGB, MODEL_NONE)) {
			if (convert) {
				*replacement = converter.Convert();
				if (*replacement) {
					return true;
				}
			} else if (converter.Apply()) {
				return true;
			}
		}
		if (!converter.EmbeddedSource()) {
			break;
		}
	}
	// a failed in-place conversion leaves the image as it was loaded
	return !convert;
}

} // namespace

// ==========================================================
//   Public functions
// ==========================================================

FIBITMAP * DLL_CALLCONV
FreeImage_ConvertToICCProfile(FIBITMAP *dib, const void *profile, DWORD size, int flags) {
	ColorConverter converter(flags);
	if (!converter.SetSource(dib) || !converter.SetDestination(profile, size, MODEL_NONE, converter.DefaultModel())) {
		return NULL;
	}
	return converter.Convert();
}

BOOL DLL_CALLCONV
FreeImage_ApplyICCProfile(FIBITMAP *dib, const void *profile, DWORD size, int flags) {
	ColorConverter converter(flags);
	if (!converter.SetSource(dib) || !converter.SetDestination(profile, size, MODEL_NONE, converter.DefaultModel())) {
		return FALSE;
	}
	return converter.Apply();
}

FIBITMAP * DLL_CALLCONV
FreeImage_ConvertToCMYK(FIBITMAP *dib, const void *profile, DWORD size, int flags) {
	ColorConverter converter(flags);
	if (!converter.SetSource(dib)) {
		return NULL;
	}
	if (!profile && (converter.SourceModel() == MODEL_CMYK)) {
		return FreeImage_Clone(dib);
	}
	if (!converter.SetDestination(profile, size, MODEL_CMYK, MODEL_CMYK)) {
		return NULL;
	}
	return converter.Convert();
}

FIBITMAP * DLL_CALLCONV
FreeImage_ConvertCMYKToRGB(FIBITMAP *dib, const void *profile, DWORD size, int flags) {
	ColorConverter converter(flags);
	if (!converter.SetSource(dib)) {
		return NULL;
	}
	if (converter.SourceModel() != MODEL_CMYK) {
		FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: FreeImage_ConvertCMYKToRGB needs a CMYK image");
		return NULL;
	}
	if (!converter.SetDestination(profile, size, MODEL_RGB, MODEL_RGB)) {
		return NULL;
	}
	return converter.Convert();
}

FIBITMAP * DLL_CALLCONV
FreeImage_SoftProof(FIBITMAP *dib, const void *proof_profile, DWORD proof_size, const void *display_profile, DWORD display_size, int flags) {
	ColorConverter converter(flags);
	if (!converter.SetSource(dib) || !converter.SetProof(proof_profile, proof_size) || !converter.SetDestination(display_profile, display_size, MODEL_RGB, MODEL_RGB)) {
		return NULL;
	}
	return converter.Convert();
}

const void * DLL_CALLCONV
FreeImage_GetBuiltInICCProfile(int profile, DWORD *size) {
	if (size) {
		*size = 0;
	}
	if ((profile < 0) || (profile >= ICC_BUILTIN_COUNT)) {
		return NULL;
	}
	const BuiltInProfiles &profiles = GetBuiltInProfiles();
	if (size && profiles.data[profile]) {
		*size = profiles.size[profile];
	}
	return profiles.data[profile];
}

unsigned DLL_CALLCONV
FreeImage_GetICCProfileDescription(const void *profile, DWORD size, char *buffer, unsigned buffer_size) {
	if (buffer && buffer_size) {
		buffer[0] = 0;
	}
	Context context;
	context.mute = true;
	cmsHPROFILE handle = context.Open(profile, size);
	if (!handle) {
		return 0;
	}
	unsigned needed = 0;
	const cmsUInt32Number length = cmsGetProfileInfoUTF8(handle, cmsInfoDescription, "en", "US", NULL, 0);
	char *text = length ? (char*)malloc(length) : NULL;
	if (text && cmsGetProfileInfoUTF8(handle, cmsInfoDescription, "en", "US", text, length)) {
		text[length - 1] = 0;
		needed = (unsigned)strlen(text) + 1;
		if (buffer && buffer_size) {
			// cut on a character boundary
			unsigned n = MIN(needed - 1, buffer_size - 1);
			while ((n > 0) && (n < needed - 1) && (((BYTE)text[n] & 0xC0) == 0x80)) {
				n--;
			}
			memcpy(buffer, text, n);
			buffer[n] = 0;
		}
	}
	free(text);
	cmsCloseProfile(handle);
	return needed;
}

DWORD DLL_CALLCONV
FreeImage_GetICCProfileColorSpace(const void *profile, DWORD size) {
	Context context;
	context.mute = true;
	cmsHPROFILE handle = context.Open(profile, size);
	if (!handle) {
		return 0;
	}
	const DWORD space = (DWORD)cmsGetColorSpace(handle);
	cmsCloseProfile(handle);
	return space;
}

BOOL DLL_CALLCONV
FreeImage_SetDisplayICCProfile(const void *profile, DWORD size, int flags) {
	if (((flags & 0xFF) > FICMS_INTENT_ABSOLUTE_COLORIMETRIC) || (flags & ~(0xFF | FICMS_BLACKPOINT_COMPENSATION))) {
		FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: FreeImage_SetDisplayICCProfile takes a rendering intent and FICMS_BLACKPOINT_COMPENSATION");
		return FALSE;
	}
	try {
		if (!GetDisplayCache().Pin(profile, size, flags)) {
			FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: the display profile is not an RGB profile Little CMS can convert to");
			return FALSE;
		}
		return TRUE;
	} catch (std::bad_alloc &) {
		FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: %s", FI_MSG_ERROR_MEMORY);
		return FALSE;
	}
}

DWORD DLL_CALLCONV
FreeImage_GetDisplayICCProfile(void *buffer, DWORD size) {
	try {
		const std::shared_ptr<const DisplayState> display = GetDisplayCache().Current();
		const DWORD needed = (DWORD)display->rgb.size();
		if (buffer && needed && (size >= needed)) {
			memcpy(buffer, &display->rgb[0], needed);
		}
		return needed;
	} catch (std::bad_alloc &) {
		return 0;
	}
}

// ==========================================================
//   FIF_LOAD_DISPLAY_ICC
// ==========================================================

int
DisplayICCLoadFlags(FREE_IMAGE_FORMAT fif, int flags) {
	if ((flags & FIF_LOAD_DISPLAY_ICC) != FIF_LOAD_DISPLAY_ICC) {
		return flags;
	}
	flags &= ~FIF_LOAD_DISPLAY_ICC;
	if ((flags & FIF_LOAD_NOPIXELS) == FIF_LOAD_NOPIXELS) {
		return flags;
	}
	// CMYK stays CMYK, converted with its profile; Lab is converted by the loader
	switch (fif) {
		case FIF_JPEG:
			return flags | JPEG_CMYK;
		case FIF_TIFF:
			return flags | TIFF_CMYK;
		case FIF_PSD:
			return (flags | PSD_CMYK) & ~PSD_LAB;
		default:
			return flags;
	}
}

FIBITMAP *
ConvertToDisplayICC(FREE_IMAGE_FORMAT fif, int flags, FIBITMAP *dib) {
	if (!dib || ((flags & (FIF_LOAD_DISPLAY_ICC | FIF_LOAD_NOPIXELS)) != FIF_LOAD_DISPLAY_ICC) || !FreeImage_HasPixels(dib)) {
		return dib;
	}
	// raw sensor data holds no colors yet
	if ((fif == FIF_RAW) && ((flags & RAW_UNPROCESSED) == RAW_UNPROCESSED)) {
		return dib;
	}
	try {
		const std::shared_ptr<const DisplayState> display = GetDisplayCache().Current();
		FIBITMAP *replacement = NULL;
		if (!ToDisplay(*display, dib, &replacement)) {
			FreeImage_Unload(dib);
			return NULL;
		}
		if (replacement) {
			// conversions leave the thumbnail behind
			FreeImage_SetThumbnail(replacement, FreeImage_GetThumbnail(dib));
			FreeImage_Unload(dib);
			dib = replacement;
		}
		FIBITMAP *thumbnail = FreeImage_GetThumbnail(dib);
		if (thumbnail) {
			FIBITMAP *converted = NULL;
			if (!ToDisplay(*display, thumbnail, &converted)) {
				FreeImage_SetThumbnail(dib, NULL);
			} else if (converted) {
				FreeImage_SetThumbnail(dib, converted);
				FreeImage_Unload(converted);
			}
		}
		return dib;
	} catch (std::bad_alloc &) {
		FreeImage_OutputMessageProc(fif, FI_MSG_ERROR_MEMORY);
		FreeImage_Unload(dib);
		return NULL;
	}
}
