// ==========================================================
// Color management: ICC profile conversions with Little CMS
//
// This file is part of FreeImage 3
//
// COVERED CODE IS PROVIDED UNDER THIS LICENSE ON AN "AS IS" BASIS, WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, WITHOUT LIMITATION, WARRANTIES
// THAT THE COVERED CODE IS FREE OF DEFECTS, MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE
// OR NON-INFRINGING. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE COVERED
// CODE IS WITH YOU. SHOULD ANY COVERED CODE PROVE DEFECTIVE IN ANY RESPECT, YOU (NOT
// THE INITIAL DEVELOPER OR ANY OTHER CONTRIBUTOR) ASSUME THE COST OF ANY NECESSARY
// SERVICING, REPAIR OR CORRECTION. THIS DISCLAIMER OF WARRANTY CONSTITUTES AN ESSENTIAL
// PART OF THIS LICENSE. NO USE OF ANY COVERED CODE IS AUTHORIZED HEREUNDER EXCEPT UNDER
// THIS DISCLAIMER.
//
// Use at your own risk!
//
// Code generated by Marius Șucan with Anthropic Claude
// ==========================================================

#include "FreeImage.h"
#include "Utilities.h"

#define CMS_NO_REGISTER_KEYWORD 1
#include "../LibLCMS2/include/lcms2.h"

// images smaller than this are converted on one thread
#define ICC_PARALLEL_PIXELS 16384

// the number of FICMS_PROFILE_* profiles
#define ICC_BUILTIN_COUNT 7

// FreeImage's 24- and 32-bit pixels and palette entries
#if FREEIMAGE_COLORORDER == FREEIMAGE_COLORORDER_BGR
#define ICC_TYPE_RGB_8	TYPE_BGR_8
#define ICC_TYPE_RGBA_8	TYPE_BGRA_8
#else
#define ICC_TYPE_RGB_8	TYPE_RGB_8
#define ICC_TYPE_RGBA_8	TYPE_RGBA_8
#endif

namespace {

enum Model {
	MODEL_NONE = 0,
	MODEL_GRAY,
	MODEL_RGB,
	MODEL_CMYK
};

enum Layout {
	LAYOUT_NONE = 0,
	LAYOUT_INDEXED,		// 1-, 4- or 8-bit palette
	LAYOUT_GRAY8,		// 8-bit linear grey ramp without transparency
	LAYOUT_555,
	LAYOUT_565,
	LAYOUT_RGB8,
	LAYOUT_RGBA8,
	LAYOUT_CMYK8,
	LAYOUT_GRAY16,
	LAYOUT_RGB16,
	LAYOUT_RGBA16,
	LAYOUT_CMYK16,
	LAYOUT_GRAYF,
	LAYOUT_RGBF,
	LAYOUT_RGBAF
};

struct Pixels {
	Layout layout;
	Model model;
	unsigned depth;		// 8, 16 or 32 (float) bits per sample
	bool alpha;			// an alpha channel or a transparency table
	bool reversed;		// FIC_MINISWHITE
	unsigned colors;	// palette entries
};

// ----------------------------------------------------------
//   Pixel layouts
// ----------------------------------------------------------

static bool
IsGreyPalette(const RGBQUAD *palette, unsigned count) {
	for (unsigned i = 0; i < count; i++) {
		if ((palette[i].rgbRed != palette[i].rgbGreen) || (palette[i].rgbRed != palette[i].rgbBlue)) {
			return false;
		}
	}
	return true;
}

// NULL, or why the image cannot be color managed
static const char *
AnalysePixels(FIBITMAP *dib, Pixels &px) {
	memset(&px, 0, sizeof(px));

	const bool cmyk = (FreeImage_GetICCProfile(dib)->flags & FIICC_COLOR_IS_CMYK) != 0;
	const unsigned bpp = FreeImage_GetBPP(dib);

	switch (FreeImage_GetImageType(dib)) {
		case FIT_BITMAP:
			px.depth = 8;
			switch (bpp) {
				case 1:
				case 4:
				case 8:
				{
					const RGBQUAD *palette = FreeImage_GetPalette(dib);
					px.colors = FreeImage_GetColorsUsed(dib);
					if (!palette || !px.colors) {
						return "the image has no palette";
					}
					px.layout = LAYOUT_INDEXED;
					px.model = IsGreyPalette(palette, px.colors) ? MODEL_GRAY : MODEL_RGB;
					px.alpha = FreeImage_IsTransparent(dib) && (FreeImage_GetTransparencyCount(dib) > 0);
					if ((bpp == 8) && (px.colors == 256) && !px.alpha) {
						const FREE_IMAGE_COLOR_TYPE color_type = FreeImage_GetColorType(dib);
						if ((color_type == FIC_MINISBLACK) || (color_type == FIC_MINISWHITE)) {
							px.layout = LAYOUT_GRAY8;
							px.reversed = (color_type == FIC_MINISWHITE);
						}
					}
					return NULL;
				}
				case 16:
					px.layout = IS_FORMAT_RGB565(dib) ? LAYOUT_565 : LAYOUT_555;
					px.model = MODEL_RGB;
					return NULL;
				case 24:
					px.layout = LAYOUT_RGB8;
					px.model = MODEL_RGB;
					return NULL;
				case 32:
					px.layout = cmyk ? LAYOUT_CMYK8 : LAYOUT_RGBA8;
					px.model = cmyk ? MODEL_CMYK : MODEL_RGB;
					px.alpha = !cmyk;
					return NULL;
			}
			break;
		case FIT_UINT16:
			px.layout = LAYOUT_GRAY16;
			px.model = MODEL_GRAY;
			px.depth = 16;
			px.reversed = (FreeImage_GetColorType(dib) == FIC_MINISWHITE);
			return NULL;
		case FIT_RGB16:
			px.layout = LAYOUT_RGB16;
			px.model = MODEL_RGB;
			px.depth = 16;
			return NULL;
		case FIT_RGBA16:
			px.layout = cmyk ? LAYOUT_CMYK16 : LAYOUT_RGBA16;
			px.model = cmyk ? MODEL_CMYK : MODEL_RGB;
			px.depth = 16;
			px.alpha = !cmyk;
			return NULL;
		case FIT_FLOAT:
			px.layout = LAYOUT_GRAYF;
			px.model = MODEL_GRAY;
			px.depth = 32;
			return NULL;
		case FIT_RGBF:
			px.layout = LAYOUT_RGBF;
			px.model = MODEL_RGB;
			px.depth = 32;
			return NULL;
		case FIT_RGBAF:
			if (cmyk) {
				return "floating-point CMYK images are not supported";
			}
			px.layout = LAYOUT_RGBAF;
			px.model = MODEL_RGB;
			px.depth = 32;
			px.alpha = true;
			return NULL;
		default:
			break;
	}
	return "unsupported image type";
}

static cmsUInt32Number
LayoutFormat(Layout layout, bool reversed) {
	switch (layout) {
		case LAYOUT_GRAY8:	return reversed ? TYPE_GRAY_8_REV : TYPE_GRAY_8;
		case LAYOUT_RGB8:	return ICC_TYPE_RGB_8;
		case LAYOUT_RGBA8:	return ICC_TYPE_RGBA_8;
		case LAYOUT_CMYK8:	return TYPE_CMYK_8;
		case LAYOUT_GRAY16:	return reversed ? TYPE_GRAY_16_REV : TYPE_GRAY_16;
		case LAYOUT_RGB16:	return TYPE_RGB_16;
		case LAYOUT_RGBA16:	return TYPE_RGBA_16;
		case LAYOUT_CMYK16:	return TYPE_CMYK_16;
		case LAYOUT_GRAYF:	return TYPE_GRAY_FLT;
		case LAYOUT_RGBF:	return TYPE_RGB_FLT;
		case LAYOUT_RGBAF:	return TYPE_RGBA_FLT;
		default:			return 0;
	}
}

static unsigned
PixelBytes(cmsUInt32Number format) {
	const unsigned bytes = T_BYTES(format) ? T_BYTES(format) : 8;
	return bytes * (T_CHANNELS(format) + T_EXTRA(format));
}

// the pixel format of a new image in the destination model: same precision, alpha kept when it can be
static Layout
OutputLayout(const Pixels &px, Model model) {
	switch (model) {
		case MODEL_RGB:
			if (px.depth == 8) return px.alpha ? LAYOUT_RGBA8 : LAYOUT_RGB8;
			if (px.depth == 16) return px.alpha ? LAYOUT_RGBA16 : LAYOUT_RGB16;
			return px.alpha ? LAYOUT_RGBAF : LAYOUT_RGBF;
		case MODEL_GRAY:
			// a transparent palette keeps its transparency table
			if (px.depth == 8) return ((px.layout == LAYOUT_INDEXED) && px.alpha) ? LAYOUT_INDEXED : LAYOUT_GRAY8;
			if (px.depth == 16) return LAYOUT_GRAY16;
			return LAYOUT_GRAYF;
		case MODEL_CMYK:
			return (px.depth == 8) ? LAYOUT_CMYK8 : LAYOUT_CMYK16;
		default:
			return LAYOUT_NONE;
	}
}

// the pixel format an in-place conversion leaves, or LAYOUT_NONE
static Layout
InPlaceLayout(const Pixels &px, Model model) {
	switch (px.layout) {
		case LAYOUT_INDEXED:
			return (model == MODEL_CMYK) ? LAYOUT_NONE : LAYOUT_INDEXED;
		case LAYOUT_GRAY8:
			if (model == MODEL_GRAY) return LAYOUT_GRAY8;
			return (model == MODEL_RGB) ? LAYOUT_INDEXED : LAYOUT_NONE;
		case LAYOUT_RGB8:
		case LAYOUT_RGBA8:
		case LAYOUT_RGB16:
		case LAYOUT_RGBA16:
		case LAYOUT_RGBF:
		case LAYOUT_RGBAF:
			return (model == MODEL_RGB) ? px.layout : LAYOUT_NONE;
		case LAYOUT_GRAY16:
		case LAYOUT_GRAYF:
			return (model == MODEL_GRAY) ? px.layout : LAYOUT_NONE;
		case LAYOUT_CMYK8:
			if (model == MODEL_CMYK) return LAYOUT_CMYK8;
			return (model == MODEL_RGB) ? LAYOUT_RGBA8 : LAYOUT_NONE;
		case LAYOUT_CMYK16:
			if (model == MODEL_CMYK) return LAYOUT_CMYK16;
			return (model == MODEL_RGB) ? LAYOUT_RGBA16 : LAYOUT_NONE;
		default:
			return LAYOUT_NONE;
	}
}

static FIBITMAP *
AllocateLayout(Layout layout, int width, int height) {
	switch (layout) {
		case LAYOUT_GRAY8:
		{
			FIBITMAP *dib = FreeImage_Allocate(width, height, 8);
			if (dib) {
				RGBQUAD *palette = FreeImage_GetPalette(dib);
				CREATE_GREYSCALE_PALETTE(palette, 256);
			}
			return dib;
		}
		case LAYOUT_RGB8:
			return FreeImage_Allocate(width, height, 24, FI_RGBA_RED_MASK, FI_RGBA_GREEN_MASK, FI_RGBA_BLUE_MASK);
		case LAYOUT_RGBA8:
		case LAYOUT_CMYK8:
			return FreeImage_Allocate(width, height, 32, FI_RGBA_RED_MASK, FI_RGBA_GREEN_MASK, FI_RGBA_BLUE_MASK);
		case LAYOUT_GRAY16:
			return FreeImage_AllocateT(FIT_UINT16, width, height);
		case LAYOUT_RGB16:
			return FreeImage_AllocateT(FIT_RGB16, width, height);
		case LAYOUT_RGBA16:
		case LAYOUT_CMYK16:
			return FreeImage_AllocateT(FIT_RGBA16, width, height);
		case LAYOUT_GRAYF:
			return FreeImage_AllocateT(FIT_FLOAT, width, height);
		case LAYOUT_RGBF:
			return FreeImage_AllocateT(FIT_RGBF, width, height);
		case LAYOUT_RGBAF:
			return FreeImage_AllocateT(FIT_RGBAF, width, height);
		default:
			return NULL;
	}
}

// ----------------------------------------------------------
//   Device CMYK: the conversions FreeImage's loaders use
// ----------------------------------------------------------

// as ConvertCMYKtoRGBA(): R = (1 - C)(1 - K), 8-bit output in FreeImage's color order
static void
DeviceCMYKToRGB8(const BYTE *src, BYTE *dst, unsigned width) {
	for (unsigned x = 0; x < width; x++) {
		const unsigned K = 255 - src[3];
		dst[FI_RGBA_RED]	= (BYTE)(((255 - src[0]) * K) / 255);
		dst[FI_RGBA_GREEN]	= (BYTE)(((255 - src[1]) * K) / 255);
		dst[FI_RGBA_BLUE]	= (BYTE)(((255 - src[2]) * K) / 255);
		src += 4;
		dst += 3;
	}
}

static void
DeviceCMYKToRGB16(const WORD *src, WORD *dst, unsigned width) {
	for (unsigned x = 0; x < width; x++) {
		const unsigned K = 65535 - src[3];
		dst[0] = (WORD)(((65535 - src[0]) * K) / 65535);
		dst[1] = (WORD)(((65535 - src[1]) * K) / 65535);
		dst[2] = (WORD)(((65535 - src[2]) * K) / 65535);
		src += 4;
		dst += 3;
	}
}

// full black generation; the exact inverse of DeviceCMYKToRGB*
template <class T> static void
RGBToDeviceCMYK(const T *src, unsigned step, bool grey, unsigned r, unsigned g, unsigned b, T *dst, unsigned width) {
	const unsigned MAX_VAL = (sizeof(T) == 1) ? 255 : 65535;
	for (unsigned x = 0; x < width; x++) {
		if (grey) {
			dst[0] = dst[1] = dst[2] = 0;
			dst[3] = (T)(MAX_VAL - src[0]);
		} else {
			const unsigned R = src[r], G = src[g], B = src[b];
			const unsigned M = MAX(R, MAX(G, B));
			if (M == 0) {
				dst[0] = dst[1] = dst[2] = 0;
				dst[3] = (T)MAX_VAL;
			} else {
				dst[0] = (T)(MAX_VAL - (MAX_VAL * R + M - 1) / M);
				dst[1] = (T)(MAX_VAL - (MAX_VAL * G + M - 1) / M);
				dst[2] = (T)(MAX_VAL - (MAX_VAL * B + M - 1) / M);
				dst[3] = (T)(MAX_VAL - M);
			}
		}
		src += step;
		dst += 4;
	}
}

static void
PackOpaque8(const BYTE *rgb, BYTE *rgba, unsigned width) {
	for (unsigned x = 0; x < width; x++) {
		rgba[0] = rgb[0];
		rgba[1] = rgb[1];
		rgba[2] = rgb[2];
		rgba[3] = 0xFF;
		rgb += 3;
		rgba += 4;
	}
}

static void
PackOpaque16(const WORD *rgb, WORD *rgba, unsigned width) {
	for (unsigned x = 0; x < width; x++) {
		rgba[0] = rgb[0];
		rgba[1] = rgb[1];
		rgba[2] = rgb[2];
		rgba[3] = 0xFFFF;
		rgb += 3;
		rgba += 4;
	}
}

// ----------------------------------------------------------
//   Built-in profiles
// ----------------------------------------------------------

static bool
SetDescription(cmsHPROFILE profile, const char *text) {
	cmsMLU *mlu = cmsMLUalloc(cmsGetProfileContextID(profile), 1);
	const bool done = mlu && cmsMLUsetASCII(mlu, "en", "US", text) && cmsWriteTag(profile, cmsSigProfileDescriptionTag, mlu);
	if (mlu) {
		cmsMLUfree(mlu);
	}
	return done;
}

static cmsHPROFILE
CreateBuiltInProfile(cmsContext context, int which) {
	static const cmsCIExyY D65 = { 0.3127, 0.3290, 1.0 };
	static const cmsCIExyY D50 = { 0.3457, 0.3585, 1.0 };
	static const cmsCIExyYTRIPLE SRGB = { { 0.6400, 0.3300, 1.0 }, { 0.3000, 0.6000, 1.0 }, { 0.1500, 0.0600, 1.0 } };
	static const cmsCIExyYTRIPLE ADOBE = { { 0.6400, 0.3300, 1.0 }, { 0.2100, 0.7100, 1.0 }, { 0.1500, 0.0600, 1.0 } };
	static const cmsCIExyYTRIPLE P3 = { { 0.6800, 0.3200, 1.0 }, { 0.2650, 0.6900, 1.0 }, { 0.1500, 0.0600, 1.0 } };
	static const cmsCIExyYTRIPLE ROMM = { { 0.7347, 0.2653, 1.0 }, { 0.1596, 0.8404, 1.0 }, { 0.0366, 0.0001, 1.0 } };
	static const cmsFloat64Number SRGB_CURVE[5] = { 2.4, 1.0 / 1.055, 0.055 / 1.055, 1.0 / 12.92, 0.04045 };

	const cmsCIExyY *white = &D65;
	const cmsCIExyYTRIPLE *primaries = &SRGB;
	cmsToneCurve *curve = NULL;
	const char *name = NULL;

	switch (which) {
		case FICMS_PROFILE_SRGB:
			curve = cmsBuildParametricToneCurve(context, 4, SRGB_CURVE);
			name = "sRGB (FreeImage)";
			break;
		case FICMS_PROFILE_LINEAR_SRGB:
			curve = cmsBuildGamma(context, 1.0);
			name = "Linear sRGB (FreeImage)";
			break;
		case FICMS_PROFILE_GRAY:
			curve = cmsBuildParametricToneCurve(context, 4, SRGB_CURVE);
			name = "Gray, sRGB tone curve (FreeImage)";
			break;
		case FICMS_PROFILE_LINEAR_GRAY:
			curve = cmsBuildGamma(context, 1.0);
			name = "Linear gray (FreeImage)";
			break;
		case FICMS_PROFILE_ADOBE_RGB:
			curve = cmsBuildGamma(context, 563.0 / 256.0);
			primaries = &ADOBE;
			name = "Adobe RGB (1998) compatible (FreeImage)";
			break;
		case FICMS_PROFILE_DISPLAY_P3:
			curve = cmsBuildParametricToneCurve(context, 4, SRGB_CURVE);
			primaries = &P3;
			name = "Display P3 (FreeImage)";
			break;
		case FICMS_PROFILE_PROPHOTO_RGB:
			curve = cmsBuildGamma(context, 1.8);
			white = &D50;
			primaries = &ROMM;
			name = "ProPhoto RGB (FreeImage)";
			break;
		default:
			return NULL;
	}
	if (!curve) {
		return NULL;
	}

	cmsHPROFILE profile = NULL;
	if ((which == FICMS_PROFILE_GRAY) || (which == FICMS_PROFILE_LINEAR_GRAY)) {
		profile = cmsCreateGrayProfileTHR(context, cmsD50_xyY(), curve);
	} else {
		cmsToneCurve *curves[3] = { curve, curve, curve };
		profile = cmsCreateRGBProfileTHR(context, white, primaries, curves);
	}
	cmsFreeToneCurve(curve);

	if (profile && !SetDescription(profile, name)) {
		cmsCloseProfile(profile);
		profile = NULL;
	}
	return profile;
}

static BYTE *
SaveBuiltInProfile(cmsHPROFILE profile, DWORD *size) {
	cmsUInt32Number length = 0;
	if (!cmsSaveProfileToMem(profile, NULL, &length) || (length < 128)) {
		return NULL;
	}
	BYTE *data = (BYTE*)malloc(length);
	if (data && cmsSaveProfileToMem(profile, data, &length)) {
		// a fixed creation date and no primary platform: the same bytes on every run and system
		static const BYTE DATE[12] = { 0x07, 0xEA, 0x00, 0x01, 0x00, 0x01, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00 };
		memcpy(data + 24, DATE, sizeof(DATE));
		memset(data + 40, 0, 4);
		*size = length;
		return data;
	}
	free(data);
	return NULL;
}

// created once, kept until the process ends
struct BuiltInProfiles {
	BYTE *data[ICC_BUILTIN_COUNT];
	DWORD size[ICC_BUILTIN_COUNT];

	BuiltInProfiles() {
		cmsContext context = cmsCreateContext(NULL, NULL);
		for (int i = 0; i < ICC_BUILTIN_COUNT; i++) {
			data[i] = NULL;
			size[i] = 0;
			cmsHPROFILE profile = context ? CreateBuiltInProfile(context, i) : NULL;
			if (profile) {
				data[i] = SaveBuiltInProfile(profile, &size[i]);
				cmsCloseProfile(profile);
			}
		}
		if (context) {
			cmsDeleteContext(context);
		}
	}
};

static const BuiltInProfiles &
GetBuiltInProfiles() {
	static const BuiltInProfiles profiles;
	return profiles;
}

// the profile FreeImage assumes for images of this model and depth without one
static int
DefaultProfile(Model model, unsigned depth) {
	if (model == MODEL_GRAY) {
		return (depth == 32) ? FICMS_PROFILE_LINEAR_GRAY : FICMS_PROFILE_GRAY;
	}
	return (depth == 32) ? FICMS_PROFILE_LINEAR_SRGB : FICMS_PROFILE_SRGB;
}

// ----------------------------------------------------------
//   Profiles and the Little CMS context
// ----------------------------------------------------------

static Model
ModelOf(cmsHPROFILE profile) {
	switch (cmsGetDeviceClass(profile)) {
		case cmsSigInputClass:
		case cmsSigDisplayClass:
		case cmsSigOutputClass:
		case cmsSigColorSpaceClass:
			break;
		default:
			return MODEL_NONE;
	}
	switch (cmsGetColorSpace(profile)) {
		case cmsSigGrayData:	return MODEL_GRAY;
		case cmsSigRgbData:		return MODEL_RGB;
		case cmsSigCmykData:	return MODEL_CMYK;
		default:				return MODEL_NONE;
	}
}

// Little CMS errors go to FreeImage_OutputMessageProc unless muted
class Context {
public:
	cmsContext id;
	bool mute;

	Context() : id(NULL), mute(false) {
		id = cmsCreateContext(NULL, this);
		if (id) {
			cmsSetLogErrorHandlerTHR(id, Log);
		}
	}
	~Context() {
		if (id) {
			cmsDeleteContext(id);
		}
	}
	cmsHPROFILE Open(const void *data, DWORD size) {
		if (!id || !data || (size < 128)) {
			return NULL;
		}
		return cmsOpenProfileFromMemTHR(id, data, size);
	}

private:
	static void Log(cmsContext id, cmsUInt32Number, const char *text) {
		const Context *self = (const Context *)cmsGetContextUserData(id);
		if (self && !self->mute && text) {
			FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: Little CMS: %s", text);
		}
	}
	Context(const Context &);
	Context &operator=(const Context &);
};

struct Profile {
	cmsHPROFILE handle;		// NULL for device CMYK
	Model model;
	const void *bytes;		// the profile, to recognise two equal ones
	DWORD size;
	bool tag;				// the result carries this profile

	Profile() : handle(NULL), model(MODEL_NONE), bytes(NULL), size(0), tag(false) {
	}
	~Profile() {
		if (handle) {
			cmsCloseProfile(handle);
		}
	}
	bool Same(const Profile &other) const {
		return bytes && other.bytes && (size == other.size) && ((bytes == other.bytes) || (memcmp(bytes, other.bytes, size) == 0));
	}

private:
	Profile(const Profile &);
	Profile &operator=(const Profile &);
};

// the image's profile, even when the caller passes the image's own profile
static void
AttachProfile(FIBITMAP *dib, const void *data, DWORD size) {
	FIICCPROFILE *icc = FreeImage_GetICCProfile(dib);
	const BYTE *current = (const BYTE*)icc->data;
	const BYTE *bytes = (const BYTE*)data;
	if (current && (bytes >= current) && (bytes < current + icc->size)) {
		if ((bytes == current) && (size == icc->size)) {
			return;
		}
		void *copy = malloc(size);
		if (copy) {
			memcpy(copy, data, size);
			FreeImage_CreateICCProfile(dib, copy, (long)size);
			free(copy);
		} else {
			FreeImage_DestroyICCProfile(dib);
		}
		return;
	}
	FreeImage_CreateICCProfile(dib, (void*)data, (long)size);
}

struct RowBuffers {
	BYTE *a;
	BYTE *b;
	BYTE *c;

	RowBuffers() : a(NULL), b(NULL), c(NULL) {
	}
	~RowBuffers() {
		free(a);
		free(b);
		free(c);
	}
	bool Allocate(size_t size_a, size_t size_b, size_t size_c) {
		a = size_a ? (BYTE*)malloc(size_a) : NULL;
		b = size_b ? (BYTE*)malloc(size_b) : NULL;
		c = size_c ? (BYTE*)malloc(size_c) : NULL;
		return (a || !size_a) && (b || !size_b) && (c || !size_c);
	}

private:
	RowBuffers(const RowBuffers &);
	RowBuffers &operator=(const RowBuffers &);
};

// ----------------------------------------------------------
//   The conversion
// ----------------------------------------------------------

class ColorConverter {
public:
	explicit ColorConverter(int flags) : m_flags(flags), m_dib(NULL), m_width(0), m_height(0),
		m_transform(NULL), m_device_in(false), m_device_out(false), m_step(0), m_grey(false),
		m_in_format(0), m_out_format(0) {
		memset(&m_px, 0, sizeof(m_px));
	}
	~ColorConverter() {
		if (m_transform) {
			cmsDeleteTransform(m_transform);
		}
	}

	bool SetSource(FIBITMAP *dib);
	bool SetDestination(const void *data, DWORD size, Model required, Model if_null);
	bool SetProof(const void *data, DWORD size);
	FIBITMAP *Convert();
	BOOL Apply();

	Model SourceModel() const {
		return m_px.model;
	}
	// FreeImage's default space: grey for grey images, else RGB
	Model DefaultModel() const {
		return (m_px.model == MODEL_GRAY) ? MODEL_GRAY : MODEL_RGB;
	}

private:
	Context m_context;
	int m_flags;
	FIBITMAP *m_dib;
	Pixels m_px;
	int m_width;
	int m_height;
	Profile m_source;
	Profile m_destination;
	Profile m_proof;
	Profile m_device;		// sRGB or grey sRGB, the other side of device CMYK
	cmsHTRANSFORM m_transform;
	bool m_device_in;		// device CMYK source
	bool m_device_out;		// device CMYK destination
	unsigned m_step;		// samples per pixel read by the device CMYK separation
	bool m_grey;			// the separation reads grey
	cmsUInt32Number m_in_format;
	cmsUInt32Number m_out_format;

	bool OpenBuiltIn(Profile &profile, Model model, unsigned depth);
	bool OpenGiven(Profile &profile, const void *data, DWORD size, const char *what);
	bool IsIdentity() const;
	bool CreateTransform(bool same_buffer);
	void Tag(FIBITMAP *dib) const;
	bool Run(FIBITMAP *target, Layout out, bool in_place);
	bool RunTable(FIBITMAP *target, Layout out, bool in_place);
	bool RunRows(FIBITMAP *target, Layout out, bool in_place);
	void Row(const BYTE *src, BYTE *dst, BYTE *buffer_a, BYTE *buffer_b) const;
	void Separate(const BYTE *src, BYTE *dst, unsigned width, unsigned depth) const;

	ColorConverter(const ColorConverter &);
	ColorConverter &operator=(const ColorConverter &);
};

bool ColorConverter::
OpenBuiltIn(Profile &profile, Model model, unsigned depth) {
	DWORD size = 0;
	const void *data = FreeImage_GetBuiltInICCProfile(DefaultProfile(model, depth), &size);
	profile.handle = data ? m_context.Open(data, size) : NULL;
	if (!profile.handle) {
		FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: the built-in profiles are not available");
		return false;
	}
	profile.model = model;
	profile.bytes = data;
	profile.size = size;
	profile.tag = false;
	return true;
}

bool ColorConverter::
OpenGiven(Profile &profile, const void *data, DWORD size, const char *what) {
	if ((size < 128) || (size > 0x7FFFFFFF)) {
		FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: the %s profile has an invalid size", what);
		return false;
	}
	profile.handle = m_context.Open(data, size);
	if (!profile.handle) {
		FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: the %s profile is invalid", what);
		return false;
	}
	profile.model = ModelOf(profile.handle);
	if (profile.model == MODEL_NONE) {
		FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: the %s profile is not a grey, RGB or CMYK device profile", what);
		return false;
	}
	profile.bytes = data;
	profile.size = size;
	profile.tag = true;
	return true;
}

bool ColorConverter::
SetSource(FIBITMAP *dib) {
	if (!m_context.id || !FreeImage_HasPixels(dib)) {
		return false;
	}
	const char *error = AnalysePixels(dib, m_px);
	if (error) {
		FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: %s", error);
		return false;
	}
	m_dib = dib;
	m_width = (int)FreeImage_GetWidth(dib);
	m_height = (int)FreeImage_GetHeight(dib);

	const FIICCPROFILE *icc = FreeImage_GetICCProfile(dib);
	if (icc->data && icc->size) {
		m_context.mute = true;
		cmsHPROFILE handle = m_context.Open(icc->data, icc->size);
		m_context.mute = false;
		if (!handle) {
			FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: the embedded profile is invalid and is ignored");
		} else {
			const Model model = ModelOf(handle);
			const bool indexed = (m_px.layout == LAYOUT_INDEXED) || (m_px.layout == LAYOUT_GRAY8);
			// a grey palette may come with an RGB profile
			if ((model == m_px.model) || (indexed && (m_px.model == MODEL_GRAY) && (model == MODEL_RGB))) {
				m_px.model = model;
				m_source.handle = handle;
				m_source.model = model;
				m_source.bytes = icc->data;
				m_source.size = icc->size;
			} else {
				cmsCloseProfile(handle);
				FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: the embedded profile does not match the pixels and is ignored");
			}
		}
	}
	if (!m_source.handle) {
		if (m_px.model == MODEL_CMYK) {
			m_source.model = MODEL_CMYK;
		} else if (!OpenBuiltIn(m_source, m_px.model, m_px.depth)) {
			return false;
		}
	}
	return true;
}

bool ColorConverter::
SetDestination(const void *data, DWORD size, Model required, Model if_null) {
	if (data) {
		if (!OpenGiven(m_destination, data, size, "destination")) {
			return false;
		}
		if ((required != MODEL_NONE) && (m_destination.model != required)) {
			FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: the destination profile is not a%s profile", (required == MODEL_CMYK) ? " CMYK" : (required == MODEL_RGB) ? "n RGB" : " grey");
			return false;
		}
		return true;
	}
	if (if_null == MODEL_CMYK) {
		m_destination.model = MODEL_CMYK;
		return true;
	}
	return OpenBuiltIn(m_destination, if_null, m_px.depth);
}

bool ColorConverter::
SetProof(const void *data, DWORD size) {
	if (!data) {
		FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: soft proofing needs the profile of the proofing device");
		return false;
	}
	if (!OpenGiven(m_proof, data, size, "proofing")) {
		return false;
	}
	m_proof.tag = false;
	return true;
}

bool ColorConverter::
IsIdentity() const {
	if (m_proof.handle || (m_source.model != m_destination.model)) {
		return false;
	}
	if (!m_source.handle && !m_destination.handle) {
		return true;
	}
	return m_source.Same(m_destination);
}

// the Little CMS stage, none when both sides are the same profile and the samples can be copied
bool ColorConverter::
CreateTransform(bool same_buffer) {
	const Profile &in = m_device_in ? m_device : m_source;
	const Profile &out = m_device_out ? m_device : m_destination;
	if (!m_proof.handle && in.Same(out) && (m_device_out || (m_in_format == m_out_format))) {
		return true;
	}

	cmsUInt32Number flags = 0;
	if (m_flags & FICMS_BLACKPOINT_COMPENSATION) {
		flags |= cmsFLAGS_BLACKPOINTCOMPENSATION;
	}
	if (!same_buffer && T_EXTRA(m_in_format) && T_EXTRA(m_out_format)) {
		flags |= cmsFLAGS_COPY_ALPHA;
	}
	// Little CMS's precalculated 16-bit tables are coarser than its 8-bit path: 16 bits are computed exactly
	if ((T_BYTES(m_in_format) == 2) || (T_BYTES(m_out_format) == 2)) {
		flags |= cmsFLAGS_NOOPTIMIZE;
	}
	const cmsUInt32Number intent = (cmsUInt32Number)(m_flags & 0xFF);

	if (m_proof.handle) {
		flags |= cmsFLAGS_SOFTPROOFING;
		if (m_flags & FICMS_GAMUT_CHECK) {
			flags |= cmsFLAGS_GAMUTCHECK;
		}
		const cmsUInt32Number proof_intent = (m_flags & FICMS_SIMULATE_PAPER) ? INTENT_ABSOLUTE_COLORIMETRIC : INTENT_RELATIVE_COLORIMETRIC;
		m_transform = cmsCreateProofingTransformTHR(m_context.id, in.handle, m_in_format, out.handle, m_out_format, m_proof.handle, intent, proof_intent, flags);
		// without a gamut table Little CMS 2.19 still takes its gamut-check path and crashes
		if (m_transform && (flags & cmsFLAGS_GAMUTCHECK) && !cmsGetTransformGamutCheckPipeline(m_transform)) {
			cmsDeleteTransform(m_transform);
			m_transform = NULL;
			FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: the proofing profile cannot be used for a gamut check");
			return false;
		}
	} else {
		m_transform = cmsCreateTransformTHR(m_context.id, in.handle, m_in_format, out.handle, m_out_format, intent, flags);
	}
	if (!m_transform) {
		FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: the profiles cannot be linked");
		return false;
	}
	return true;
}

// the destination profile, or none for FreeImage's default space
void ColorConverter::
Tag(FIBITMAP *dib) const {
	if (m_destination.tag) {
		AttachProfile(dib, m_destination.bytes, m_destination.size);
	} else {
		FreeImage_DestroyICCProfile(dib);
	}
	FIICCPROFILE *icc = FreeImage_GetICCProfile(dib);
	if (m_destination.model == MODEL_CMYK) {
		icc->flags |= FIICC_COLOR_IS_CMYK;
	} else {
		icc->flags &= ~FIICC_COLOR_IS_CMYK;
	}
}

bool ColorConverter::
Run(FIBITMAP *target, Layout out, bool in_place) {
	m_device_in = (m_source.model == MODEL_CMYK) && !m_source.handle;
	m_device_out = (m_destination.model == MODEL_CMYK) && !m_destination.handle;
	m_grey = m_device_out && (m_source.model == MODEL_GRAY);
	if (m_device_in || m_device_out) {
		if (!OpenBuiltIn(m_device, m_grey ? MODEL_GRAY : MODEL_RGB, (m_px.depth == 8) ? 8 : 16)) {
			return false;
		}
	}
	if ((m_px.layout == LAYOUT_INDEXED) || (m_px.layout == LAYOUT_GRAY8)) {
		return RunTable(target, out, in_place);
	}
	return RunRows(target, out, in_place);
}

// device CMYK from the stage's output, or from the source when there is no stage
void ColorConverter::
Separate(const BYTE *src, BYTE *dst, unsigned width, unsigned depth) const {
	if (depth == 8) {
		RGBToDeviceCMYK<BYTE>(src, m_step, m_grey, FI_RGBA_RED, FI_RGBA_GREEN, FI_RGBA_BLUE, dst, width);
	} else {
		RGBToDeviceCMYK<WORD>((const WORD*)src, m_step, m_grey, 0, 1, 2, (WORD*)dst, width);
	}
}

// palettes and 8-bit grey: the 256 possible values go through a table
bool ColorConverter::
RunTable(FIBITMAP *target, Layout out, bool in_place) {
	const bool alpha = m_px.alpha && (out == LAYOUT_RGBA8);
	const bool grey_in = (m_px.model == MODEL_GRAY);

	if (grey_in) {
		m_in_format = alpha ? TYPE_GRAYA_8 : TYPE_GRAY_8;
	} else {
		m_in_format = alpha ? ICC_TYPE_RGBA_8 : ICC_TYPE_RGB_8;
	}
	if (m_device_out) {
		m_out_format = m_grey ? TYPE_GRAY_8 : ICC_TYPE_RGB_8;
	} else if (out == LAYOUT_INDEXED) {
		m_out_format = (m_destination.model == MODEL_GRAY) ? TYPE_GRAY_8 : ICC_TYPE_RGB_8;
	} else {
		m_out_format = LayoutFormat(out, false);
	}
	if (!CreateTransform(false)) {
		return false;
	}

	// the entries in the stage's input format
	BYTE entries[256 * 4];
	{
		const RGBQUAD *palette = FreeImage_GetPalette(m_dib);
		const BYTE *table = FreeImage_GetTransparencyTable(m_dib);
		const unsigned count = (alpha && table) ? FreeImage_GetTransparencyCount(m_dib) : 0;
		const unsigned bytes = PixelBytes(m_in_format);
		for (unsigned i = 0; i < 256; i++) {
			RGBQUAD color = { 0, 0, 0, 0 };
			if (i < m_px.colors) {
				color = palette[i];
			}
			const BYTE a = (i < count) ? table[i] : 0xFF;
			BYTE *entry = entries + i * bytes;
			if (grey_in) {
				entry[0] = color.rgbRed;
				if (alpha) entry[1] = a;
			} else {
				entry[FI_RGBA_RED] = color.rgbRed;
				entry[FI_RGBA_GREEN] = color.rgbGreen;
				entry[FI_RGBA_BLUE] = color.rgbBlue;
				if (alpha) entry[FI_RGBA_ALPHA] = a;
			}
		}
	}

	// the converted entries in the output format
	const unsigned lut_bytes = m_device_out ? 4 : PixelBytes(m_out_format);
	BYTE lut[256 * 4];
	BYTE middle[256 * 4];
	const BYTE *p = entries;
	if (m_transform) {
		BYTE *t = m_device_out ? middle : lut;
		cmsDoTransform(m_transform, p, t, 256);
		p = t;
	}
	if (m_device_out) {
		m_step = m_transform ? PixelBytes(m_out_format) : PixelBytes(m_in_format);
		Separate(p, lut, 256, 8);
		p = lut;
	}
	if (p != lut) {
		memcpy(lut, p, 256 * lut_bytes);
	}

	if (out == LAYOUT_INDEXED) {
		// the palette changes, the indices stay
		RGBQUAD *palette = FreeImage_GetPalette(target);
		const bool grey_out = (m_destination.model == MODEL_GRAY);
		for (unsigned i = 0; i < m_px.colors; i++) {
			const BYTE *entry = lut + i * lut_bytes;
			if (grey_out) {
				palette[i].rgbRed = palette[i].rgbGreen = palette[i].rgbBlue = entry[0];
			} else {
				palette[i].rgbRed = entry[FI_RGBA_RED];
				palette[i].rgbGreen = entry[FI_RGBA_GREEN];
				palette[i].rgbBlue = entry[FI_RGBA_BLUE];
			}
		}
		return true;
	}

	const bool threaded = (m_height > 1) && ((UINT64)m_width * (UINT64)m_height >= ICC_PARALLEL_PIXELS);
	const unsigned width = (unsigned)m_width;

	if (in_place) {
		// an 8-bit grey ramp keeps its palette: the values change
		BYTE index[256];
		for (unsigned i = 0; i < 256; i++) {
			index[i] = m_px.reversed ? (BYTE)(255 - lut[i]) : lut[i];
		}
		#pragma omp parallel for schedule(static) default(shared) if(threaded)
		for (int y = 0; y < m_height; y++) {
			BYTE *bits = FreeImage_GetScanLine(target, y);
			for (unsigned x = 0; x < width; x++) {
				bits[x] = index[bits[x]];
			}
		}
		return true;
	}

	const unsigned bpp = FreeImage_GetBPP(m_dib);
	#pragma omp parallel for schedule(static) default(shared) if(threaded)
	for (int y = 0; y < m_height; y++) {
		const BYTE *src = FreeImage_GetScanLine(m_dib, y);
		BYTE *dst = FreeImage_GetScanLine(target, y);
		for (unsigned x = 0; x < width; x++) {
			unsigned i;
			if (bpp == 8) {
				i = src[x];
			} else if (bpp == 4) {
				i = (x & 1) ? (src[x >> 1] & 0x0F) : (src[x >> 1] >> 4);
			} else {
				i = (src[x >> 3] >> (7 - (x & 7))) & 1;
			}
			const BYTE *entry = lut + i * lut_bytes;
			for (unsigned k = 0; k < lut_bytes; k++) {
				dst[k] = entry[k];
			}
			dst += lut_bytes;
		}
	}
	return true;
}

// one row: expansion or device CMYK, the Little CMS stage, the device CMYK separation
void ColorConverter::
Row(const BYTE *src, BYTE *dst, BYTE *buffer_a, BYTE *buffer_b) const {
	const unsigned width = (unsigned)m_width;
	const bool copy_out = !m_transform && !m_device_out;
	const BYTE *p = src;

	if ((m_px.layout == LAYOUT_555) || (m_px.layout == LAYOUT_565)) {
		BYTE *t = copy_out ? dst : buffer_a;
		if (m_px.layout == LAYOUT_565) {
			FreeImage_ConvertLine16To24_565(t, (BYTE*)p, (int)width);
		} else {
			FreeImage_ConvertLine16To24_555(t, (BYTE*)p, (int)width);
		}
		p = t;
	} else if (m_device_in) {
		BYTE *t = copy_out ? dst : buffer_a;
		if (m_px.depth == 8) {
			DeviceCMYKToRGB8(p, t, width);
		} else {
			DeviceCMYKToRGB16((const WORD*)p, (WORD*)t, width);
		}
		p = t;
	}
	if (m_transform) {
		BYTE *t = m_device_out ? buffer_b : dst;
		cmsDoTransform(m_transform, p, t, width);
		p = t;
	}
	if (m_device_out) {
		Separate(p, dst, width, (m_px.depth == 8) ? 8 : 16);
		p = dst;
	}
	if (p != dst) {
		memcpy(dst, p, (size_t)width * PixelBytes(m_out_format));
	}
}

// every other layout: row by row
bool ColorConverter::
RunRows(FIBITMAP *target, Layout out, bool in_place) {
	const bool d8 = (m_px.depth == 8);
	// CMYK to RGBA in place: through a row buffer, alpha set opaque
	const bool opaque = in_place && (out != m_px.layout);

	if (m_device_in) {
		m_in_format = d8 ? ICC_TYPE_RGB_8 : TYPE_RGB_16;
	} else if ((m_px.layout == LAYOUT_555) || (m_px.layout == LAYOUT_565)) {
		m_in_format = ICC_TYPE_RGB_8;
	} else {
		m_in_format = LayoutFormat(m_px.layout, m_px.reversed);
	}
	if (m_device_out) {
		if (m_grey) {
			m_out_format = d8 ? TYPE_GRAY_8 : TYPE_GRAY_16;
		} else {
			m_out_format = d8 ? ICC_TYPE_RGB_8 : TYPE_RGB_16;
		}
	} else if (opaque) {
		m_out_format = d8 ? ICC_TYPE_RGB_8 : TYPE_RGB_16;
	} else {
		m_out_format = LayoutFormat(out, (out == m_px.layout) && m_px.reversed);
	}
	const bool same_buffer = in_place && !opaque && !m_device_in;
	if (!CreateTransform(same_buffer)) {
		return false;
	}
	if (m_device_out) {
		m_step = m_transform ? T_CHANNELS(m_out_format) + T_EXTRA(m_out_format) : T_CHANNELS(m_in_format) + T_EXTRA(m_in_format);
	}
	if (in_place && !m_transform && !m_device_in) {
		// nothing changes
		return true;
	}

	const size_t width = (size_t)m_width;
	const bool expand = m_device_in || (m_px.layout == LAYOUT_555) || (m_px.layout == LAYOUT_565);
	const size_t size_a = expand ? width * PixelBytes(m_in_format) : 0;
	const size_t size_b = (m_device_out && m_transform) ? width * PixelBytes(m_out_format) : 0;
	const size_t size_c = opaque ? width * PixelBytes(m_out_format) : 0;

	const bool threaded = (m_height > 1) && ((UINT64)m_width * (UINT64)m_height >= ICC_PARALLEL_PIXELS);
	bool failed = false;

	#pragma omp parallel default(shared) if(threaded)
	{
		RowBuffers buffers;
		if (!buffers.Allocate(size_a, size_b, size_c)) {
			#pragma omp critical
			failed = true;
		}
		// nothing is written unless every thread has its buffers
		#pragma omp barrier
		if (!failed) {
			#pragma omp for schedule(static)
			for (int y = 0; y < m_height; y++) {
				BYTE *dst = FreeImage_GetScanLine(target, y);
				if (opaque) {
					Row(dst, buffers.c, buffers.a, buffers.b);
					if (d8) {
						PackOpaque8(buffers.c, dst, (unsigned)width);
					} else {
						PackOpaque16((const WORD*)buffers.c, (WORD*)dst, (unsigned)width);
					}
				} else {
					Row(in_place ? dst : FreeImage_GetScanLine(m_dib, y), dst, buffers.a, buffers.b);
				}
			}
		}
	}
	if (failed) {
		FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: %s", FI_MSG_ERROR_MEMORY);
		return false;
	}
	return true;
}

FIBITMAP *ColorConverter::
Convert() {
	const Layout out = OutputLayout(m_px, m_destination.model);
	if (out == LAYOUT_NONE) {
		return NULL;
	}
	if (out == m_px.layout) {
		// the same pixel format: a copy converted in place
		FIBITMAP *dst = FreeImage_Clone(m_dib);
		if (!dst) {
			return NULL;
		}
		if (!IsIdentity() && !Run(dst, out, true)) {
			FreeImage_Unload(dst);
			return NULL;
		}
		Tag(dst);
		return dst;
	}
	FIBITMAP *dst = AllocateLayout(out, m_width, m_height);
	if (!dst) {
		FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: %s", FI_MSG_ERROR_DIB_MEMORY);
		return NULL;
	}
	FreeImage_CloneMetadata(dst, m_dib);
	if (!Run(dst, out, false)) {
		FreeImage_Unload(dst);
		return NULL;
	}
	Tag(dst);
	return dst;
}

BOOL ColorConverter::
Apply() {
	if (IsIdentity()) {
		Tag(m_dib);
		return TRUE;
	}
	const Layout out = InPlaceLayout(m_px, m_destination.model);
	if (out == LAYOUT_NONE) {
		FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: this conversion changes the pixel format, use FreeImage_ConvertToICCProfile");
		return FALSE;
	}
	if (!Run(m_dib, out, true)) {
		return FALSE;
	}
	Tag(m_dib);
	return TRUE;
}

} // namespace

// ==========================================================
//   Public functions
// ==========================================================

FIBITMAP * DLL_CALLCONV
FreeImage_ConvertToICCProfile(FIBITMAP *dib, const void *profile, DWORD size, int flags) {
	ColorConverter converter(flags);
	if (!converter.SetSource(dib) || !converter.SetDestination(profile, size, MODEL_NONE, converter.DefaultModel())) {
		return NULL;
	}
	return converter.Convert();
}

BOOL DLL_CALLCONV
FreeImage_ApplyICCProfile(FIBITMAP *dib, const void *profile, DWORD size, int flags) {
	ColorConverter converter(flags);
	if (!converter.SetSource(dib) || !converter.SetDestination(profile, size, MODEL_NONE, converter.DefaultModel())) {
		return FALSE;
	}
	return converter.Apply();
}

FIBITMAP * DLL_CALLCONV
FreeImage_ConvertToCMYK(FIBITMAP *dib, const void *profile, DWORD size, int flags) {
	ColorConverter converter(flags);
	if (!converter.SetSource(dib)) {
		return NULL;
	}
	if (!profile && (converter.SourceModel() == MODEL_CMYK)) {
		return FreeImage_Clone(dib);
	}
	if (!converter.SetDestination(profile, size, MODEL_CMYK, MODEL_CMYK)) {
		return NULL;
	}
	return converter.Convert();
}

FIBITMAP * DLL_CALLCONV
FreeImage_ConvertCMYKToRGB(FIBITMAP *dib, const void *profile, DWORD size, int flags) {
	ColorConverter converter(flags);
	if (!converter.SetSource(dib)) {
		return NULL;
	}
	if (converter.SourceModel() != MODEL_CMYK) {
		FreeImage_OutputMessageProc(FIF_UNKNOWN, "ICC: FreeImage_ConvertCMYKToRGB needs a CMYK image");
		return NULL;
	}
	if (!converter.SetDestination(profile, size, MODEL_RGB, MODEL_RGB)) {
		return NULL;
	}
	return converter.Convert();
}

FIBITMAP * DLL_CALLCONV
FreeImage_SoftProof(FIBITMAP *dib, const void *proof_profile, DWORD proof_size, const void *display_profile, DWORD display_size, int flags) {
	ColorConverter converter(flags);
	if (!converter.SetSource(dib) || !converter.SetProof(proof_profile, proof_size) || !converter.SetDestination(display_profile, display_size, MODEL_RGB, MODEL_RGB)) {
		return NULL;
	}
	return converter.Convert();
}

const void * DLL_CALLCONV
FreeImage_GetBuiltInICCProfile(int profile, DWORD *size) {
	if (size) {
		*size = 0;
	}
	if ((profile < 0) || (profile >= ICC_BUILTIN_COUNT)) {
		return NULL;
	}
	const BuiltInProfiles &profiles = GetBuiltInProfiles();
	if (size && profiles.data[profile]) {
		*size = profiles.size[profile];
	}
	return profiles.data[profile];
}

unsigned DLL_CALLCONV
FreeImage_GetICCProfileDescription(const void *profile, DWORD size, char *buffer, unsigned buffer_size) {
	if (buffer && buffer_size) {
		buffer[0] = 0;
	}
	Context context;
	context.mute = true;
	cmsHPROFILE handle = context.Open(profile, size);
	if (!handle) {
		return 0;
	}
	unsigned needed = 0;
	const cmsUInt32Number length = cmsGetProfileInfoUTF8(handle, cmsInfoDescription, "en", "US", NULL, 0);
	char *text = length ? (char*)malloc(length) : NULL;
	if (text && cmsGetProfileInfoUTF8(handle, cmsInfoDescription, "en", "US", text, length)) {
		text[length - 1] = 0;
		needed = (unsigned)strlen(text) + 1;
		if (buffer && buffer_size) {
			// cut on a character boundary
			unsigned n = MIN(needed - 1, buffer_size - 1);
			while ((n > 0) && (n < needed - 1) && (((BYTE)text[n] & 0xC0) == 0x80)) {
				n--;
			}
			memcpy(buffer, text, n);
			buffer[n] = 0;
		}
	}
	free(text);
	cmsCloseProfile(handle);
	return needed;
}

DWORD DLL_CALLCONV
FreeImage_GetICCProfileColorSpace(const void *profile, DWORD size) {
	Context context;
	context.mute = true;
	cmsHPROFILE handle = context.Open(profile, size);
	if (!handle) {
		return 0;
	}
	const DWORD space = (DWORD)cmsGetColorSpace(handle);
	cmsCloseProfile(handle);
	return space;
}
