; FreeImage color management example for AutoHotkey v1.1
; Shows images in the colors of the monitor, converted by Little CMS through FreeImage:
; 32-bit RGBA images with an embedded RGB profile and CMYK images with an embedded CMYK profile.
; Open an image from the File menu, by dropping it on the window or as the first parameter;
; View > Color management compares it with the colors shown without color management.
;
; Functions used: FreeImage_ConvertToICCProfile, FreeImage_GetBuiltInICCProfile, FreeImage_GetICCProfileDescription,
; FreeImage_GetICCProfileColorSpace, FreeImage_DestroyICCProfile
;
; Needs FreeImage.dll built from this repository, of the same bitness as AutoHotkey, next to this script
; or in ..\..\Dist\x64 or x32, and Gdip_All.ahk in a Lib folder: https://github.com/marius-sucan/AHK-GDIp-Library-Compilation
;
; Code generated by Marius Șucan with Anthropic Claude

#NoEnv
#SingleInstance, Off
SetBatchLines, -1
#Include E:\Sucan twins\_small-apps\AutoHotkey\my scripts\_github\FreeImage-library\Wrapper\AHK\freeimage-wrapper.ahk
#Include E:\Sucan twins\_small-apps\AutoHotkey\my scripts\_github\quick-picto-viewer\lib\Gdip_All.ahk

UseMonitorProfile := 1   ; 0 - sRGB, for Windows HDR or Auto Color Management, which convert sRGB to the display themselves
Intent := 0x101          ; FICMS_INTENT_RELATIVE_COLORIMETRIC | FICMS_BLACKPOINT_COMPENSATION; see FreeImage_ConvertToICCProfile()

hDll := FreeImage_FoxInit(1, "E:\Sucan twins\_small-apps\AutoHotkey\my scripts\fast-image-viewer\cPlusPlus\freeimage-r1909-custom\x64\Release\")
If InStr(hDll, "err")
{
   MsgBox, 16, FreeImage, % "FreeImage.dll could not be loaded: " hDll
   ExitApp
}
pToken := Gdip_Startup()
CheckerBrush := CreateCheckerBrush()
Managed := 1, hSource := 0, pShown := 0

Menu, FileMenu, Add, &Open..., OpenFile
Menu, FileMenu, Add, E&xit, GuiClose
Menu, ViewMenu, Add, &Color management, ToggleManaged
Menu, ViewMenu, Check, &Color management
Menu, MainMenu, Add, &File, :FileMenu
Menu, MainMenu, Add, &View, :ViewMenu

Gui, +Resize +MinSize320x240 -DPIScale +hwndhGui
Gui, Menu, MainMenu
Gui, Margin, 0, 0
Gui, Add, Picture, x0 y0 w1 h1 0xE hwndhPic   ; SS_BITMAP
Gui, Add, StatusBar
Gui, Show, % "w" A_ScreenWidth*2//3 " h" A_ScreenHeight*2//3, FreeImage color management
SetDisplayProfile(UseMonitorProfile ? MonitorProfileFile(hGui) : "")
OnMessage(0x03, "CheckMonitor")   ; WM_MOVE
OnMessage(0x7E, "CheckMonitor")   ; WM_DISPLAYCHANGE
If A_Args.Length()
   OpenImage(A_Args[1])
Else
   UpdateView()
Return

GuiSize:
   If (A_EventInfo!=1)   ; not minimized
      SetTimer, Redraw, -30
Return

GuiDropFiles:
   Loop, Parse, A_GuiEvent, `n
   {
      OpenImage(A_LoopField)
      Break
   }
Return

OpenFile:
   Gui, +OwnDialogs
   FileSelectFile, file, 3,, Open an image, Images (*.jpg; *.jpeg; *.png; *.tif; *.tiff; *.psd; *.webp; *.jxr; *.avif; *.heic; *.heif)
   If (file!="")
      OpenImage(file)
Return

ToggleManaged:
   Managed := !Managed
   Menu, ViewMenu, ToggleCheck, &Color management
   UpdateView()
Return

GuiClose:
   FreeImage_UnLoad(hSource)
   If pShown
      Gdip_DisposeImage(pShown)
   Gdip_DeleteBrush(CheckerBrush)
   Gdip_Shutdown(pToken)
ExitApp

OpenImage(file) {
   Global hSource, FileName
   Critical
   hImage := LoadImageFile(file)
   If !hImage
   {
      SB_SetText("Cannot open " file)
      Return
   }
   FreeImage_UnLoad(hSource)
   hSource := hImage
   SplitPath, file, FileName
   UpdateView()
}

LoadImageFile(file) {
; CMYK JPEG, TIFF and PSD files stay CMYK: converted to RGB by FreeImage, their CMYK profile no longer applies
   fif := FreeImage_GetFileType(file)
   flags := (fif=2) ? 0x0C : (fif=18 || fif=20) ? 0x01 : 0   ; JPEG_CMYK | JPEG_EXIFROTATE; TIFF_CMYK, PSD_CMYK
   Return FreeImage_Load(file, fif, flags)
}

UpdateView() {
   Global hSource, pShown, Managed, FileName, DisplayName
   Critical   ; the timers must not draw a disposed bitmap
   If pShown
      Gdip_DisposeImage(pShown)
   pShown := hSource ? ShownBitmap(hSource, Managed) : 0
   Redraw()
   If !hSource
      SB_SetText("Open or drop an image; display profile: " DisplayName)
   Else
      SB_SetText(FileName ": " ImageInfo(hSource) (pShown ? "" : ", cannot be shown") " -> " (Managed ? DisplayName : "not color managed"))
}

ShownBitmap(hImage, managed) {
; a GDI+ bitmap of the image in the display's colors; unmanaged, RGB is shown as sRGB and CMYK by FreeImage's formula
   Global pDisplay, DisplaySize, Intent
   If managed
   {
      hRGB := FreeImage_ConvertToICCProfile(hImage, pDisplay, DisplaySize, Intent)
   } Else
   {
      hCopy := FreeImage_Clone(hImage)
      FreeImage_DestroyICCProfile(hCopy)
      pSRGB := FreeImage_GetBuiltInICCProfile(0, size)   ; FICMS_PROFILE_SRGB
      hRGB := FreeImage_ConvertToICCProfile(hCopy, pSRGB, size)
      FreeImage_UnLoad(hCopy)
   }
   h32 := FreeImage_ConvertTo32Bits(hRGB)   ; 8- and 16-bit images
   FreeImage_UnLoad(hRGB)
   pBitmap := h32 ? ConvertFIMtoPBITMAP(h32) : 0
   FreeImage_UnLoad(h32)
   Return pBitmap
}

ImageInfo(hImage) {
   info := FreeImage_GetBPP(hImage) "-bit " FreeImage_GetColorType(hImage)
   pICC := FreeImage_GetICCProfileData(hImage, size)
   If !pICC
      Return info ", no profile"
   space := FreeImage_GetICCProfileColorSpace(pICC, size)
   space := (space=0x52474220) ? "RGB" : (space=0x434D594B) ? "CMYK" : (space=0x47524159) ? "grey" : "other"
   Return info ", " FreeImage_GetICCProfileDescription(pICC, size) " (" space ")"
}

SetDisplayProfile(file) {
; file - the monitor's profile; blank, or not an RGB profile - sRGB
   Global MonitorICC, pDisplay, DisplaySize, DisplayName, DisplayFile
   DisplayFile := file, size := 0
   f := (file!="") ? FileOpen(file, "r") : ""
   If IsObject(f)
   {
      SoundBeep 
      size := f.Length
      VarSetCapacity(MonitorICC, size, 0)
      f.RawRead(MonitorICC, size)
      f.Close()
   }
   If (size && FreeImage_GetICCProfileColorSpace(&MonitorICC, size)=0x52474220)   ; FICMS_COLORSPACE_RGB
      pDisplay := &MonitorICC, DisplaySize := size
   Else
      pDisplay := FreeImage_GetBuiltInICCProfile(0, DisplaySize)   ; FICMS_PROFILE_SRGB
   DisplayName := FreeImage_GetICCProfileDescription(pDisplay, DisplaySize)
}

MonitorProfileFile(hwnd) {
; the ICC profile file Windows assigns to the monitor showing the window
   VarSetCapacity(mi, 104, 0)   ; MONITORINFOEXW
   NumPut(104, mi, 0, "UInt")
   hMonitor := DllCall("MonitorFromWindow", "Ptr", hwnd, "UInt", 2, "Ptr")   ; MONITOR_DEFAULTTONEAREST
   If !DllCall("GetMonitorInfoW", "Ptr", hMonitor, "Ptr", &mi)
      Return ""
   hdc := DllCall("CreateICW", "Ptr", &mi + 40, "Ptr", 0, "Ptr", 0, "Ptr", 0, "Ptr")   ; szDevice
   size := 1024
   VarSetCapacity(path, size * 2, 0)
   ok := hdc && DllCall("GetICMProfileW", "Ptr", hdc, "UInt*", size, "Ptr", &path)
   If hdc
      DllCall("DeleteDC", "Ptr", hdc)
   path := ok ? StrGet(&path, "UTF-16") : ""
   Return FileExist(path) ? path : ""
}

CheckMonitor(wParam, lParam, msg, hwnd) {
   Global hGui
   If (hwnd=hGui)
      SetTimer, UpdateMonitorProfile, -300
}

UpdateMonitorProfile() {
; converts the image again when the window reaches a monitor with another profile
   Global hGui, UseMonitorProfile, DisplayFile
   Critical
   If !UseMonitorProfile
      Return
   file := MonitorProfileFile(hGui)
   If (file!=DisplayFile)
   {
      SetDisplayProfile(file)
      UpdateView()
   }
}

Redraw() {
   Global hGui, hPic, pShown
   Critical
   VarSetCapacity(rc, 16, 0)
   DllCall("GetClientRect", "Ptr", hGui, "Ptr", &rc)
   ControlGetPos,,,, sbH, msctls_statusbar321, ahk_id %hGui%
   w := NumGet(rc, 8, "Int"), h := NumGet(rc, 12, "Int") - sbH
   If (w<1 || h<1)
      Return
   GuiControl, Move, %hPic%, w%w% h%h%
   SetImage(hPic, ComposeView(pShown, w, h))   ; deletes the previous bitmap
}

ComposeView(pBitmap, w, h) {
; a 24-bit bitmap: the image fitted and centered over a checkerboard that shows its transparency
   Global CheckerBrush
   hbm := CreateDIBSection(w, h, "", 24)
   hdc := CreateCompatibleDC()
   obm := SelectObject(hdc, hbm)
   G := Gdip_GraphicsFromHDC(hdc)
   Gdip_FillRectangle(G, CheckerBrush, 0, 0, w, h)
   If pBitmap
   {
      Gdip_GetImageDimensions(pBitmap, imgW, imgH)
      scale := Min(1, w/imgW, h/imgH)
      dw := Round(imgW*scale), dh := Round(imgH*scale)
      Gdip_SetInterpolationMode(G, (scale<1) ? 7 : 5)   ; HighQualityBicubic, NearestNeighbor
      Gdip_SetPixelOffsetMode(G, 2)   ; Half: at 100% the pixels are copied
      ImageAttr := Gdip_CreateImageAttributes()
      Gdip_SetImageAttributesWrapMode(ImageAttr, 3)   ; TileFlipXY: no half-transparent edges
      Gdip_DrawImage(G, pBitmap, (w-dw)//2, (h-dh)//2, dw, dh, 0, 0, imgW, imgH, 1, 2, ImageAttr)
      Gdip_DisposeImageAttributes(ImageAttr)
   }
   Gdip_DeleteGraphics(G)
   SelectObject(hdc, obm)
   DeleteDC(hdc)
   Return hbm
}

CreateCheckerBrush() {
; white and light grey squares of 8 pixels
   pTile := Gdip_CreateBitmap(16, 16)
   G := Gdip_GraphicsFromImage(pTile)
   Gdip_GraphicsClear(G, 0xFFFFFFFF)
   pGrey := Gdip_BrushCreateSolid(0xFFCCCCCC)
   Gdip_FillRectangle(G, pGrey, 8, 0, 8, 8)
   Gdip_FillRectangle(G, pGrey, 0, 8, 8, 8)
   Gdip_DeleteBrush(pGrey)
   Gdip_DeleteGraphics(G)
   pBrush := Gdip_CreateTextureBrush(pTile, 0)   ; WrapModeTile
   Gdip_DisposeImage(pTile)
   Return pBrush
}
