// ==========================================================
// Linear light: the transfer curve of an image undone
//
// This file is part of FreeImage 3
//
// COVERED CODE IS PROVIDED UNDER THIS LICENSE ON AN "AS IS" BASIS, WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, WITHOUT LIMITATION, WARRANTIES
// THAT THE COVERED CODE IS FREE OF DEFECTS, MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE
// OR NON-INFRINGING. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE COVERED
// CODE IS WITH YOU. SHOULD ANY COVERED CODE PROVE DEFECTIVE IN ANY RESPECT, YOU (NOT
// THE INITIAL DEVELOPER OR ANY OTHER CONTRIBUTOR) ASSUME THE COST OF ANY NECESSARY
// SERVICING, REPAIR OR CORRECTION. THIS DISCLAIMER OF WARRANTY CONSTITUTES AN ESSENTIAL
// PART OF THIS LICENSE. NO USE OF ANY COVERED CODE IS AUTHORIZED HEREUNDER EXCEPT UNDER
// THIS DISCLAIMER.
//
// Use at your own risk!
//
// Code generated by Marius Șucan with Anthropic Claude
// ==========================================================

#include "FreeImage.h"
#include "Utilities.h"

#define CMS_NO_REGISTER_KEYWORD 1
#include "../LibLCMS2/include/lcms2.h"

// SDR reference white, ITU-R BT.2408: 1.0 in the result
#define REFERENCE_WHITE 203.0

// the nominal peak of the HLG reference display, ITU-R BT.2100, and its system gamma
#define HLG_PEAK 1000.0
#define HLG_GAMMA 1.2

// images smaller than this are converted on one thread
#define LINEAR_PARALLEL_PIXELS 65536

namespace {

// the light of a signal, 1.0 being SDR reference white
typedef double (*Curve)(double signal);

enum Layout {
	IN_RGB8,		// 24-bit, after FreeImage_ConvertTo24Bits
	IN_RGBA8,		// 32-bit, after FreeImage_ConvertTo32Bits
	IN_GREY16,
	IN_RGB16,
	IN_RGBA16,
	IN_GREYF,
	IN_RGBF,
	IN_RGBAF
};

struct Plan {
	Curve curve;					// NULL: the profile's tone curves, or linear light already
	const cmsToneCurve *trc[3];		// the profile's tone curves, red, green and blue, or grey in all three
	bool hlg;						// the HLG display step, per pixel, after the curve
	double weights[3];				// the luminance the HLG step reads
	bool convert;					// the primaries matrix, after the HLG step
	double matrix[3][3];
	BYTE primaries;					// the code point of the result's primaries

	Plan() : curve(NULL), hlg(false), convert(false), primaries(2) {
		trc[0] = trc[1] = trc[2] = NULL;
		weights[0] = 0.2126; weights[1] = 0.7152; weights[2] = 0.0722;
	}
	double Apply(unsigned channel, double signal) const {
		if (trc[channel]) {
			return cmsEvalToneCurveFloat(trc[channel], (cmsFloat32Number)signal);
		}
		return curve ? curve(signal) : signal;
	}
};

struct Chromaticities {
	BYTE code;
	double red[2], green[2], blue[2], white[2];
};

} // namespace

// ----------------------------------------------------------
//   Transfer curves, ITU-T H.273
// ----------------------------------------------------------

static double
Signed(double signal, double light) {
	return (signal < 0) ? -light : light;
}

static double
FromLinear(double signal) {
	return signal;
}

static double
FromSRGB(double signal) {
	const double v = fabs(signal);
	return Signed(signal, (v <= 0.04045) ? v / 12.92 : pow((v + 0.055) / 1.055, 2.4));
}

// BT.709, BT.601 and BT.2020: their camera curve, undone; xvYCC and BT.1361 extend it below 0
static double
FromBT709(double signal) {
	const double v = fabs(signal);
	return Signed(signal, (v < 0.081) ? v / 4.5 : pow((v + 0.099) / 1.099, 1 / 0.45));
}

static double
FromGamma22(double signal) {
	return Signed(signal, pow(fabs(signal), 2.2));
}

static double
FromGamma28(double signal) {
	return Signed(signal, pow(fabs(signal), 2.8));
}

static double
FromSMPTE240(double signal) {
	const double v = fabs(signal);
	return Signed(signal, (v < 0.0913) ? v / 4 : pow((v + 0.1115) / 1.1115, 1 / 0.45));
}

static double
FromLog100(double signal) {
	return (signal <= 0) ? 0 : pow(10.0, 2 * (signal - 1));
}

static double
FromLog316(double signal) {
	return (signal <= 0) ? 0 : pow(10.0, 2.5 * (signal - 1));
}

// SMPTE ST 2084: absolute luminance up to 10000 cd/m2
static double
FromPQ(double signal) {
	const double m1 = 2610.0 / 16384, m2 = 2523.0 / 4096 * 128;
	const double c1 = 3424.0 / 4096, c2 = 2413.0 / 4096 * 32, c3 = 2392.0 / 4096 * 32;
	const double p = pow(MAX(signal, 0.0), 1 / m2);
	return 10000 * pow(MAX(p - c1, 0.0) / (c2 - c3 * p), 1 / m1) / REFERENCE_WHITE;
}

// ARIB STD-B67: scene light up to 1, the display step comes after
static double
FromHLG(double signal) {
	const double a = 0.17883277, b = 1 - 4 * a, c = 0.5 - a * log(4 * a);
	if (signal <= 0) {
		return 0;
	}
	return (signal <= 0.5) ? signal * signal / 3 : (exp((signal - c) / a) + b) / 12;
}

// SMPTE ST 428-1, the cinema's XYZ, 48 cd/m2 as white
static double
FromSMPTE428(double signal) {
	return pow(MAX(signal, 0.0), 2.6) * 52.37 / 48;
}

static Curve
CurveOfCode(BYTE transfer) {
	switch (transfer) {
		case 1: case 6: case 11: case 12: case 14: case 15:
			return FromBT709;
		case 4:
			return FromGamma22;
		case 5:
			return FromGamma28;
		case 7:
			return FromSMPTE240;
		case 8:
			return FromLinear;
		case 9:
			return FromLog100;
		case 10:
			return FromLog316;
		case 13:
			return FromSRGB;
		case 16:
			return FromPQ;
		case 17:
			return FromSMPTE428;
		case 18:
			return FromHLG;
		default:	// 2 unspecified, 0 and 3 reserved
			return NULL;
	}
}

// ----------------------------------------------------------
//   Primaries
// ----------------------------------------------------------

// ITU-T H.273 table 2; 10, the cinema's XYZ, has no primaries a matrix can be built from
static const Chromaticities *
ChromaticitiesOfCode(BYTE code) {
	static const Chromaticities table[] = {
		{ 1, { 0.640, 0.330 }, { 0.300, 0.600 }, { 0.150, 0.060 }, { 0.3127, 0.3290 } },	// BT.709, sRGB
		{ 4, { 0.670, 0.330 }, { 0.210, 0.710 }, { 0.140, 0.080 }, { 0.3100, 0.3160 } },	// BT.470 System M
		{ 5, { 0.640, 0.330 }, { 0.290, 0.600 }, { 0.150, 0.060 }, { 0.3127, 0.3290 } },	// BT.601 625 lines
		{ 6, { 0.630, 0.340 }, { 0.310, 0.595 }, { 0.155, 0.070 }, { 0.3127, 0.3290 } },	// BT.601 525 lines
		{ 7, { 0.630, 0.340 }, { 0.310, 0.595 }, { 0.155, 0.070 }, { 0.3127, 0.3290 } },	// SMPTE 240M
		{ 8, { 0.681, 0.319 }, { 0.243, 0.692 }, { 0.145, 0.049 }, { 0.3100, 0.3160 } },	// generic film
		{ 9, { 0.708, 0.292 }, { 0.170, 0.797 }, { 0.131, 0.046 }, { 0.3127, 0.3290 } },	// BT.2020, BT.2100
		{ 11, { 0.680, 0.320 }, { 0.265, 0.690 }, { 0.150, 0.060 }, { 0.3140, 0.3510 } },	// DCI-P3
		{ 12, { 0.680, 0.320 }, { 0.265, 0.690 }, { 0.150, 0.060 }, { 0.3127, 0.3290 } },	// Display P3
		{ 22, { 0.630, 0.340 }, { 0.295, 0.605 }, { 0.155, 0.077 }, { 0.3127, 0.3290 } }	// EBU Tech 3213-E
	};
	for (unsigned i = 0; i < sizeof(table) / sizeof(table[0]); i++) {
		if (table[i].code == code) {
			return &table[i];
		}
	}
	return NULL;
}

static cmsHPROFILE
LinearProfile(cmsContext context, const cmsCIExyY &white, const cmsCIExyYTRIPLE &primaries) {
	cmsToneCurve *linear = cmsBuildGamma(context, 1.0);
	if (!linear) {
		return NULL;
	}
	cmsToneCurve *curves[3] = { linear, linear, linear };
	cmsHPROFILE profile = cmsCreateRGBProfileTHR(context, &white, &primaries, curves);
	cmsFreeToneCurve(linear);
	return profile;
}

static cmsHPROFILE
LinearProfileOfCode(cmsContext context, const Chromaticities &c) {
	const cmsCIExyY white = { c.white[0], c.white[1], 1 };
	const cmsCIExyYTRIPLE primaries = { { c.red[0], c.red[1], 1 }, { c.green[0], c.green[1], 1 }, { c.blue[0], c.blue[1], 1 } };
	return LinearProfile(context, white, primaries);
}

// a matrix-shaper profile with linear tone curves: its colorants, against the PCS white
static cmsHPROFILE
LinearCopy(cmsContext context, cmsHPROFILE profile) {
	const cmsCIEXYZ *red = (const cmsCIEXYZ *)cmsReadTag(profile, cmsSigRedColorantTag);
	const cmsCIEXYZ *green = (const cmsCIEXYZ *)cmsReadTag(profile, cmsSigGreenColorantTag);
	const cmsCIEXYZ *blue = (const cmsCIEXYZ *)cmsReadTag(profile, cmsSigBlueColorantTag);
	if (!red || !green || !blue) {
		return NULL;
	}
	cmsCIExyY white;
	cmsCIExyYTRIPLE primaries;
	cmsXYZ2xyY(&white, cmsD50_XYZ());
	cmsXYZ2xyY(&primaries.Red, red);
	cmsXYZ2xyY(&primaries.Green, green);
	cmsXYZ2xyY(&primaries.Blue, blue);
	return LinearProfile(context, white, primaries);
}

// the colors of linear light in 'from' as BT.709's, white kept white: Little CMS gives the columns,
// the pixels go through the matrix, which leaves light above white unclipped
static bool
MatrixToBT709(cmsContext context, cmsHPROFILE from, double matrix[3][3]) {
	const Chromaticities *bt709 = ChromaticitiesOfCode(1);
	cmsHPROFILE to = LinearProfileOfCode(context, *bt709);
	if (!to) {
		return false;
	}
	cmsHTRANSFORM transform = cmsCreateTransformTHR(context, from, TYPE_RGB_DBL, to, TYPE_RGB_DBL, INTENT_RELATIVE_COLORIMETRIC, cmsFLAGS_NOCACHE | cmsFLAGS_NOOPTIMIZE);
	cmsCloseProfile(to);
	if (!transform) {
		return false;
	}
	const double basis[9] = { 1, 0, 0, 0, 1, 0, 0, 0, 1 };
	double columns[9];
	cmsDoTransform(transform, basis, columns, 3);
	cmsDeleteTransform(transform);
	for (unsigned row = 0; row < 3; row++) {
		for (unsigned column = 0; column < 3; column++) {
			matrix[row][column] = columns[column * 3 + row];
			if (!IsFiniteValue(matrix[row][column])) {
				return false;
			}
		}
	}
	return true;
}

// ----------------------------------------------------------
//   The plan: which curve, which display step, which matrix
// ----------------------------------------------------------

static bool
IsGreyPixels(FIBITMAP *dib) {
	switch (FreeImage_GetImageType(dib)) {
		case FIT_UINT16:
		case FIT_FLOAT:
			return true;
		case FIT_BITMAP: {
			const FREE_IMAGE_COLOR_TYPE color = FreeImage_GetColorType(dib);
			return (color == FIC_MINISBLACK) || (color == FIC_MINISWHITE);
		}
		default:
			return false;
	}
}

static void
PlanFromCode(Plan &plan, cmsContext context, BYTE primaries, BYTE transfer, bool to_bt709) {
	plan.curve = CurveOfCode(transfer);
	plan.hlg = (transfer == 18);
	if (primaries == 9) {
		// BT.2100's luminance for the HLG display step
		plan.weights[0] = 0.2627; plan.weights[1] = 0.6780; plan.weights[2] = 0.0593;
	}
	plan.primaries = primaries;
	if (to_bt709 && (primaries != 1)) {
		const Chromaticities *c = ChromaticitiesOfCode(primaries);
		cmsHPROFILE from = c ? LinearProfileOfCode(context, *c) : NULL;
		if (from) {
			plan.convert = MatrixToBT709(context, from, plan.matrix);
			cmsCloseProfile(from);
		}
		if (plan.convert || (primaries == 2)) {
			plan.primaries = 1;
		}
	}
}

// ----------------------------------------------------------
//   Conversion
// ----------------------------------------------------------

static void
ConvertRows(FIBITMAP *src, FIBITMAP *dst, Layout layout, const Plan &plan, const std::vector<float> lut[3]) {
	const int width = (int)FreeImage_GetWidth(src);
	const int height = (int)FreeImage_GetHeight(src);
	const unsigned out_step = (FreeImage_GetImageType(dst) == FIT_RGBAF) ? 4 : 3;
	const bool parallel = ((double)width * height > LINEAR_PARALLEL_PIXELS);
	const double hlg_scale = HLG_PEAK / REFERENCE_WHITE;

#pragma omp parallel for if(parallel)
	for (int y = 0; y < height; y++) {
		const BYTE *in = FreeImage_GetScanLine(src, y);
		float *out = (float *)FreeImage_GetScanLine(dst, y);
		for (int x = 0; x < width; x++) {
			double rgb[3];
			double alpha = 1;
			switch (layout) {
				case IN_RGB8:
				case IN_RGBA8: {
					const BYTE *p = in + x * ((layout == IN_RGBA8) ? 4 : 3);
					rgb[0] = lut[0][p[FI_RGBA_RED]];
					rgb[1] = lut[1][p[FI_RGBA_GREEN]];
					rgb[2] = lut[2][p[FI_RGBA_BLUE]];
					if (layout == IN_RGBA8) {
						alpha = p[FI_RGBA_ALPHA] / 255.0;
					}
					break;
				}
				case IN_GREY16:
					rgb[0] = rgb[1] = rgb[2] = lut[0][((const WORD *)in)[x]];
					break;
				case IN_RGB16:
				case IN_RGBA16: {
					const WORD *p = (const WORD *)in + x * ((layout == IN_RGBA16) ? 4 : 3);
					rgb[0] = lut[0][p[0]];
					rgb[1] = lut[1][p[1]];
					rgb[2] = lut[2][p[2]];
					if (layout == IN_RGBA16) {
						alpha = p[3] / 65535.0;
					}
					break;
				}
				case IN_GREYF:
					rgb[0] = rgb[1] = rgb[2] = plan.Apply(0, ((const float *)in)[x]);
					break;
				default: {
					const float *p = (const float *)in + x * ((layout == IN_RGBAF) ? 4 : 3);
					for (unsigned c = 0; c < 3; c++) {
						rgb[c] = plan.Apply(c, p[c]);
					}
					if (layout == IN_RGBAF) {
						alpha = p[3];
					}
					break;
				}
			}
			if (plan.hlg) {
				// the reference display: 0.75 becomes 203 cd/m2
				const double luminance = plan.weights[0] * rgb[0] + plan.weights[1] * rgb[1] + plan.weights[2] * rgb[2];
				const double gain = (luminance > 0) ? hlg_scale * pow(luminance, HLG_GAMMA - 1) : 0;
				for (unsigned c = 0; c < 3; c++) {
					rgb[c] *= gain;
				}
			}
			float *q = out + x * out_step;
			if (plan.convert) {
				for (unsigned c = 0; c < 3; c++) {
					q[c] = (float)(plan.matrix[c][0] * rgb[0] + plan.matrix[c][1] * rgb[1] + plan.matrix[c][2] * rgb[2]);
				}
			} else {
				q[0] = (float)rgb[0];
				q[1] = (float)rgb[1];
				q[2] = (float)rgb[2];
			}
			if (out_step == 4) {
				q[3] = (float)alpha;
			}
		}
	}
}

// the result's description: its primaries and linear transfer, and the profile it keeps, if any
static void
Describe(FIBITMAP *dst, FIBITMAP *dib, BYTE primaries, const std::vector<BYTE> &icc) {
	FreeImage_CloneMetadata(dst, dib);
	FreeImage_SetDotsPerMeterX(dst, FreeImage_GetDotsPerMeterX(dib));
	FreeImage_SetDotsPerMeterY(dst, FreeImage_GetDotsPerMeterY(dib));
	// the result is light: the source's precision no longer applies
	FreeImage_SetMetadata(FIMD_CUSTOM, dst, "SignificantBits", NULL);
	FreeImage_SetMetadata(FIMD_CUSTOM, dst, "UnscaledBits", NULL);
	SetCICPMetadata(dst, primaries, 8, 0, TRUE);
	FreeImage_DestroyICCProfile(dst);
	if (!icc.empty()) {
		FreeImage_CreateICCProfile(dst, (void *)&icc[0], (long)icc.size());
	}
}

// a profile Little CMS cannot reduce to tone curves and colorants: converted to linear sRGB by FreeImage_ConvertToICCProfile
static FIBITMAP *
ConvertThroughProfile(FIBITMAP *dib, bool alpha) {
	FIBITMAP *encoded = alpha ? FreeImage_ConvertToRGBAF(dib) : FreeImage_ConvertToRGBF(dib);
	if (!encoded) {
		return NULL;
	}
	const FIICCPROFILE *icc = FreeImage_GetICCProfile(dib);
	FreeImage_CreateICCProfile(encoded, icc->data, (long)icc->size);
	DWORD size = 0;
	const void *linear = FreeImage_GetBuiltInICCProfile(FICMS_PROFILE_LINEAR_SRGB, &size);
	FIBITMAP *result = linear ? FreeImage_ConvertToICCProfile(encoded, linear, size, FICMS_INTENT_RELATIVE_COLORIMETRIC) : NULL;
	FreeImage_Unload(encoded);
	if (result) {
		// linear sRGB is what FreeImage takes a floating-point image without a profile for
		Describe(result, dib, 1, std::vector<BYTE>());
	}
	return result;
}

static unsigned
UnscaledMaximum(FIBITMAP *dib, unsigned maximum) {
	FITAG *tag = NULL;
	if (FreeImage_GetMetadata(FIMD_CUSTOM, dib, "UnscaledBits", &tag) && tag && (FreeImage_GetTagType(tag) == FIDT_BYTE) && (FreeImage_GetTagCount(tag) == 1)) {
		const unsigned bits = *(const BYTE *)FreeImage_GetTagValue(tag);
		if ((bits > 0) && ((1u << bits) - 1 < maximum)) {
			return (1u << bits) - 1;
		}
	}
	return maximum;
}

static FIBITMAP *
ConvertToLinear(FIBITMAP *dib, int flags, cmsContext context) {
	const FREE_IMAGE_TYPE type = FreeImage_GetImageType(dib);
	const bool to_bt709 = ((flags & FI_LINEAR_SRGB_PRIMARIES) == FI_LINEAR_SRGB_PRIMARIES);
	const bool alpha = (type == FIT_RGBA16) || (type == FIT_RGBAF) || ((type == FIT_BITMAP) && FreeImage_IsTransparent(dib));
	const bool grey = IsGreyPixels(dib);

	Plan plan;
	cmsHPROFILE profile = NULL;
	std::vector<BYTE> linear_icc;
	BYTE cicp[4];
	const bool described = GetCICPMetadata(dib, cicp) && (CurveOfCode(cicp[1]) != NULL);
	if (described) {
		PlanFromCode(plan, context, cicp[0], cicp[1], to_bt709);
	} else {
		const FIICCPROFILE *icc = FreeImage_GetICCProfile(dib);
		if (icc && icc->data && (icc->size >= 132)) {
			profile = cmsOpenProfileFromMemTHR(context, icc->data, icc->size);
		}
		const cmsColorSpaceSignature space = profile ? cmsGetColorSpace(profile) : (cmsColorSpaceSignature)0;
		if (profile && (space != (grey ? cmsSigGrayData : cmsSigRgbData))) {
			// a profile for other pixels says nothing about these
			cmsCloseProfile(profile);
			profile = NULL;
		}
		const cmsVideoSignalType *signal = profile ? (const cmsVideoSignalType *)cmsReadTag(profile, cmsSigcicpTag) : NULL;
		if (signal && CurveOfCode(signal->TransferCharacteristics)) {
			PlanFromCode(plan, context, signal->ColourPrimaries, signal->TransferCharacteristics, to_bt709);
		} else if (profile && grey) {
			plan.trc[0] = plan.trc[1] = plan.trc[2] = (const cmsToneCurve *)cmsReadTag(profile, cmsSigGrayTRCTag);
			if (!plan.trc[0]) {
				plan.curve = FromSRGB;
			}
			plan.primaries = 1;
		} else if (profile) {
			if (!cmsIsMatrixShaper(profile)) {
				cmsCloseProfile(profile);
				return ConvertThroughProfile(dib, alpha);
			}
			plan.trc[0] = (const cmsToneCurve *)cmsReadTag(profile, cmsSigRedTRCTag);
			plan.trc[1] = (const cmsToneCurve *)cmsReadTag(profile, cmsSigGreenTRCTag);
			plan.trc[2] = (const cmsToneCurve *)cmsReadTag(profile, cmsSigBlueTRCTag);
			cmsHPROFILE linear = LinearCopy(context, profile);
			if (!plan.trc[0] || !plan.trc[1] || !plan.trc[2] || !linear) {
				if (linear) {
					cmsCloseProfile(linear);
				}
				cmsCloseProfile(profile);
				return ConvertThroughProfile(dib, alpha);
			}
			if (to_bt709) {
				plan.convert = MatrixToBT709(context, linear, plan.matrix);
				plan.primaries = 1;
			} else {
				// the result keeps the profile's colorants, with linear tone curves
				cmsUInt32Number size = 0;
				if (cmsSaveProfileToMem(linear, NULL, &size) && size) {
					linear_icc.resize(size);
					if (!cmsSaveProfileToMem(linear, &linear_icc[0], &size)) {
						linear_icc.clear();
					}
				}
			}
			cmsCloseProfile(linear);
		} else {
			// FreeImage's defaults: sRGB for 8- and 16-bit images, linear sRGB for floating point
			const bool floating = (type == FIT_FLOAT) || (type == FIT_RGBF) || (type == FIT_RGBAF);
			plan.curve = floating ? FromLinear : FromSRGB;
			plan.primaries = 1;
		}
	}

	// the source, in a layout the rows read
	FIBITMAP *src = dib;
	Layout layout;
	unsigned maximum = 0;
	switch (type) {
		case FIT_BITMAP:
			src = alpha ? FreeImage_ConvertTo32Bits(dib) : FreeImage_ConvertTo24Bits(dib);
			layout = alpha ? IN_RGBA8 : IN_RGB8;
			maximum = 255;
			break;
		case FIT_UINT16:
			layout = IN_GREY16;
			maximum = 65535;
			break;
		case FIT_RGB16:
			layout = IN_RGB16;
			maximum = 65535;
			break;
		case FIT_RGBA16:
			layout = IN_RGBA16;
			maximum = 65535;
			break;
		case FIT_FLOAT:
			layout = IN_GREYF;
			break;
		case FIT_RGBF:
			layout = IN_RGBF;
			break;
		default:
			layout = IN_RGBAF;
			break;
	}

	FIBITMAP *dst = NULL;
	if (src) {
		std::vector<float> lut[3];
		if (maximum) {
			// unscaled samples are read in their own precision
			const unsigned top = UnscaledMaximum(dib, maximum);
			for (unsigned c = 0; c < 3; c++) {
				if ((c > 0) && (plan.trc[c] == plan.trc[0])) {
					lut[c] = lut[0];
					continue;
				}
				lut[c].resize(maximum + 1);
				for (unsigned v = 0; v <= maximum; v++) {
					lut[c][v] = (float)plan.Apply(c, (double)MIN(v, top) / top);
				}
			}
		}
		dst = FreeImage_AllocateT(alpha ? FIT_RGBAF : FIT_RGBF, (int)FreeImage_GetWidth(dib), (int)FreeImage_GetHeight(dib));
		if (dst) {
			ConvertRows(src, dst, layout, plan, lut);
			Describe(dst, dib, plan.primaries, linear_icc);
		}
		if (src != dib) {
			FreeImage_Unload(src);
		}
	}
	if (profile) {
		cmsCloseProfile(profile);
	}
	return dst;
}

static void
MuteLittleCMS(cmsContext, cmsUInt32Number, const char *) {
}

// ==========================================================
//   Public function
// ==========================================================

/**
Converts an image to linear light, the input FreeImage_ToneMapping expects. The curve undone is the
one the CICP tag names (PQ, HLG, sRGB, BT.709 and the other curves of ITU-T H.273), else the ICC
profile's cicp tag or tone curves, else sRGB for 8- and 16-bit images; floating-point images without
either are linear already. 1.0 is SDR reference white, 203 cd/m2 (ITU-R BT.2408): PQ reaches 49 and
the HLG reference display 4.9. HLG gets the display step of BT.2100 for a 1000 cd/m2 display.
Samples tagged "UnscaledBits" are read in their own precision. CMYK images are converted to RGB first.
@param dib Image to convert: a standard bitmap, FIT_UINT16, FIT_RGB16, FIT_RGBA16, FIT_FLOAT, FIT_RGBF or FIT_RGBAF
@param flags FI_LINEAR_SRGB_PRIMARIES converts the colors to sRGB's primaries; otherwise they keep the image's,
which the CICP tag of the result names, or the linear copy of a matrix-shaper profile it carries
@return Returns a FIT_RGBF image, FIT_RGBAF when the image has an alpha channel, or NULL
*/
FIBITMAP * DLL_CALLCONV
FreeImage_ConvertToLinear(FIBITMAP *dib, int flags) {
	if (!FreeImage_HasPixels(dib)) {
		return NULL;
	}
	switch (FreeImage_GetImageType(dib)) {
		case FIT_BITMAP:
		case FIT_UINT16:
		case FIT_RGB16:
		case FIT_RGBA16:
		case FIT_FLOAT:
		case FIT_RGBF:
		case FIT_RGBAF:
			break;
		default:
			return NULL;
	}
	if (FreeImage_GetColorType(dib) == FIC_CMYK) {
		FIBITMAP *rgb = FreeImage_ConvertCMYKToRGB(dib, NULL, 0, 0);
		if (!rgb || (FreeImage_GetColorType(rgb) == FIC_CMYK)) {
			FreeImage_Unload(rgb);
			return NULL;
		}
		FIBITMAP *result = FreeImage_ConvertToLinear(rgb, flags);
		FreeImage_Unload(rgb);
		return result;
	}
	cmsContext context = cmsCreateContext(NULL, NULL);
	if (!context) {
		return NULL;
	}
	cmsSetLogErrorHandlerTHR(context, MuteLittleCMS);
	FIBITMAP *result = NULL;
	try {
		result = ConvertToLinear(dib, flags, context);
	} catch (std::bad_alloc &) {
		FreeImage_OutputMessageProc(FIF_UNKNOWN, FI_MSG_ERROR_MEMORY);
	}
	cmsDeleteContext(context);
	return result;
}
