// ==========================================================
// Tone mapping advice: does an image need tone mapping to be displayed?
//
// This file is part of FreeImage 3
//
// COVERED CODE IS PROVIDED UNDER THIS LICENSE ON AN "AS IS" BASIS, WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, WITHOUT LIMITATION, WARRANTIES
// THAT THE COVERED CODE IS FREE OF DEFECTS, MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE
// OR NON-INFRINGING. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE COVERED
// CODE IS WITH YOU. SHOULD ANY COVERED CODE PROVE DEFECTIVE IN ANY RESPECT, YOU (NOT
// THE INITIAL DEVELOPER OR ANY OTHER CONTRIBUTOR) ASSUME THE COST OF ANY NECESSARY
// SERVICING, REPAIR OR CORRECTION. THIS DISCLAIMER OF WARRANTY CONSTITUTES AN ESSENTIAL
// PART OF THIS LICENSE. NO USE OF ANY COVERED CODE IS AUTHORIZED HEREUNDER EXCEPT UNDER
// THIS DISCLAIMER.
//
// Use at your own risk!
//
// Code generated by Marius Șucan with Anthropic Claude
// ==========================================================

#include "FreeImage.h"
#include "Utilities.h"

#define CMS_NO_REGISTER_KEYWORD 1
#include "../LibLCMS2/include/lcms2.h"

// the most pixels inspected; a larger image is sampled on a regular grid
#define SAMPLE_BUDGET (1 << 20)

// 16-bit samples that all stay below this carry at most 12 bits: JPEG 2000 and scientific
// files store 9- to 12-bit data unscaled, which looks black when shown as it is
#define LOW_RANGE_LIMIT 4096

// the ITU-T H.273 code point for "unspecified"
#define CICP_UNSPECIFIED 2

#define CICP_KEY "CICP"

namespace {

// how the samples encode light
enum Transfer {
	TRANSFER_UNKNOWN = 0,	// not described
	TRANSFER_DISPLAY,		// a display curve: sRGB, BT.709, gamma 1.8 to 2.8, L*
	TRANSFER_HLG,			// Hybrid Log-Gamma, made to be shown as it is on SDR screens too
	TRANSFER_LINEAR,		// proportional to light
	TRANSFER_STEEP,			// logarithmic, or steeper than any display curve
	TRANSFER_PQ				// SMPTE ST 2084, absolute luminance up to 10000 cd/m2
};

// the file's format, looked up only when the verdict depends on it
class SourceFormat {
public:
	SourceFormat(const char *name, const wchar_t *wide_name) : m_name(name), m_wide_name(wide_name), m_fif(FIF_UNKNOWN), m_known(false) {
	}
	FREE_IMAGE_FORMAT Get() {
		if (!m_known) {
			m_known = true;
			if (m_name && *m_name) {
				m_fif = FreeImage_GetFileType(m_name, 0);
				if (m_fif == FIF_UNKNOWN) {
					m_fif = FreeImage_GetFIFFromFilename(m_name);
				}
			} else if (m_wide_name && *m_wide_name) {
				m_fif = FreeImage_GetFileTypeU(m_wide_name, 0);
				if (m_fif == FIF_UNKNOWN) {
					m_fif = FreeImage_GetFIFFromFilenameU(m_wide_name);
				}
			}
		}
		return m_fif;
	}

private:
	const char *m_name;
	const wchar_t *m_wide_name;
	FREE_IMAGE_FORMAT m_fif;
	bool m_known;
};

struct Samples16 {
	WORD brightest;		// the largest color sample
	bool widened;		// every sample is an 8-bit value widened to 16 bits
};

struct SamplesFloat {
	size_t finite;
	size_t negative;
	size_t bright;		// above white, 1.0
};

} // namespace

// ----------------------------------------------------------
//   The color description of the file: ITU-T H.273 code points
// ----------------------------------------------------------

void
SetCICPMetadata(FIBITMAP *dib, unsigned primaries, unsigned transfer, unsigned matrix, BOOL full_range) {
	if (!dib || ((primaries == CICP_UNSPECIFIED) && (transfer == CICP_UNSPECIFIED) && (matrix == CICP_UNSPECIFIED))) {
		return;
	}
	// code points are 8-bit; ISOBMFF stores them in 16 bits
	BYTE value[4] = {
		(BYTE)((primaries < 256) ? primaries : CICP_UNSPECIFIED),
		(BYTE)((transfer < 256) ? transfer : CICP_UNSPECIFIED),
		(BYTE)((matrix < 256) ? matrix : CICP_UNSPECIFIED),
		(BYTE)(full_range ? 1 : 0)
	};
	FITAG *tag = FreeImage_CreateTag();
	if (tag) {
		FreeImage_SetTagKey(tag, CICP_KEY);
		FreeImage_SetTagDescription(tag, "Color primaries, transfer characteristics, matrix coefficients, full range flag (ITU-T H.273)");
		FreeImage_SetTagType(tag, FIDT_BYTE);
		FreeImage_SetTagCount(tag, 4);
		FreeImage_SetTagLength(tag, 4);
		FreeImage_SetTagValue(tag, value);
		FreeImage_SetMetadata(FIMD_CUSTOM, dib, CICP_KEY, tag);
		FreeImage_DeleteTag(tag);
	}
}

// samples of fewer bits than the image type holds, unscaled: J2K_UNSCALED and JP2_UNSCALED loads
static bool
IsUnscaled(FIBITMAP *dib) {
	FITAG *tag = NULL;
	if (!FreeImage_GetMetadata(FIMD_CUSTOM, dib, "UnscaledBits", &tag) || !tag) {
		return false;
	}
	const BYTE *bits = (const BYTE *)FreeImage_GetTagValue(tag);
	if ((FreeImage_GetTagType(tag) != FIDT_BYTE) || (FreeImage_GetTagCount(tag) != 1) || !bits) {
		return false;
	}
	switch (FreeImage_GetImageType(dib)) {
		case FIT_BITMAP:
			return (*bits > 0) && (*bits < 8);
		case FIT_UINT16:
		case FIT_RGB16:
		case FIT_RGBA16:
			return (*bits > 0) && (*bits < 16);
		default:
			return false;
	}
}

bool
GetCICPMetadata(FIBITMAP *dib, BYTE cicp[4]) {
	FITAG *tag = NULL;
	if (!FreeImage_GetMetadata(FIMD_CUSTOM, dib, CICP_KEY, &tag) || !tag) {
		return false;
	}
	const void *value = FreeImage_GetTagValue(tag);
	if ((FreeImage_GetTagType(tag) != FIDT_BYTE) || (FreeImage_GetTagCount(tag) != 4) || !value) {
		return false;
	}
	memcpy(cicp, value, 4);
	return true;
}

static Transfer
TransferOfCode(BYTE transfer) {
	switch (transfer) {
		case 1:		// BT.709
		case 4:		// BT.470 System M, gamma 2.2
		case 5:		// BT.470 System B and G, gamma 2.8
		case 6:		// BT.601
		case 7:		// SMPTE 240M
		case 11:	// IEC 61966-2-4, xvYCC
		case 12:	// BT.1361
		case 13:	// IEC 61966-2-1, sRGB
		case 14:	// BT.2020, 10 bits
		case 15:	// BT.2020, 12 bits
		case 17:	// SMPTE ST 428-1, DCI XYZ
			return TRANSFER_DISPLAY;
		case 8:
			return TRANSFER_LINEAR;
		case 9:		// logarithmic, 100:1
		case 10:	// logarithmic, 316:1
			return TRANSFER_STEEP;
		case 16:
			return TRANSFER_PQ;
		case 18:	// ARIB STD-B67
			return TRANSFER_HLG;
		default:	// 2 unspecified, 0 and 3 reserved
			return TRANSFER_UNKNOWN;
	}
}

// ----------------------------------------------------------
//   The tone curve of an ICC profile
// ----------------------------------------------------------

static void
MuteLittleCMS(cmsContext, cmsUInt32Number, const char *) {
}

// the luminance that neutral black, mid grey and white get through the profile, measured as
// the exponent of the mid grey: 1 for linear light, about 2.2 for sRGB, 6.8 for PQ
static Transfer
TransferOfResponse(cmsContext context, cmsHPROFILE profile) {
	switch (cmsGetDeviceClass(profile)) {
		case cmsSigInputClass:
		case cmsSigDisplayClass:
		case cmsSigOutputClass:
		case cmsSigColorSpaceClass:
			break;
		default:
			return TRANSFER_UNKNOWN;
	}
	const cmsColorSpaceSignature space = cmsGetColorSpace(profile);
	if ((space != cmsSigRgbData) && (space != cmsSigGrayData)) {
		return TRANSFER_UNKNOWN;
	}
	const unsigned channels = (space == cmsSigRgbData) ? 3 : 1;

	cmsHPROFILE xyz = cmsCreateXYZProfileTHR(context);
	if (!xyz) {
		return TRANSFER_UNKNOWN;
	}
	cmsHTRANSFORM transform = cmsCreateTransformTHR(context, profile, (channels == 3) ? TYPE_RGB_DBL : TYPE_GRAY_DBL, xyz, TYPE_XYZ_DBL, INTENT_RELATIVE_COLORIMETRIC, cmsFLAGS_NOCACHE | cmsFLAGS_NOOPTIMIZE);
	cmsCloseProfile(xyz);
	if (!transform) {
		return TRANSFER_UNKNOWN;
	}
	static const double levels[3] = { 0, 0.5, 1 };
	double device[3 * 3];
	cmsCIEXYZ light[3];
	for (unsigned i = 0; i < 3; i++) {
		for (unsigned c = 0; c < channels; c++) {
			device[i * channels + c] = levels[i];
		}
	}
	cmsDoTransform(transform, device, light, 3);
	cmsDeleteTransform(transform);

	const double range = light[2].Y - light[0].Y;
	if (!(range > 1e-6)) {
		return TRANSFER_UNKNOWN;
	}
	const double mid = (light[1].Y - light[0].Y) / range;
	if (!(mid > 0) || !(mid < 1)) {
		return TRANSFER_UNKNOWN;
	}
	const double exponent = log(mid) / log(0.5);
	if (exponent < 0.8) {
		return TRANSFER_UNKNOWN;
	}
	if (exponent <= 1.2) {
		return TRANSFER_LINEAR;
	}
	return (exponent <= 3.2) ? TRANSFER_DISPLAY : TRANSFER_STEEP;
}

static Transfer
TransferOfProfile(const void *data, DWORD size) {
	Transfer transfer = TRANSFER_UNKNOWN;
	cmsContext context = cmsCreateContext(NULL, NULL);
	if (!context) {
		return transfer;
	}
	cmsSetLogErrorHandlerTHR(context, MuteLittleCMS);
	cmsHPROFILE profile = cmsOpenProfileFromMemTHR(context, data, size);
	if (profile) {
		const cmsVideoSignalType *cicp = (const cmsVideoSignalType *)cmsReadTag(profile, cmsSigcicpTag);
		if (cicp) {
			transfer = TransferOfCode(cicp->TransferCharacteristics);
		}
		if (transfer == TRANSFER_UNKNOWN) {
			transfer = TransferOfResponse(context, profile);
		}
		cmsCloseProfile(profile);
	}
	cmsDeleteContext(context);
	return transfer;
}

// the file's code points first, which PNG ranks above iCCP; then the ICC profile
static Transfer
TransferOf(FIBITMAP *dib) {
	BYTE cicp[4];
	if (GetCICPMetadata(dib, cicp)) {
		const Transfer transfer = TransferOfCode(cicp[1]);
		if (transfer != TRANSFER_UNKNOWN) {
			return transfer;
		}
	}
	const FIICCPROFILE *icc = FreeImage_GetICCProfile(dib);
	if (icc && icc->data && (icc->size >= 132) && ((icc->flags & FIICC_COLOR_IS_CMYK) == 0)) {
		return TransferOfProfile(icc->data, (DWORD)icc->size);
	}
	return TRANSFER_UNKNOWN;
}

// ----------------------------------------------------------
//   Pixel statistics
// ----------------------------------------------------------

static unsigned
SampleStep(unsigned width, unsigned height) {
	const double pixels = (double)width * (double)height;
	return (pixels <= SAMPLE_BUDGET) ? 1 : (unsigned)ceil(sqrt(pixels / SAMPLE_BUDGET));
}

// colors only: the alpha of an RGBA16 image is left out
static void
Scan16(FIBITMAP *dib, unsigned step, Samples16 &samples) {
	const unsigned width = FreeImage_GetWidth(dib);
	const unsigned height = FreeImage_GetHeight(dib);
	const unsigned words = FreeImage_GetBPP(dib) / 16;
	const unsigned colors = (words == 4) ? 3 : words;
	WORD brightest = 0;
	bool widened = true;
	for (unsigned y = 0; y < height; y += step) {
		const WORD *row = (const WORD *)FreeImage_GetScanLine(dib, y);
		for (unsigned x = 0; x < width; x += step) {
			const WORD *pixel = row + (size_t)x * words;
			for (unsigned c = 0; c < colors; c++) {
				const WORD value = pixel[c];
				const unsigned low = value & 0xFF;
				if (value > brightest) {
					brightest = value;
				}
				// FreeImage widens by shifting, other tools by multiplying by 257
				if ((low != 0) && (low != (unsigned)(value >> 8))) {
					widened = false;
				}
			}
		}
	}
	samples.brightest = brightest;
	samples.widened = widened;
}

static void
ScanFloat(FIBITMAP *dib, SamplesFloat &samples) {
	const unsigned width = FreeImage_GetWidth(dib);
	const unsigned height = FreeImage_GetHeight(dib);
	const unsigned step = SampleStep(width, height);
	samples.finite = samples.negative = samples.bright = 0;
	for (unsigned y = 0; y < height; y += step) {
		const float *row = (const float *)FreeImage_GetScanLine(dib, y);
		for (unsigned x = 0; x < width; x += step) {
			const float value = row[x];
			if (!IsFiniteValue(value)) {
				continue;
			}
			samples.finite++;
			if (value < 0) {
				samples.negative++;
			} else if (value > 1) {
				samples.bright++;
			}
		}
	}
}

// ----------------------------------------------------------
//   Verdicts
// ----------------------------------------------------------

static int
VerdictOf16(FIBITMAP *dib, SourceFormat &source) {
	// CMYK is converted, not tone mapped
	if (FreeImage_GetColorType(dib) == FIC_CMYK) {
		return FITM_NONE;
	}
	const Transfer transfer = TransferOf(dib);
	if (transfer == TRANSFER_PQ) {
		return FITM_PQ;
	}

	bool widened = false;
	if (FreeImage_HasPixels(dib)) {
		Samples16 samples;
		const unsigned step = SampleStep(FreeImage_GetWidth(dib), FreeImage_GetHeight(dib));
		Scan16(dib, step, samples);
		if ((step > 1) && (samples.brightest < LOW_RANGE_LIMIT)) {
			// the grid may have missed the few bright pixels
			Scan16(dib, 1, samples);
		}
		if (samples.brightest == 0) {
			return FITM_NONE;
		}
		if ((samples.brightest < LOW_RANGE_LIMIT) && !samples.widened) {
			return FITM_OPTIONAL;
		}
		widened = samples.widened;
	}

	switch (transfer) {
		case TRANSFER_LINEAR:
		case TRANSFER_STEEP:
			return FITM_OPTIONAL;
		case TRANSFER_DISPLAY:
		case TRANSFER_HLG:
			return FITM_NONE;
		default:
			break;
	}
	// LibRaw decodes camera RAW to linear samples; widened 8-bit ones are a preview
	if (!widened && (source.Get() == FIF_RAW)) {
		return FITM_OPTIONAL;
	}
	return FITM_NONE;
}

static int
VerdictOfFloat(FIBITMAP *dib, SourceFormat &source) {
	if (TransferOf(dib) == TRANSFER_PQ) {
		return FITM_PQ;
	}
	switch (source.Get()) {
		case FIF_HDR:
		case FIF_EXR:
		case FIF_PFM:
		case FIF_JXR:
		case FIF_PSD:
			// these store light
			return FITM_REQUIRED;
		default:
			break;
	}
	if (!FreeImage_HasPixels(dib)) {
		return FITM_OPTIONAL;
	}
	SamplesFloat samples;
	ScanFloat(dib, samples);
	if (samples.finite == 0) {
		return FITM_NONE;
	}
	// signed data, such as elevations: FreeImage_ConvertToStandardType() spreads it, the operators clip it
	if (samples.negative * 100 >= samples.finite) {
		return FITM_NONE;
	}
	// brighter than white in 1 sample of 10000: one hot pixel is not enough, a light in the scene is
	if (samples.bright * 10000 >= samples.finite) {
		return FITM_REQUIRED;
	}
	return FITM_OPTIONAL;
}

static int
MustTonemap(FIBITMAP *dib, SourceFormat &source) {
	if (!dib) {
		return FITM_ERROR;
	}
	if (IsUnscaled(dib)) {
		return FITM_UNSCALED;
	}
	switch (FreeImage_GetImageType(dib)) {
		case FIT_BITMAP:
			return FITM_NONE;
		case FIT_UINT16:
		case FIT_RGB16:
		case FIT_RGBA16:
			return VerdictOf16(dib, source);
		case FIT_FLOAT:
			return VerdictOfFloat(dib, source);
		case FIT_RGBF:
		case FIT_RGBAF:
			// light, which only the tone mapping operators turn into a standard bitmap
			return (TransferOf(dib) == TRANSFER_PQ) ? FITM_PQ : FITM_REQUIRED;
		case FIT_INT16:
		case FIT_UINT32:
		case FIT_INT32:
		case FIT_DOUBLE:
		case FIT_COMPLEX:
			// measurements: FreeImage_ConvertToStandardType() shows them, the operators refuse them
			return FITM_NONE;
		default:
			return FITM_ERROR;
	}
}

// ==========================================================
//   Public functions
// ==========================================================

/**
Tells whether an image needs tone mapping to be displayed. The verdict follows the pixel type, the
color type, the colors the file describes (the "CICP" tag of AVIF, HEIF, PNG and camera RAW images,
or the ICC profile's cicp tag and tone curve), the format of the file and, for 16-bit and grey float
images, statistics of a sample of the pixels. A header-only bitmap gets a verdict without statistics.
@param dib Image to look at
@param filename The file the image comes from, or NULL; read only for the formats of 16-bit and grey float images
@return Returns FITM_NONE (0), FITM_OPTIONAL (1), FITM_REQUIRED (2), FITM_PQ (3) or FITM_UNSCALED (4), and FITM_ERROR (-1) for a NULL or unknown bitmap
*/
int DLL_CALLCONV
FreeImage_MustTonemap(FIBITMAP *dib, const char *filename) {
	SourceFormat source(filename, NULL);
	return MustTonemap(dib, source);
}

/**
@see FreeImage_MustTonemap; the file name is not read where FreeImage_GetFileTypeU() does not read Unicode file names
*/
int DLL_CALLCONV
FreeImage_MustTonemapU(FIBITMAP *dib, const wchar_t *filename) {
	SourceFormat source(NULL, filename);
	return MustTonemap(dib, source);
}
