// ==========================================================
// AVIF Loader (libavif + dav1d), read-only
//
// This file is part of FreeImage 3
//
// COVERED CODE IS PROVIDED UNDER THIS LICENSE ON AN "AS IS" BASIS, WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, WITHOUT LIMITATION, WARRANTIES
// THAT THE COVERED CODE IS FREE OF DEFECTS, MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE
// OR NON-INFRINGING. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE COVERED
// CODE IS WITH YOU. SHOULD ANY COVERED CODE PROVE DEFECTIVE IN ANY RESPECT, YOU (NOT
// THE INITIAL DEVELOPER OR ANY OTHER CONTRIBUTOR) ASSUME THE COST OF ANY NECESSARY
// SERVICING, REPAIR OR CORRECTION. THIS DISCLAIMER OF WARRANTY CONSTITUTES AN ESSENTIAL
// PART OF THIS LICENSE. NO USE OF ANY COVERED CODE IS AUTHORIZED HEREUNDER EXCEPT UNDER
// THIS DISCLAIMER.
//
// Use at your own risk!
// ==========================================================
//
// Code generated by Marius Șucan with Anthropic Claude
// ==========================================================

#ifdef _WIN32
#include <windows.h>
#else
#include <unistd.h>
#endif

#include <limits.h>
#include <stdlib.h>
#include <string.h>

#include "FreeImage.h"
#include "Utilities.h"

#include "../Metadata/FreeImageTag.h"

#include "../LibAVIF/include/avif/avif.h"

// ==========================================================
// Plugin Interface
// ==========================================================

static int s_format_id;

// ----------------------------------------------------------
//   Threads
// ----------------------------------------------------------

#define FI_AVIF_MAX_THREADS 64

static int
GetProcessorCount() {
	int count = 1;
#ifdef _WIN32
	SYSTEM_INFO info;
	GetSystemInfo(&info);
	count = (int)info.dwNumberOfProcessors;
#elif defined(_SC_NPROCESSORS_ONLN)
	const long n = sysconf(_SC_NPROCESSORS_ONLN);
	if(n > 0) {
		count = (int)n;
	}
#endif
	if(count < 1) {
		count = 1;
	}
	if(count > FI_AVIF_MAX_THREADS) {
		count = FI_AVIF_MAX_THREADS;
	}
	return count;
}

// ----------------------------------------------------------
//   avifIO over FreeImageIO
// ----------------------------------------------------------

// seek_proc takes a long (32-bit on Win64); overridable for tests
#ifndef FI_AVIF_SEEK_STEP_MAX
#define FI_AVIF_SEEK_STEP_MAX LONG_MAX
#endif

// read_proc takes an unsigned size
#define FI_AVIF_READ_CHUNK 0x40000000u

typedef struct tagAVIFStream {
	avifIO io;
	FreeImageIO *fio;
	fi_handle handle;
	long base;				//! stream position of the first AVIF byte
	BOOL size_known;
	uint64_t size;			//! bytes from base to the end
	BYTE *buffer;
	size_t capacity;
} AVIFStream;

// seek to base + offset, in long-sized steps if needed
static BOOL
AVIF_SeekTo(AVIFStream *s, uint64_t offset) {
	const long span = (s->base <= FI_AVIF_SEEK_STEP_MAX) ? (FI_AVIF_SEEK_STEP_MAX - s->base) : 0;
	if(offset <= (uint64_t)span) {
		return (s->fio->seek_proc(s->handle, s->base + (long)offset, SEEK_SET) == 0) ? TRUE : FALSE;
	}
	if(s->fio->seek_proc(s->handle, s->base, SEEK_SET) != 0) {
		return FALSE;
	}
	uint64_t remaining = offset;
	while(remaining > 0) {
		const long step = (remaining > (uint64_t)FI_AVIF_SEEK_STEP_MAX) ? (long)FI_AVIF_SEEK_STEP_MAX : (long)remaining;
		if(s->fio->seek_proc(s->handle, step, SEEK_CUR) != 0) {
			return FALSE;
		}
		remaining -= (uint64_t)step;
	}
	return TRUE;
}

// avifIOReadFunc: past the end = error, at the end = empty, across = clipped
static avifResult
AVIF_ReadProc(avifIO *io, uint32_t readFlags, uint64_t offset, size_t size, avifROData *out) {
	AVIFStream *s = (AVIFStream*)io->data;

	if(readFlags != 0) {
		return AVIF_RESULT_IO_ERROR;
	}
	if(s->size_known) {
		if(offset > s->size) {
			return AVIF_RESULT_IO_ERROR;
		}
		if(size > s->size - offset) {
			size = (size_t)(s->size - offset);
		}
	}
	if(size == 0) {
		static const uint8_t empty = 0;
		out->data = &empty;
		out->size = 0;
		return AVIF_RESULT_OK;
	}
	if(size > s->capacity) {
		BYTE *buffer = (BYTE*)realloc(s->buffer, size);
		if(!buffer) {
			return AVIF_RESULT_OUT_OF_MEMORY;
		}
		s->buffer = buffer;
		s->capacity = size;
	}
	if(!AVIF_SeekTo(s, offset)) {
		return AVIF_RESULT_IO_ERROR;
	}

	size_t total = 0;
	while(total < size) {
		const size_t left = size - total;
		const unsigned chunk = (left > (size_t)FI_AVIF_READ_CHUNK) ? FI_AVIF_READ_CHUNK : (unsigned)left;
		const unsigned got = s->fio->read_proc(s->buffer + total, 1, chunk, s->handle);
		if(got == 0) {
			break;
		}
		total += got;
	}
	if((total < size) && s->size_known) {
		return AVIF_RESULT_IO_ERROR;
	}

	out->data = s->buffer;
	out->size = total;
	return AVIF_RESULT_OK;
}

// ----------------------------------------------------------
//   Decoder context
// ----------------------------------------------------------

typedef struct tagAVIFContext {
	AVIFStream stream;
	avifDecoder *decoder;
	int threads;
} AVIFContext;

typedef struct tagAVIFOutput {
	FREE_IMAGE_TYPE type;
	unsigned bpp;
	avifRGBFormat format;
	unsigned depth;			//! 8 or 16 bits per channel
} AVIFOutput;

static void
ReportError(const char *what, avifResult result, const avifDecoder *decoder) {
	const char *detail = decoder->diag.error;
	FreeImage_OutputMessageProc(s_format_id, "%s: %s%s%s", what, avifResultToString(result), detail[0] ? " - " : "", detail);
}

static void
ChooseOutput(const avifImage *image, BOOL has_alpha, BOOL allow_grey, BOOL playback, AVIFOutput *out) {
	if(playback) {
		// libavif fills a missing alpha with opaque
		out->depth = 8;
		out->type = FIT_BITMAP;
		out->bpp = 32;
#if FREEIMAGE_COLORORDER == FREEIMAGE_COLORORDER_BGR
		out->format = AVIF_RGB_FORMAT_BGRA;
#else
		out->format = AVIF_RGB_FORMAT_RGBA;
#endif
		return;
	}

	const BOOL deep = (image->depth > 8) ? TRUE : FALSE;
	const BOOL grey = (allow_grey && (image->yuvFormat == AVIF_PIXEL_FORMAT_YUV400) && !has_alpha) ? TRUE : FALSE;

	out->depth = deep ? 16 : 8;
	if(grey) {
		out->type = deep ? FIT_UINT16 : FIT_BITMAP;
		out->bpp = deep ? 16 : 8;
		out->format = AVIF_RGB_FORMAT_GRAY;
	} else if(deep) {
		// FIRGB16/FIRGBA16 are RGB order whatever FREEIMAGE_COLORORDER says
		out->type = has_alpha ? FIT_RGBA16 : FIT_RGB16;
		out->bpp = has_alpha ? 64 : 48;
		out->format = has_alpha ? AVIF_RGB_FORMAT_RGBA : AVIF_RGB_FORMAT_RGB;
	} else {
		out->type = FIT_BITMAP;
		out->bpp = has_alpha ? 32 : 24;
#if FREEIMAGE_COLORORDER == FREEIMAGE_COLORORDER_BGR
		out->format = has_alpha ? AVIF_RGB_FORMAT_BGRA : AVIF_RGB_FORMAT_BGR;
#else
		out->format = has_alpha ? AVIF_RGB_FORMAT_RGBA : AVIF_RGB_FORMAT_RGB;
#endif
	}
}

static FIBITMAP *
AllocateOutput(BOOL header_only, const AVIFOutput *out, unsigned width, unsigned height) {
	FIBITMAP *dib = NULL;

	if((width == 0) || (height == 0) || (width > (unsigned)INT_MAX) || (height > (unsigned)INT_MAX)) {
		FreeImage_OutputMessageProc(s_format_id, "Unsupported image size: %u x %u", width, height);
		return NULL;
	}
	if((out->type == FIT_BITMAP) && (out->bpp >= 24)) {
		dib = FreeImage_AllocateHeaderT(header_only, FIT_BITMAP, (int)width, (int)height, (int)out->bpp, FI_RGBA_RED_MASK, FI_RGBA_GREEN_MASK, FI_RGBA_BLUE_MASK);
	} else {
		dib = FreeImage_AllocateHeaderT(header_only, out->type, (int)width, (int)height, (int)out->bpp, 0, 0, 0);
	}
	if(!dib) {
		FreeImage_OutputMessageProc(s_format_id, FI_MSG_ERROR_DIB_MEMORY);
		return NULL;
	}
	if((out->type == FIT_BITMAP) && (out->bpp == 8)) {
		// greyscale ramp
		RGBQUAD *pal = FreeImage_GetPalette(dib);
		for(int i = 0; i < 256; i++) {
			pal[i].rgbRed = pal[i].rgbGreen = pal[i].rgbBlue = (BYTE)i;
			pal[i].rgbReserved = 0;
		}
	}
	return dib;
}

// ----------------------------------------------------------
//   Metadata
// ----------------------------------------------------------

static BOOL
SetAnimTag(FIBITMAP *dib, const char *key, WORD id, FREE_IMAGE_MDTYPE type, DWORD count, DWORD length, const void *value) {
	BOOL bResult = FALSE;
	FITAG *tag = FreeImage_CreateTag();
	if(tag) {
		FreeImage_SetTagKey(tag, key);
		FreeImage_SetTagID(tag, id);
		FreeImage_SetTagType(tag, type);
		FreeImage_SetTagCount(tag, count);
		FreeImage_SetTagLength(tag, length);
		FreeImage_SetTagValue(tag, value);
		TagLib& s = TagLib::instance();
		FreeImage_SetTagDescription(tag, s.getTagDescription(TagLib::ANIMATION, id));
		bResult = FreeImage_SetMetadata(FIMD_ANIMATION, dib, key, tag);
		FreeImage_DeleteTag(tag);
	}
	return bResult;
}

// many writers keep the "Exif\0\0" prefix, so search; size = not found
static size_t
FindTiffHeader(const BYTE *data, size_t size) {
	static const BYTE lsb_first[4] = { 0x49, 0x49, 0x2A, 0x00 };	// "II*\0"
	static const BYTE msb_first[4] = { 0x4D, 0x4D, 0x00, 0x2A };	// "MM\0*"
	for(size_t i = 0; i + 4 <= size; i++) {
		if((memcmp(data + i, lsb_first, 4) == 0) || (memcmp(data + i, msb_first, 4) == 0)) {
			return i;
		}
	}
	return size;
}

// known after parsing, so header-only loads get them too
static void
AttachMetadata(FIBITMAP *dib, const avifImage *image) {
	// ICC profile
	if((image->icc.size > 0) && image->icc.data && (image->icc.size <= (size_t)LONG_MAX)) {
		FreeImage_CreateICCProfile(dib, (void*)image->icc.data, (long)image->icc.size);
	}

	// Exif
	if((image->exif.size > 0) && image->exif.data && (image->exif.size <= (size_t)UINT_MAX)) {
		const BYTE *exif = image->exif.data;
		const size_t offset = FindTiffHeader(exif, image->exif.size);
		if(offset < image->exif.size) {
			const unsigned length = (unsigned)(image->exif.size - offset);
			psd_read_exif_profile_raw(dib, exif + offset, length);
			psd_read_exif_profile(dib, exif + offset, length);
		}
	}

	// XMP
	if((image->xmp.size > 0) && image->xmp.data && (image->xmp.size <= (size_t)UINT_MAX)) {
		FITAG *tag = FreeImage_CreateTag();
		if(tag) {
			FreeImage_SetTagKey(tag, g_TagLib_XMPFieldName);
			FreeImage_SetTagLength(tag, (DWORD)image->xmp.size);
			FreeImage_SetTagCount(tag, (DWORD)image->xmp.size);
			FreeImage_SetTagType(tag, FIDT_ASCII);
			FreeImage_SetTagValue(tag, image->xmp.data);
			FreeImage_SetMetadata(FIMD_XMP, dib, FreeImage_GetTagKey(tag), tag);
			FreeImage_DeleteTag(tag);
		}
	}
}

static LONG
FrameTimeMs(const avifImageTiming *timing) {
	if(timing->timescale == 0) {
		return 0;
	}
	const uint64_t scale = timing->timescale;
	const uint64_t whole = timing->durationInTimescales / scale;
	const uint64_t rem = timing->durationInTimescales % scale;
	const uint64_t ms = whole * 1000 + (rem * 1000 + scale / 2) / scale;
	return (ms > (uint64_t)LONG_MAX) ? LONG_MAX : (LONG)ms;
}

// dib is the finished page; an AVIF frame covers the whole canvas
static void
AttachAnimation(FIBITMAP *dib, avifDecoder *decoder, int page) {
	if(decoder->imageCount <= 1) {
		return;
	}

	avifImageTiming timing;
	if(avifDecoderNthImageTiming(decoder, (uint32_t)page, &timing) == AVIF_RESULT_OK) {
		const LONG frametime = FrameTimeMs(&timing);
		SetAnimTag(dib, "FrameTime", ANIMTAG_FRAMETIME, FIDT_LONG, 1, 4, &frametime);
	}

	const WORD left = 0;
	const WORD top = 0;
	const BYTE disposal = 1;
	const BYTE blend = 1;
	SetAnimTag(dib, "FrameLeft", ANIMTAG_FRAMELEFT, FIDT_SHORT, 1, 2, &left);
	SetAnimTag(dib, "FrameTop", ANIMTAG_FRAMETOP, FIDT_SHORT, 1, 2, &top);
	SetAnimTag(dib, "DisposalMethod", ANIMTAG_DISPOSALMETHOD, FIDT_BYTE, 1, 1, &disposal);
	SetAnimTag(dib, "BlendMethod", ANIMTAG_BLENDMETHOD, FIDT_BYTE, 1, 1, &blend);

	// on every frame, so deleting page 0 keeps them; SHORTs saturate
	const unsigned width = FreeImage_GetWidth(dib);
	const unsigned height = FreeImage_GetHeight(dib);
	const WORD logicalwidth = (WORD)((width > 0xFFFF) ? 0xFFFF : width);
	const WORD logicalheight = (WORD)((height > 0xFFFF) ? 0xFFFF : height);
	// libavif: n means n + 1 plays, negative = infinite or unknown
	const LONG loop = (decoder->repetitionCount < 0) ? 0 : (LONG)decoder->repetitionCount + 1;
	SetAnimTag(dib, "LogicalWidth", ANIMTAG_LOGICALWIDTH, FIDT_SHORT, 1, 2, &logicalwidth);
	SetAnimTag(dib, "LogicalHeight", ANIMTAG_LOGICALHEIGHT, FIDT_SHORT, 1, 2, &logicalheight);
	SetAnimTag(dib, "Loop", ANIMTAG_LOOP, FIDT_LONG, 1, 4, &loop);
}

// ----------------------------------------------------------
//   Transformative properties
// ----------------------------------------------------------

static BOOL
GetCleanAperture(const avifImage *image, avifDiagnostics *diag, avifCropRect *rect) {
	if(!(image->transformFlags & AVIF_TRANSFORM_CLAP)) {
		return FALSE;
	}
	if(!avifCropRectFromCleanApertureBox(rect, &image->clap, image->width, image->height, diag)) {
		FreeImage_OutputMessageProc(s_format_id, "Ignoring an invalid clean aperture ('clap') box");
		return FALSE;
	}
	if((rect->width == 0) || (rect->height == 0)) {
		return FALSE;
	}
	return TRUE;
}

// clap, irot, imir in that order (ISO/IEC 23000-22 7.3.6.7); consumes dib
static FIBITMAP *
ApplyTransforms(FIBITMAP *dib, const avifImage *image, avifDiagnostics *diag) {
	avifCropRect rect;

	// clap: pixels are RGB here, so a 4:4:4 crop
	if(GetCleanAperture(image, diag, &rect)) {
		if((rect.x != 0) || (rect.y != 0) || (rect.width != image->width) || (rect.height != image->height)) {
			FIBITMAP *cropped = FreeImage_Copy(dib, (int)rect.x, (int)rect.y, (int)(rect.x + rect.width), (int)(rect.y + rect.height));
			if(cropped) {
				FreeImage_Unload(dib);
				dib = cropped;
			} else {
				FreeImage_OutputMessageProc(s_format_id, "Could not apply the clean aperture (%u x %u at %u, %u)", rect.width, rect.height, rect.x, rect.y);
			}
		}
	}

	// irot: quarter turns anti-clockwise, like FreeImage_Rotate
	if(image->transformFlags & AVIF_TRANSFORM_IROT) {
		const int quarter_turns = image->irot.angle & 3;
		if(quarter_turns != 0) {
			FIBITMAP *rotated = FreeImage_Rotate(dib, 90.0 * quarter_turns, NULL);
			if(rotated) {
				FreeImage_Unload(dib);
				dib = rotated;
			} else {
				FreeImage_OutputMessageProc(s_format_id, "Could not apply the %d degree rotation ('irot')", 90 * quarter_turns);
			}
		}
	}

	// imir: axis 0 flips top/bottom, axis 1 left/right (23008-12 6.5.12)
	if(image->transformFlags & AVIF_TRANSFORM_IMIR) {
		if(image->imir.axis == 0) {
			FreeImage_FlipVertical(dib);
		} else {
			FreeImage_FlipHorizontal(dib);
		}
	}

	return dib;
}

// ==========================================================
// Plugin Implementation
// ==========================================================

static const char * DLL_CALLCONV
Format() {
	return "AVIF";
}

static const char * DLL_CALLCONV
Description() {
	return "AV1 Image File Format";
}

static const char * DLL_CALLCONV
Extension() {
	return "avif,avifs";
}

static const char * DLL_CALLCONV
RegExpr() {
	return NULL;
}

static const char * DLL_CALLCONV
MimeType() {
	return "image/avif";
}

static BOOL
ftypHasBrand(const BYTE *ftyp, unsigned size, const char *brand) {
	if(memcmp(ftyp + 8, brand, 4) == 0) {
		// major_brand
		return TRUE;
	}
	// compatible_brands[], after minor_version
	for(unsigned offset = 16; offset + 4 <= size; offset += 4) {
		if(memcmp(ftyp + offset, brand, 4) == 0) {
			return TRUE;
		}
	}
	return FALSE;
}

static BOOL DLL_CALLCONV
Validate(FreeImageIO *io, fi_handle handle) {
	BYTE buffer[4096];

	if(io->read_proc(buffer, 1, 8, handle) != 8) {
		return FALSE;
	}
	if(memcmp(buffer + 4, "ftyp", 4) != 0) {
		return FALSE;
	}
	const unsigned box_size = ((unsigned)buffer[0] << 24) | ((unsigned)buffer[1] << 16) | ((unsigned)buffer[2] << 8) | (unsigned)buffer[3];
	// 16 = box header + major brand + minor version
	if((box_size < 16) || (box_size > sizeof(buffer))) {
		return FALSE;
	}
	if(io->read_proc(buffer + 8, 1, box_size - 8, handle) != box_size - 8) {
		return FALSE;
	}
	avifROData data;
	data.data = buffer;
	data.size = box_size;
	if(!avifPeekCompatibleFileType(&data)) {
		return FALSE;
	}
	// 'mif3' only with minor_version 'avif': other codecs go to FIF_HEIF
	if(!ftypHasBrand(buffer, box_size, "avif") && !ftypHasBrand(buffer, box_size, "avis")) {
		if(memcmp(buffer + 12, "avif", 4) != 0) {
			return FALSE;
		}
	}
	return TRUE;
}

static BOOL DLL_CALLCONV
SupportsExportDepth(int depth) {
	return FALSE;
}

static BOOL DLL_CALLCONV
SupportsExportType(FREE_IMAGE_TYPE type) {
	return FALSE;
}

static BOOL DLL_CALLCONV
SupportsICCProfiles() {
	return TRUE;
}

static BOOL DLL_CALLCONV
SupportsNoPixels() {
	return TRUE;
}

// ----------------------------------------------------------

static void DLL_CALLCONV
Close(FreeImageIO *io, fi_handle handle, void *data) {
	AVIFContext *ctx = (AVIFContext*)data;
	if(ctx) {
		if(ctx->decoder) {
			avifDecoderDestroy(ctx->decoder);
		}
		free(ctx->stream.buffer);
		free(ctx);
	}
}

static void * DLL_CALLCONV
Open(FreeImageIO *io, fi_handle handle, BOOL read) {
	if(!read) {
		// this plugin cannot write
		return NULL;
	}

	AVIFContext *ctx = (AVIFContext*)calloc(1, sizeof(AVIFContext));
	if(!ctx) {
		FreeImage_OutputMessageProc(s_format_id, FI_MSG_ERROR_MEMORY);
		return NULL;
	}

	// --- the stream ---

	AVIFStream *s = &ctx->stream;
	s->fio = io;
	s->handle = handle;
	s->base = io->tell_proc(handle);
	if(s->base < 0) {
		s->base = 0;
	}
	// stream length, when tell_proc can express it (32-bit long on Win64)
	if(io->seek_proc(handle, 0, SEEK_END) == 0) {
		const long end = io->tell_proc(handle);
		if(end >= s->base) {
			s->size = (uint64_t)(end - s->base);
			s->size_known = TRUE;
		}
	}
	io->seek_proc(handle, s->base, SEEK_SET);

	s->io.read = AVIF_ReadProc;
	s->io.sizeHint = s->size_known ? s->size : 0;
	s->io.persistent = AVIF_FALSE;
	s->io.data = s;
	// io.destroy stays NULL: the decoder does not own the stream

	// --- the decoder ---

	ctx->threads = GetProcessorCount();
	ctx->decoder = avifDecoderCreate();
	if(!ctx->decoder) {
		FreeImage_OutputMessageProc(s_format_id, FI_MSG_ERROR_MEMORY);
		Close(io, handle, ctx);
		return NULL;
	}
	avifDecoder *decoder = ctx->decoder;
	decoder->maxThreads = ctx->threads;
	// lift libavif's 16384 x 16384 cap; allocation is the limit
	decoder->imageSizeLimit = UINT32_MAX;
	decoder->imageDimensionLimit = 0;
	// lenient: tolerate a missing pixi or alpha ispe, ignore an invalid clap
	decoder->strictFlags = AVIF_STRICT_DISABLED;
	avifDecoderSetIO(decoder, &s->io);

	avifResult result = avifDecoderParse(decoder);
	if(result == AVIF_RESULT_INVALID_EXIF_PAYLOAD) {
		// a broken Exif block should cost the metadata, not the image
		ReportError("Ignoring the Exif metadata", result, decoder);
		decoder->ignoreExif = AVIF_TRUE;
		result = avifDecoderParse(decoder);
	}
	if(result != AVIF_RESULT_OK) {
		ReportError("Cannot parse the file", result, decoder);
		Close(io, handle, ctx);
		return NULL;
	}

	return ctx;
}

static int DLL_CALLCONV
PageCount(FreeImageIO *io, fi_handle handle, void *data) {
	AVIFContext *ctx = (AVIFContext*)data;
	if(!ctx || !ctx->decoder) {
		return 0;
	}
	return (ctx->decoder->imageCount > 0) ? ctx->decoder->imageCount : 1;
}

static FIBITMAP *
LoadHeader(avifDecoder *decoder, int page, BOOL playback) {
	const avifImage *image = decoder->image;
	AVIFOutput out;
	avifCropRect rect;

	ChooseOutput(image, decoder->alphaPresent, TRUE, playback, &out);

	// size after clap, then after an odd number of quarter turns
	unsigned width = image->width;
	unsigned height = image->height;
	if(GetCleanAperture(image, &decoder->diag, &rect)) {
		width = rect.width;
		height = rect.height;
	}
	if((image->transformFlags & AVIF_TRANSFORM_IROT) && (image->irot.angle & 1)) {
		const unsigned t = width;
		width = height;
		height = t;
	}

	FIBITMAP *dib = AllocateOutput(TRUE, &out, width, height);
	if(dib) {
		AttachMetadata(dib, image);
		AttachAnimation(dib, decoder, page);
	}
	return dib;
}

static FIBITMAP *
LoadPixels(AVIFContext *ctx, int page, BOOL playback) {
	avifDecoder *decoder = ctx->decoder;
	AVIFOutput out;
	avifRGBImage rgb;

	avifResult result = avifDecoderNthImage(decoder, (uint32_t)page);
	if(result != AVIF_RESULT_OK) {
		ReportError("Cannot decode the image", result, decoder);
		return NULL;
	}
	const avifImage *image = decoder->image;
	const BOOL has_alpha = (image->alphaPlane != NULL) ? TRUE : FALSE;

	// greyscale first; RGB when libavif has no direct path
	BOOL allow_grey = TRUE;
	FIBITMAP *dib = NULL;
	for(;;) {
		ChooseOutput(image, has_alpha, allow_grey, playback, &out);
		dib = AllocateOutput(FALSE, &out, image->width, image->height);
		if(!dib) {
			return NULL;
		}

		avifRGBImageSetDefaults(&rgb, image);
		rgb.format = out.format;
		rgb.depth = out.depth;
		rgb.chromaUpsampling = AVIF_CHROMA_UPSAMPLING_BEST_QUALITY;
		// straight alpha: libavif un-premultiplies
		rgb.alphaPremultiplied = AVIF_FALSE;
		rgb.maxThreads = ctx->threads;
		rgb.pixels = FreeImage_GetBits(dib);
		rgb.rowBytes = FreeImage_GetPitch(dib);

		result = avifImageYUVToRGB(image, &rgb);
		if(result == AVIF_RESULT_OK) {
			break;
		}
		FreeImage_Unload(dib);
		dib = NULL;
		if((result == AVIF_RESULT_NOT_IMPLEMENTED) && (out.format == AVIF_RGB_FORMAT_GRAY)) {
			allow_grey = FALSE;
			continue;
		}
		ReportError("Cannot convert the image to RGB", result, decoder);
		return NULL;
	}

	// libavif rows are top-down
	FreeImage_FlipVertical(dib);

	dib = ApplyTransforms(dib, image, &decoder->diag);

	AttachMetadata(dib, image);
	AttachAnimation(dib, decoder, page);

	return dib;
}

static FIBITMAP * DLL_CALLCONV
Load(FreeImageIO *io, fi_handle handle, int page, int flags, void *data) {
	AVIFContext *ctx = (AVIFContext*)data;
	if(!ctx || !ctx->decoder) {
		return NULL;
	}
	if(page < 0) {
		page = 0;
	}
	if(page >= ctx->decoder->imageCount) {
		FreeImage_OutputMessageProc(s_format_id, "Page %d does not exist: the file has %d image(s)", page, ctx->decoder->imageCount);
		return NULL;
	}

	const BOOL header_only = ((flags & FIF_LOAD_NOPIXELS) == FIF_LOAD_NOPIXELS) ? TRUE : FALSE;
	const BOOL playback = ((ctx->decoder->imageCount > 1) && ((flags & AVIF_PLAYBACK) == AVIF_PLAYBACK)) ? TRUE : FALSE;
	if(header_only) {
		return LoadHeader(ctx->decoder, page, playback);
	}
	return LoadPixels(ctx, page, playback);
}

// ==========================================================
//	 Init
// ==========================================================

void DLL_CALLCONV
InitAVIF(Plugin *plugin, int format_id) {
	s_format_id = format_id;

	plugin->format_proc = Format;
	plugin->description_proc = Description;
	plugin->extension_proc = Extension;
	plugin->regexpr_proc = RegExpr;
	plugin->open_proc = Open;
	plugin->close_proc = Close;
	plugin->pagecount_proc = PageCount;
	plugin->pagecapability_proc = NULL;
	plugin->load_proc = Load;
	plugin->save_proc = NULL;
	plugin->validate_proc = Validate;
	plugin->mime_proc = MimeType;
	plugin->supports_export_bpp_proc = SupportsExportDepth;
	plugin->supports_export_type_proc = SupportsExportType;
	plugin->supports_icc_profiles_proc = SupportsICCProfiles;
	plugin->supports_no_pixels_proc = SupportsNoPixels;
}
