// ==========================================================
// HEIF Loader (libheif + libde265)
//
// This file is part of FreeImage 3
//
// COVERED CODE IS PROVIDED UNDER THIS LICENSE ON AN "AS IS" BASIS, WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, WITHOUT LIMITATION, WARRANTIES
// THAT THE COVERED CODE IS FREE OF DEFECTS, MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE
// OR NON-INFRINGING. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE COVERED
// CODE IS WITH YOU. SHOULD ANY COVERED CODE PROVE DEFECTIVE IN ANY RESPECT, YOU (NOT
// THE INITIAL DEVELOPER OR ANY OTHER CONTRIBUTOR) ASSUME THE COST OF ANY NECESSARY
// SERVICING, REPAIR OR CORRECTION. THIS DISCLAIMER OF WARRANTY CONSTITUTES AN ESSENTIAL
// PART OF THIS LICENSE. NO USE OF ANY COVERED CODE IS AUTHORIZED HEREUNDER EXCEPT UNDER
// THIS DISCLAIMER.
//
// Use at your own risk!
// ==========================================================
//
// Read-only. Pages: the top-level images (primary first) or a sequence's frames.
//
// Code generated by Marius Șucan with Anthropic Claude
// ==========================================================

#ifdef _WIN32
#include <windows.h>
#else
#include <unistd.h>
#endif

#include <limits.h>
#include <stdlib.h>
#include <string.h>

#include <algorithm>

#include "FreeImage.h"
#include "Utilities.h"

#include "../Metadata/FreeImageTag.h"

#ifndef LIBHEIF_STATIC_BUILD
#define LIBHEIF_STATIC_BUILD
#endif
#include <libheif/heif.h>
#include <libheif/heif_sequences.h>

// ==========================================================
// Plugin Interface
// ==========================================================

static int s_format_id;

// ----------------------------------------------------------
//   Threads
// ----------------------------------------------------------

#define FI_HEIF_MAX_THREADS 64

static int
GetProcessorCount() {
	int count = 1;
#ifdef _WIN32
	SYSTEM_INFO info;
	GetSystemInfo(&info);
	count = (int)info.dwNumberOfProcessors;
#elif defined(_SC_NPROCESSORS_ONLN)
	const long n = sysconf(_SC_NPROCESSORS_ONLN);
	if(n > 0) {
		count = (int)n;
	}
#endif
	if(count < 1) {
		count = 1;
	}
	if(count > FI_HEIF_MAX_THREADS) {
		count = FI_HEIF_MAX_THREADS;
	}
	return count;
}

// ----------------------------------------------------------
//   heif_reader over FreeImageIO
// ----------------------------------------------------------

typedef struct tagHEIFStream {
	FreeImageIO *io;
	fi_handle handle;
	INT64 base;				//! stream offset of the first HEIF byte
	uint64_t position;		//! relative to 'base'
	BOOL size_known;
	uint64_t size;			//! bytes from 'base' to the end
	uint64_t budget;		//! read cap in bytes, 0 = none
	uint64_t spent;
	BOOL overspent;
} HEIFStream;

/** seek to base + offset */
static BOOL
HEIF_SeekTo(HEIFStream *s, uint64_t offset) {
	if(offset > (uint64_t)(INT64_MAX - s->base)) {
		return FALSE;
	}
	return (s->io->seek_proc(s->handle, s->base + (INT64)offset, SEEK_SET) == 0) ? TRUE : FALSE;
}

/** is there a byte at 'offset'? Leaves the position undefined */
static BOOL
HEIF_Probe(HEIFStream *s, uint64_t offset) {
	BYTE b;
	return (HEIF_SeekTo(s, offset) && (s->io->read_proc(&b, 1, 1, s->handle) == 1)) ? TRUE : FALSE;
}

/** the length of a stream that SEEK_END cannot tell: doubling probes, then bisection */
static void
HEIF_MeasureStream(HEIFStream *s) {
	uint64_t lo = 0;	// a byte exists at 'lo'
	uint64_t hi = 1;	// no byte exists at 'hi', once the doubling stops

	if(!HEIF_Probe(s, 0)) {
		s->size = 0;
		s->size_known = TRUE;
		return;
	}
	while(HEIF_Probe(s, hi)) {
		if(hi > ((uint64_t)INT64_MAX >> 1)) {
			return;
		}
		lo = hi;
		hi <<= 1;
	}
	while(hi - lo > 1) {
		const uint64_t mid = lo + (hi - lo) / 2;
		if(HEIF_Probe(s, mid)) {
			lo = mid;
		} else {
			hi = mid;
		}
	}
	s->size = hi;
	s->size_known = TRUE;
}

/** libheif callback: tracked position */
static int64_t
HEIF_GetPosition(void *userdata) {
	HEIFStream *s = (HEIFStream*)userdata;
	return (s->position <= (uint64_t)INT64_MAX) ? (int64_t)s->position : INT64_MAX;
}

/** libheif callback: read exactly 'size' bytes, 0 on success */
static int
HEIF_Read(void *data, size_t size, void *userdata) {
	HEIFStream *s = (HEIFStream*)userdata;
	if(s->budget) {
		if((s->spent > s->budget) || ((uint64_t)size > s->budget - s->spent)) {
			s->overspent = TRUE;
			return -1;
		}
		s->spent += size;
	}
	const size_t total = FreeImage_ReadBytes(s->io, s->handle, data, size);
	s->position += total;
	return (total == size) ? 0 : -1;
}

/** libheif callback: absolute seek, 0 on success */
static int
HEIF_Seek(int64_t position, void *userdata) {
	HEIFStream *s = (HEIFStream*)userdata;
	if(position < 0) {
		return -1;
	}
	if(!HEIF_SeekTo(s, (uint64_t)position)) {
		return -1;
	}
	s->position = (uint64_t)position;
	return 0;
}

/** libheif callback: must be exact, libheif bisects the length with it */
static heif_reader_grow_status
HEIF_WaitForFileSize(int64_t target_size, void *userdata) {
	HEIFStream *s = (HEIFStream*)userdata;
	if(target_size < 0) {
		return heif_reader_grow_status_size_beyond_eof;
	}
	if(!s->size_known) {
		// unknown length: optimistic, a read past the end fails anyway
		return heif_reader_grow_status_size_reached;
	}
	return ((uint64_t)target_size <= s->size) ? heif_reader_grow_status_size_reached : heif_reader_grow_status_size_beyond_eof;
}

static const heif_reader s_reader = {
	1,						// reader_api_version
	HEIF_GetPosition,
	HEIF_Read,
	HEIF_Seek,
	HEIF_WaitForFileSize,
	NULL,					// request_range
	NULL,					// preload_range_hint
	NULL,					// release_file_range
	NULL					// release_error_msg
};

// ----------------------------------------------------------
//   Decoder context (the 'data' of Open/Load/Close)
// ----------------------------------------------------------

typedef struct tagHEIFOutput {
	FREE_IMAGE_TYPE type;
	unsigned bpp;
	BOOL grey;				//! a single greyscale plane (heif_channel_Y)
	BOOL has_alpha;
	heif_colorspace colorspace;
	heif_chroma chroma;
} HEIFOutput;

typedef struct tagHEIFSequence {
	uint32_t track_id;
	int frames;
	uint32_t *durations;	//! per frame, in 'timescale' ticks, display order
	uint32_t timescale;		//! ticks per second
	LONG loop;				//! plays, 0 = forever
	int width;				//! from the sample entry
	int height;
	BOOL has_alpha;
	int bits;				//! luma depth from 'hvcC', 0 if not HEVC
	BOOL mono;				//! 'hvcC' says 4:0:0
	BOOL no_grey;			//! greyscale decode failed: use colour
	BYTE *icc;
	size_t icc_size;
	// the decoder
	heif_track *track;		//! NULL until needed, or after a failure
	BOOL dirty;				//! decoded from: going back needs a fresh parse
	int next;
	heif_image *image;		//! last frame, kept for a repeat request
	int image_page;			//! -1 = none
	HEIFOutput image_out;
} HEIFSequence;

typedef struct tagHEIFContext {
	HEIFStream stream;
	heif_context *ctx;
	int threads;
	int page_count;			//! top-level images or frames
	heif_item_id *pages;	//! item IDs, primary first
	BOOL frames;			//! pages are the frames of 'seq'
	HEIFSequence seq;
} HEIFContext;

static void
ReportError(const char *what, const heif_error &error) {
	FreeImage_OutputMessageProc(s_format_id, "%s: %s", what, error.message ? error.message : "unknown error");
}

static void
SetOutput(BOOL grey, BOOL deep, BOOL has_alpha, HEIFOutput *out) {
	out->grey = grey;
	out->has_alpha = has_alpha;
	if(grey) {
		out->type = deep ? FIT_UINT16 : FIT_BITMAP;
		out->bpp = deep ? 16 : 8;
		out->colorspace = heif_colorspace_monochrome;
		out->chroma = heif_chroma_monochrome;
	} else if(deep) {
		// FIRGB16 is RGB order regardless of FREEIMAGE_COLORORDER; host byte order
		out->type = has_alpha ? FIT_RGBA16 : FIT_RGB16;
		out->bpp = has_alpha ? 64 : 48;
		out->colorspace = heif_colorspace_RGB;
#ifdef FREEIMAGE_BIGENDIAN
		out->chroma = has_alpha ? heif_chroma_interleaved_RRGGBBAA_BE : heif_chroma_interleaved_RRGGBB_BE;
#else
		out->chroma = has_alpha ? heif_chroma_interleaved_RRGGBBAA_LE : heif_chroma_interleaved_RRGGBB_LE;
#endif
	} else {
		out->type = FIT_BITMAP;
		out->bpp = has_alpha ? 32 : 24;
		out->colorspace = heif_colorspace_RGB;
		out->chroma = has_alpha ? heif_chroma_interleaved_RGBA : heif_chroma_interleaved_RGB;
	}
}

static void
ChooseOutput(const heif_image_handle *handle, BOOL allow_grey, HEIFOutput *out) {
	const BOOL has_alpha = heif_image_handle_has_alpha_channel(handle) ? TRUE : FALSE;
	int bits = heif_image_handle_get_luma_bits_per_pixel(handle);
	if(bits <= 0) {
		// unknown until decoded: assume 8
		bits = 8;
	}
	const BOOL deep = (bits > 8) ? TRUE : FALSE;

	heif_colorspace colorspace = heif_colorspace_undefined;
	heif_chroma chroma = heif_chroma_undefined;
	heif_image_handle_get_preferred_decoding_colorspace(handle, &colorspace, &chroma);
	const BOOL grey = (allow_grey && (colorspace == heif_colorspace_monochrome) && !has_alpha) ? TRUE : FALSE;

	SetOutput(grey, deep, has_alpha, out);
}

static void
ChooseFrameOutput(const HEIFSequence *seq, BOOL playback, HEIFOutput *out) {
	if(playback) {
		// 32-bit RGBA; libheif converts to 8 bits and adds opaque alpha
		out->grey = FALSE;
		out->has_alpha = TRUE;
		out->type = FIT_BITMAP;
		out->bpp = 32;
		out->colorspace = heif_colorspace_RGB;
		out->chroma = heif_chroma_interleaved_RGBA;
		return;
	}
	const BOOL grey = (seq->mono && !seq->has_alpha && !seq->no_grey) ? TRUE : FALSE;
	SetOutput(grey, (seq->bits > 8) ? TRUE : FALSE, seq->has_alpha, out);
}

static FIBITMAP *
AllocateOutput(BOOL header_only, const HEIFOutput *out, int width, int height) {
	FIBITMAP *dib = NULL;

	if((width <= 0) || (height <= 0)) {
		FreeImage_OutputMessageProc(s_format_id, "Unsupported image size: %d x %d", width, height);
		return NULL;
	}
	if((out->type == FIT_BITMAP) && (out->bpp >= 24)) {
		dib = FreeImage_AllocateHeaderT(header_only, FIT_BITMAP, width, height, (int)out->bpp, FI_RGBA_RED_MASK, FI_RGBA_GREEN_MASK, FI_RGBA_BLUE_MASK);
	} else {
		dib = FreeImage_AllocateHeaderT(header_only, out->type, width, height, (int)out->bpp, 0, 0, 0);
	}
	if(!dib) {
		FreeImage_OutputMessageProc(s_format_id, FI_MSG_ERROR_DIB_MEMORY);
		return NULL;
	}
	if((out->type == FIT_BITMAP) && (out->bpp == 8)) {
		// greyscale ramp
		RGBQUAD *pal = FreeImage_GetPalette(dib);
		for(int i = 0; i < 256; i++) {
			pal[i].rgbRed = pal[i].rgbGreen = pal[i].rgbBlue = (BYTE)i;
			pal[i].rgbReserved = 0;
		}
	}
	return dib;
}

/** 'handle' is NULL for sequence frames; its tiling decides the threading */
static heif_decoding_options *
CreateDecodingOptions(const HEIFContext *ctx, const heif_image_handle *handle) {
	heif_decoding_options *options = heif_decoding_options_alloc();
	if(!options) {
		return NULL;
	}
	// libheif applies clap, irot and imir
	options->ignore_transformations = 0;
	// keep 10- and 12-bit content
	options->convert_hdr_to_8bit = 0;
	// lenient: rule-bending files decode with warnings
	options->strict_decoding = 0;
	// tiled image: one tile per thread; single picture: codec threads
	heif_image_tiling tiling;
	uint64_t tiles = 1;
	if(handle && (heif_image_handle_get_image_tiling(handle, 1, &tiling).code == heif_error_Ok)) {
		tiles = (uint64_t)tiling.num_columns * tiling.num_rows;
	}
	options->num_codec_threads = (tiles > 1) ? 1 : ctx->threads;
	// every sample once; the edit list's repeats become "Loop"
	options->ignore_sequence_editlist = 1;
	// no colour conversion: HDR stays as encoded
	options->output_image_nclx_profile_passthrough = 1;
	// known encoder quirks (e.g. Sony HIF 'colr')
	options->autocorrect_broken_input = 1;
	return options;
}

// ----------------------------------------------------------
//   Pixel copies (libheif rows are top-down, FreeImage rows bottom-up)
// ----------------------------------------------------------

static void
UnpremultiplyRow8(BYTE *row, int width) {
	for(int x = 0; x < width; x++, row += 4) {
		const unsigned a = row[FI_RGBA_ALPHA];
		if((a > 0) && (a < 255)) {
			for(int c = 0; c < 3; c++) {
				const unsigned v = ((unsigned)row[c] * 255u + a / 2) / a;
				row[c] = (v > 255) ? 255 : (BYTE)v;
			}
		}
	}
}

static void
UnpremultiplyRow16(WORD *row, int width) {
	for(int x = 0; x < width; x++, row += 4) {
		const uint64_t a = row[3];
		if((a > 0) && (a < 65535)) {
			for(int c = 0; c < 3; c++) {
				const uint64_t v = ((uint64_t)row[c] * 65535u + a / 2) / a;
				row[c] = (v > 65535) ? 65535 : (WORD)v;
			}
		}
	}
}

static WORD *
CreateScaleTable(int bits) {
	if((bits < 1) || (bits > 16)) {
		return NULL;
	}
	const unsigned entries = 1u << bits;
	const unsigned max = entries - 1;
	WORD *table = (WORD*)malloc(entries * sizeof(WORD));
	if(!table) {
		return NULL;
	}
	for(unsigned v = 0; v < entries; v++) {
		table[v] = (WORD)((v * 65535u + max / 2) / max);
	}
	return table;
}

static BOOL
CopyInterleaved8(const heif_image *image, FIBITMAP *dib, BOOL has_alpha, BOOL premultiplied) {
	size_t stride = 0;
	const BYTE *plane = heif_image_get_plane_readonly2(image, heif_channel_interleaved, &stride);
	if(!plane) {
		return FALSE;
	}
	const int width = (int)FreeImage_GetWidth(dib);
	const int height = (int)FreeImage_GetHeight(dib);
	const int samples = has_alpha ? 4 : 3;
	const unsigned bytespp = FreeImage_GetBPP(dib) / 8;
	if(stride < (size_t)width * samples) {
		return FALSE;
	}
	for(int y = 0; y < height; y++) {
		const BYTE *src = plane + (size_t)y * stride;
		BYTE *dst = FreeImage_GetScanLine(dib, height - 1 - y);
		for(int x = 0; x < width; x++) {
			dst[FI_RGBA_RED] = src[0];
			dst[FI_RGBA_GREEN] = src[1];
			dst[FI_RGBA_BLUE] = src[2];
			if(has_alpha) {
				dst[FI_RGBA_ALPHA] = src[3];
			}
			src += samples;
			dst += bytespp;
		}
		if(has_alpha && premultiplied) {
			UnpremultiplyRow8(FreeImage_GetScanLine(dib, height - 1 - y), width);
		}
	}
	return TRUE;
}

static BOOL
CopyInterleaved16(const heif_image *image, FIBITMAP *dib, BOOL has_alpha, BOOL premultiplied, int bits) {
	size_t stride = 0;
	const BYTE *plane = heif_image_get_plane_readonly2(image, heif_channel_interleaved, &stride);
	if(!plane) {
		return FALSE;
	}
	const int width = (int)FreeImage_GetWidth(dib);
	const int height = (int)FreeImage_GetHeight(dib);
	const int samples = has_alpha ? 4 : 3;
	if(stride < (size_t)width * samples * 2) {
		return FALSE;
	}
	WORD *table = CreateScaleTable(bits);
	if(!table) {
		return FALSE;
	}
	const unsigned mask = (1u << bits) - 1;
	for(int y = 0; y < height; y++) {
		const WORD *src = (const WORD*)(plane + (size_t)y * stride);
		WORD *dst = (WORD*)FreeImage_GetScanLine(dib, height - 1 - y);
		const int n = width * samples;
		for(int i = 0; i < n; i++) {
			dst[i] = table[src[i] & mask];
		}
		if(has_alpha && premultiplied) {
			UnpremultiplyRow16(dst, width);
		}
	}
	free(table);
	return TRUE;
}

/** storage_bits: 8 or 16 per sample; bits: how many carry the value */
static BOOL
CopyGrey(const heif_image *image, FIBITMAP *dib, int storage_bits, int bits) {
	size_t stride = 0;
	const BYTE *plane = heif_image_get_plane_readonly2(image, heif_channel_Y, &stride);
	if(!plane) {
		return FALSE;
	}
	const int width = (int)FreeImage_GetWidth(dib);
	const int height = (int)FreeImage_GetHeight(dib);
	if(storage_bits == 8) {
		if(stride < (size_t)width) {
			return FALSE;
		}
		for(int y = 0; y < height; y++) {
			memcpy(FreeImage_GetScanLine(dib, height - 1 - y), plane + (size_t)y * stride, (size_t)width);
		}
		return TRUE;
	}
	if(stride < (size_t)width * 2) {
		return FALSE;
	}
	WORD *table = CreateScaleTable(bits);
	if(!table) {
		return FALSE;
	}
	const unsigned mask = (1u << bits) - 1;
	for(int y = 0; y < height; y++) {
		const WORD *src = (const WORD*)(plane + (size_t)y * stride);
		WORD *dst = (WORD*)FreeImage_GetScanLine(dib, height - 1 - y);
		for(int x = 0; x < width; x++) {
			dst[x] = table[src[x] & mask];
		}
	}
	free(table);
	return TRUE;
}

/** 'out' follows the pixels' depth; max_width/height > 0 crop from the top left */
static FIBITMAP *
ImageToBitmap(const heif_image *image, HEIFOutput *out, BOOL premultiplied, int max_width, int max_height) {
	const heif_channel channel = out->grey ? heif_channel_Y : heif_channel_interleaved;
	int width = heif_image_get_width(image, channel);
	int height = heif_image_get_height(image, channel);
	const int storage = heif_image_get_bits_per_pixel(image, channel);		// bits stored per pixel
	int bits = heif_image_get_bits_per_pixel_range(image, channel);			// bits carrying the value, per sample
	const int samples = out->grey ? 1 : (out->has_alpha ? 4 : 3);
	const BOOL deep = (storage > samples * 8) ? TRUE : FALSE;
	if((bits <= 0) || (bits > 16)) {
		bits = deep ? 16 : 8;
	}
	if(!deep) {
		bits = 8;
	}
	if(deep != ((out->type == FIT_BITMAP) ? FALSE : TRUE)) {
		// guessed depth was wrong: follow the pixels
		out->type = out->grey ? (deep ? FIT_UINT16 : FIT_BITMAP) : (deep ? (out->has_alpha ? FIT_RGBA16 : FIT_RGB16) : FIT_BITMAP);
		out->bpp = out->grey ? (deep ? 16 : 8) : (deep ? (out->has_alpha ? 64 : 48) : (out->has_alpha ? 32 : 24));
	}
	if((max_width > 0) && (width > max_width)) {
		width = max_width;
	}
	if((max_height > 0) && (height > max_height)) {
		height = max_height;
	}

	FIBITMAP *dib = AllocateOutput(FALSE, out, width, height);
	if(dib) {
		BOOL ok;
		if(out->grey) {
			ok = CopyGrey(image, dib, deep ? 16 : 8, bits);
		} else if(deep) {
			ok = CopyInterleaved16(image, dib, out->has_alpha, premultiplied, bits);
		} else {
			ok = CopyInterleaved8(image, dib, out->has_alpha, premultiplied);
		}
		if(!ok) {
			FreeImage_OutputMessageProc(s_format_id, "Cannot read the decoded image (%d x %d, %d bits per pixel)", width, height, storage);
			FreeImage_Unload(dib);
			dib = NULL;
		}
	}
	return dib;
}

// ----------------------------------------------------------
//   Metadata
// ----------------------------------------------------------

/** searches for the TIFF header: writers get the A.2.1 offset wrong */
static size_t
FindTiffHeader(const BYTE *data, size_t size) {
	static const BYTE lsb_first[4] = { 0x49, 0x49, 0x2A, 0x00 };	// "II*\0"
	static const BYTE msb_first[4] = { 0x4D, 0x4D, 0x00, 0x2A };	// "MM\0*"
	for(size_t i = 0; i + 4 <= size; i++) {
		if((memcmp(data + i, lsb_first, 4) == 0) || (memcmp(data + i, msb_first, 4) == 0)) {
			return i;
		}
	}
	return size;
}

/** raw block with the "Exif\0\0" prefix, plus the decoded tags */
static void
AttachExif(FIBITMAP *dib, const heif_image_handle *handle) {
	heif_item_id id;
	if(heif_image_handle_get_list_of_metadata_block_IDs(handle, "Exif", &id, 1) != 1) {
		return;
	}
	const size_t size = heif_image_handle_get_metadata_size(handle, id);
	// at least a TIFF header
	if((size <= 8) || (size > (size_t)UINT_MAX)) {
		return;
	}
	BYTE *data = (BYTE*)malloc(size);
	if(!data) {
		return;
	}
	const heif_error error = heif_image_handle_get_metadata(handle, id, data);
	if(error.code == heif_error_Ok) {
		// ISO/IEC 23008-12 A.2.1 offset; 'mini' blocks may lack it
		const uint32_t offset = ((uint32_t)data[0] << 24) | ((uint32_t)data[1] << 16) | ((uint32_t)data[2] << 8) | (uint32_t)data[3];
		size_t start = 0;
		if(offset < size - 4) {
			start = 4 + offset;
		}
		const size_t tiff = start + FindTiffHeader(data + start, size - start);
		if(tiff < size) {
			const unsigned length = (unsigned)(size - tiff);
			psd_read_exif_profile_raw(dib, data + tiff, length);
			psd_read_exif_profile(dib, data + tiff, length);
		}
	} else {
		ReportError("Ignoring the Exif metadata", error);
	}
	free(data);
}

static void
AttachXMP(FIBITMAP *dib, const heif_image_handle *handle) {
	const int count = heif_image_handle_get_number_of_metadata_blocks(handle, "mime");
	if(count <= 0) {
		return;
	}
	heif_item_id *ids = (heif_item_id*)calloc((size_t)count, sizeof(heif_item_id));
	if(!ids) {
		return;
	}
	const int n = heif_image_handle_get_list_of_metadata_block_IDs(handle, "mime", ids, count);
	for(int i = 0; i < n; i++) {
		const char *content_type = heif_image_handle_get_metadata_content_type(handle, ids[i]);
		if(!content_type || (strcmp(content_type, "application/rdf+xml") != 0)) {
			continue;
		}
		const size_t size = heif_image_handle_get_metadata_size(handle, ids[i]);
		if((size == 0) || (size > (size_t)UINT_MAX)) {
			continue;
		}
		BYTE *data = (BYTE*)malloc(size);
		if(!data) {
			break;
		}
		if(heif_image_handle_get_metadata(handle, ids[i], data).code == heif_error_Ok) {
			FITAG *tag = FreeImage_CreateTag();
			if(tag) {
				FreeImage_SetTagKey(tag, g_TagLib_XMPFieldName);
				FreeImage_SetTagLength(tag, (DWORD)size);
				FreeImage_SetTagCount(tag, (DWORD)size);
				FreeImage_SetTagType(tag, FIDT_ASCII);
				FreeImage_SetTagValue(tag, data);
				FreeImage_SetMetadata(FIMD_XMP, dib, FreeImage_GetTagKey(tag), tag);
				FreeImage_DeleteTag(tag);
			}
		}
		free(data);
		break;
	}
	free(ids);
}

static void
AttachICCProfile(FIBITMAP *dib, const heif_image_handle *handle) {
	const heif_color_profile_type type = heif_image_handle_get_color_profile_type(handle);
	if((type != heif_color_profile_type_rICC) && (type != heif_color_profile_type_prof)) {
		return;
	}
	const size_t size = heif_image_handle_get_raw_color_profile_size(handle);
	if((size == 0) || (size > (size_t)LONG_MAX)) {
		return;
	}
	BYTE *profile = (BYTE*)malloc(size);
	if(!profile) {
		return;
	}
	if(heif_image_handle_get_raw_color_profile(handle, profile).code == heif_error_Ok) {
		FreeImage_CreateICCProfile(dib, profile, (long)size);
	}
	free(profile);
}

static void
AttachMetadata(FIBITMAP *dib, const heif_image_handle *handle) {
	AttachICCProfile(dib, handle);
	AttachExif(dib, handle);
	AttachXMP(dib, handle);
}

static BOOL
SetAnimTag(FIBITMAP *dib, const char *key, WORD id, FREE_IMAGE_MDTYPE type, DWORD count, DWORD length, const void *value) {
	BOOL bResult = FALSE;
	FITAG *tag = FreeImage_CreateTag();
	if(tag) {
		FreeImage_SetTagKey(tag, key);
		FreeImage_SetTagID(tag, id);
		FreeImage_SetTagType(tag, type);
		FreeImage_SetTagCount(tag, count);
		FreeImage_SetTagLength(tag, length);
		FreeImage_SetTagValue(tag, value);
		TagLib& s = TagLib::instance();
		FreeImage_SetTagDescription(tag, s.getTagDescription(TagLib::ANIMATION, id));
		bResult = FreeImage_SetMetadata(FIMD_ANIMATION, dib, key, tag);
		FreeImage_DeleteTag(tag);
	}
	return bResult;
}

static LONG
FrameTimeMs(uint32_t ticks, uint32_t timescale) {
	if(timescale == 0) {
		return 0;
	}
	const uint64_t scale = timescale;
	const uint64_t ms = ((uint64_t)ticks / scale) * 1000 + (((uint64_t)ticks % scale) * 1000 + scale / 2) / scale;
	return (ms > 0x7FFFFFFF) ? (LONG)0x7FFFFFFF : (LONG)ms;
}

/** 'dib' must be the finished page: the canvas is its size */
static void
AttachAnimation(FIBITMAP *dib, const HEIFSequence *seq, int page) {
	const LONG frametime = FrameTimeMs(seq->durations[page], seq->timescale);
	const WORD left = 0;
	const WORD top = 0;
	const BYTE disposal = 1;
	const BYTE blend = 1;
	SetAnimTag(dib, "FrameTime", ANIMTAG_FRAMETIME, FIDT_LONG, 1, 4, &frametime);
	SetAnimTag(dib, "FrameLeft", ANIMTAG_FRAMELEFT, FIDT_SHORT, 1, 2, &left);
	SetAnimTag(dib, "FrameTop", ANIMTAG_FRAMETOP, FIDT_SHORT, 1, 2, &top);
	SetAnimTag(dib, "DisposalMethod", ANIMTAG_DISPOSALMETHOD, FIDT_BYTE, 1, 1, &disposal);
	SetAnimTag(dib, "BlendMethod", ANIMTAG_BLENDMETHOD, FIDT_BYTE, 1, 1, &blend);

	// canvas and loop on every frame, so deleting page 0 keeps them
	const unsigned width = FreeImage_GetWidth(dib);
	const unsigned height = FreeImage_GetHeight(dib);
	const WORD logicalwidth = (WORD)((width > 0xFFFF) ? 0xFFFF : width);
	const WORD logicalheight = (WORD)((height > 0xFFFF) ? 0xFFFF : height);
	SetAnimTag(dib, "LogicalWidth", ANIMTAG_LOGICALWIDTH, FIDT_SHORT, 1, 2, &logicalwidth);
	SetAnimTag(dib, "LogicalHeight", ANIMTAG_LOGICALHEIGHT, FIDT_SHORT, 1, 2, &logicalheight);
	SetAnimTag(dib, "Loop", ANIMTAG_LOOP, FIDT_LONG, 1, 4, &seq->loop);
}

static void
AttachFrameMetadata(FIBITMAP *dib, const HEIFSequence *seq, int page) {
	if(seq->icc && (seq->icc_size > 0)) {
		FreeImage_CreateICCProfile(dib, seq->icc, (long)seq->icc_size);
	}
	AttachAnimation(dib, seq, page);
}

static BOOL
DecodeThumbnail(const HEIFContext *ctx, FIBITMAP *dib, heif_image_handle *thumb_handle, heif_error *error) {
	BOOL bResult = FALSE;
	heif_decoding_options *options = CreateDecodingOptions(ctx, thumb_handle);
	if(!options) {
		return FALSE;
	}
	options->convert_hdr_to_8bit = 1;
	options->num_codec_threads = 1;
	heif_image *image = NULL;
	*error = heif_decode_image(thumb_handle, &image, heif_colorspace_RGB, heif_chroma_interleaved_RGB, options);
	if((error->code == heif_error_Ok) && image) {
		const int width = heif_image_get_width(image, heif_channel_interleaved);
		const int height = heif_image_get_height(image, heif_channel_interleaved);
		if((width > 0) && (height > 0)) {
			FIBITMAP *thumb = FreeImage_Allocate(width, height, 24, FI_RGBA_RED_MASK, FI_RGBA_GREEN_MASK, FI_RGBA_BLUE_MASK);
			if(thumb) {
				if(CopyInterleaved8(image, thumb, FALSE, FALSE)) {
					bResult = FreeImage_SetThumbnail(dib, thumb);
				}
				FreeImage_Unload(thumb);
			}
		}
	}
	if(image) {
		heif_image_release(image);
	}
	heif_decoding_options_free(options);
	return bResult;
}

/** first 'thmb' that decodes; a failure costs only the thumbnail */
static void
AttachThumbnail(const HEIFContext *ctx, FIBITMAP *dib, const heif_image_handle *handle) {
	heif_item_id ids[8];
	const int count = heif_image_handle_get_list_of_thumbnail_IDs(handle, ids, 8);
	if(count <= 0) {
		return;
	}
	heif_error error = heif_error_success;
	for(int i = 0; i < count; i++) {
		heif_image_handle *thumb_handle = NULL;
		error = heif_image_handle_get_thumbnail(handle, ids[i], &thumb_handle);
		if((error.code != heif_error_Ok) || !thumb_handle) {
			continue;
		}
		const BOOL ok = DecodeThumbnail(ctx, dib, thumb_handle, &error);
		heif_image_handle_release(thumb_handle);
		if(ok) {
			return;
		}
	}
	if(error.code != heif_error_Ok) {
		ReportError("Ignoring the thumbnail", error);
	}
}

// ----------------------------------------------------------
//   Image sequences: the track and its boxes
// ----------------------------------------------------------

/** 12 h at 60 fps (libavif's limit); bounds libheif's per-sample tables */
#define FI_HEIF_MAX_FRAMES 2592000

#define FI_HEIF_MAX_BOXES 4096

/** libheif's own ICC size limit */
#define FI_HEIF_MAX_ICC (100 * 1024 * 1024)

#define FI_HEIF_FOURCC(a, b, c, d) (((uint32_t)(a) << 24) | ((uint32_t)(b) << 16) | ((uint32_t)(c) << 8) | (uint32_t)(d))

static uint32_t
GetBE32(const BYTE *p) {
	return ((uint32_t)p[0] << 24) | ((uint32_t)p[1] << 16) | ((uint32_t)p[2] << 8) | (uint32_t)p[3];
}

static uint64_t
GetBE64(const BYTE *p) {
	return ((uint64_t)GetBE32(p) << 32) | (uint64_t)GetBE32(p + 4);
}

/** ISOBMFF box; positions relative to 'base' */
typedef struct tagHEIFBox {
	uint32_t type;
	uint64_t payload;		//! content start, after the header
	uint64_t end;			//! start of the next box
} HEIFBox;

static BOOL
ReadAt(HEIFStream *s, uint64_t offset, void *buffer, size_t size) {
	if(offset > (uint64_t)INT64_MAX) {
		return FALSE;
	}
	return ((HEIF_Seek((int64_t)offset, s) == 0) && (HEIF_Read(buffer, size, s) == 0)) ? TRUE : FALSE;
}

static BOOL
ReadBox(HEIFStream *s, uint64_t offset, uint64_t end, HEIFBox *box) {
	BYTE header[16];
	if((offset >= end) || (end - offset < 8) || !ReadAt(s, offset, header, 8)) {
		return FALSE;
	}
	uint64_t size = GetBE32(header);
	uint64_t header_size = 8;
	if(size == 1) {
		// a 64-bit size follows the type
		if((end - offset < 16) || !ReadAt(s, offset + 8, header + 8, 8)) {
			return FALSE;
		}
		size = GetBE64(header + 8);
		header_size = 16;
	} else if(size == 0) {
		// size 0: to the end of the container
		size = end - offset;
	}
	if((size < header_size) || (size > end - offset)) {
		return FALSE;
	}
	box->type = GetBE32(header + 4);
	box->payload = offset + header_size;
	box->end = offset + size;
	return TRUE;
}

static BOOL
FindBox(HEIFStream *s, uint64_t first, uint64_t end, uint32_t type, HEIFBox *box) {
	uint64_t offset = first;
	for(int n = 0; (n < FI_HEIF_MAX_BOXES) && ReadBox(s, offset, end, box); n++) {
		if(box->type == type) {
			return TRUE;
		}
		offset = box->end;
	}
	return FALSE;
}

static BYTE *
ReadPayload(HEIFStream *s, const HEIFBox *box, size_t max, size_t *size) {
	const uint64_t length = box->end - box->payload;
	*size = 0;
	if((length == 0) || (length > (uint64_t)max)) {
		return NULL;
	}
	BYTE *data = (BYTE*)malloc((size_t)length);
	if(data) {
		if(ReadAt(s, box->payload, data, (size_t)length)) {
			*size = (size_t)length;
		} else {
			free(data);
			data = NULL;
		}
	}
	return data;
}

static uint64_t
StreamEnd(const HEIFStream *s) {
	return s->size_known ? s->size : UINT64_MAX;
}

static uint32_t
ReadMajorBrand(HEIFStream *s) {
	HEIFBox box;
	BYTE brand[4];
	if(ReadBox(s, 0, StreamEnd(s), &box) && (box.type == FI_HEIF_FOURCC('f','t','y','p')) &&
	   (box.end - box.payload >= 4) && ReadAt(s, box.payload, brand, 4)) {
		return GetBE32(brand);
	}
	return 0;
}

static BOOL
IsSequenceBrand(uint32_t brand) {
	switch(brand) {
		case FI_HEIF_FOURCC('m','s','f','1'):	// image sequences
		case FI_HEIF_FOURCC('h','e','v','c'):	// HEVC image sequences
		case FI_HEIF_FOURCC('h','e','v','x'):
		case FI_HEIF_FOURCC('h','e','v','m'):
		case FI_HEIF_FOURCC('h','e','v','s'):
		case FI_HEIF_FOURCC('a','v','c','s'):	// AVC
		case FI_HEIF_FOURCC('j','p','g','s'):	// JPEG
		case FI_HEIF_FOURCC('j','2','i','s'):	// JPEG 2000
		case FI_HEIF_FOURCC('v','v','i','s'):	// VVC
			return TRUE;
	}
	return FALSE;
}

static BOOL
IsImageBrand(uint32_t brand) {
	switch(brand) {
		case FI_HEIF_FOURCC('m','i','f','1'):	// image items
		case FI_HEIF_FOURCC('m','i','f','2'):
		case FI_HEIF_FOURCC('m','i','f','3'):
		case FI_HEIF_FOURCC('m','i','a','f'):
		case FI_HEIF_FOURCC('1','p','i','c'):
		case FI_HEIF_FOURCC('h','e','i','c'):	// HEVC images
		case FI_HEIF_FOURCC('h','e','i','x'):
		case FI_HEIF_FOURCC('h','e','i','m'):
		case FI_HEIF_FOURCC('h','e','i','s'):
		case FI_HEIF_FOURCC('a','v','c','i'):	// AVC
		case FI_HEIF_FOURCC('j','p','e','g'):	// JPEG
		case FI_HEIF_FOURCC('j','2','k','i'):	// JPEG 2000
		case FI_HEIF_FOURCC('v','v','i','c'):	// VVC
			return TRUE;
	}
	return FALSE;
}

static heif_compression_format
SampleEntryFormat(uint32_t type) {
	switch(type) {
		case FI_HEIF_FOURCC('h','v','c','1'):
		case FI_HEIF_FOURCC('h','e','v','1'):
			return heif_compression_HEVC;
		case FI_HEIF_FOURCC('a','v','c','1'):
		case FI_HEIF_FOURCC('a','v','c','3'):
			return heif_compression_AVC;
		case FI_HEIF_FOURCC('a','v','0','1'):
			return heif_compression_AV1;
		case FI_HEIF_FOURCC('v','v','c','1'):
		case FI_HEIF_FOURCC('v','v','i','1'):
			return heif_compression_VVC;
		case FI_HEIF_FOURCC('m','j','p','g'):
			return heif_compression_JPEG;
		case FI_HEIF_FOURCC('j','2','k','i'):
			return heif_compression_JPEG2000;
		case FI_HEIF_FOURCC('u','n','c','v'):
			return heif_compression_uncompressed;
	}
	return heif_compression_undefined;
}

/** first 'pict' track that is not a thumbnail, else 'vide'; 0 if none */
static uint32_t
ChooseTrack(const heif_context *hctx) {
	const int count = heif_context_number_of_sequence_tracks(hctx);
	if(count <= 0) {
		return 0;
	}
	// heif_context_get_track_ids() writes exactly 'count' IDs
	uint32_t *ids = (uint32_t*)calloc((size_t)count, sizeof(uint32_t));
	if(!ids) {
		return 0;
	}
	heif_context_get_track_ids(hctx, ids);
	uint32_t best = 0;
	int best_rank = 2;
	for(int i = 0; i < count; i++) {
		heif_track *track = heif_context_get_track(hctx, ids[i]);
		if(!track) {
			continue;
		}
		const uint32_t handler = heif_track_get_track_handler_type(track);
		const int rank = (handler == heif_track_type_image_sequence) ? 0 : ((handler == heif_track_type_video) ? 1 : 2);
		if((rank < best_rank) && (heif_track_get_number_of_track_reference_of_type(track, heif_track_reference_type_thumbnails) == 0)) {
			best = ids[i];
			best_rank = rank;
		}
		heif_track_release(track);
	}
	free(ids);
	return best;
}

static void
ReorderDurations(HEIFStream *s, const HEIFBox *stbl, HEIFSequence *seq) {
	HEIFBox box;
	size_t size = 0;
	if(!FindBox(s, stbl->payload, stbl->end, FI_HEIF_FOURCC('c','t','t','s'), &box)) {
		return;
	}
	BYTE *ctts = ReadPayload(s, &box, 8 + 8 * (size_t)FI_HEIF_MAX_FRAMES, &size);
	if(!ctts) {
		return;
	}
	const uint32_t n = (uint32_t)seq->frames;
	int64_t *composition = NULL;
	uint32_t *order = NULL;
	uint32_t *durations = NULL;
	const uint32_t entries = (size >= 8) ? GetBE32(ctts + 4) : 0;
	uint64_t total = 0;
	if((size >= 8) && (entries <= (size - 8) / 8)) {
		for(uint32_t i = 0; i < entries; i++) {
			total += GetBE32(ctts + 8 + 8 * (size_t)i);
		}
	}
	// offsets must cover the samples exactly
	if((total == n) && (n > 1)) {
		composition = (int64_t*)malloc(n * sizeof(int64_t));
		order = (uint32_t*)malloc(n * sizeof(uint32_t));
	}
	if(composition && order) {
		BOOL reordered = FALSE;
		int32_t first = 0;
		uint64_t decoding = 0;
		uint32_t k = 0;
		for(uint32_t i = 0; i < entries; i++) {
			const uint32_t count = GetBE32(ctts + 8 + 8 * (size_t)i);
			// v0 unsigned, v1 signed: they agree on sane offsets
			int32_t offset = (int32_t)GetBE32(ctts + 12 + 8 * (size_t)i);
			if(offset == INT32_MIN) {
				offset = 0;
			}
			for(uint32_t c = 0; c < count; c++, k++) {
				if(k == 0) {
					first = offset;
				} else if(offset != first) {
					reordered = TRUE;
				}
				composition[k] = (int64_t)decoding + offset;
				decoding += seq->durations[k];
				order[k] = k;
			}
		}
		if(reordered) {
			const int64_t *ct = composition;
			std::stable_sort(order, order + n, [ct](uint32_t a, uint32_t b) { return ct[a] < ct[b]; });
			durations = (uint32_t*)malloc(n * sizeof(uint32_t));
			if(durations) {
				for(uint32_t i = 0; i + 1 < n; i++) {
					const int64_t d = ct[order[i + 1]] - ct[order[i]];
					durations[i] = (d > (int64_t)UINT32_MAX) ? UINT32_MAX : (uint32_t)d;
				}
				durations[n - 1] = seq->durations[order[n - 1]];
				free(seq->durations);
				seq->durations = durations;
			}
		}
	}
	free(order);
	free(composition);
	free(ctts);
}

/** durations and the frame count, from 'stts' */
static BOOL
ReadDurations(HEIFStream *s, const HEIFBox *stbl, HEIFSequence *seq) {
	HEIFBox box;
	size_t size = 0;
	if(!FindBox(s, stbl->payload, stbl->end, FI_HEIF_FOURCC('s','t','t','s'), &box)) {
		return FALSE;
	}
	BYTE *stts = ReadPayload(s, &box, 8 + 8 * (size_t)FI_HEIF_MAX_FRAMES, &size);
	if(!stts) {
		return FALSE;
	}
	BOOL bResult = FALSE;
	const uint32_t entries = (size >= 8) ? GetBE32(stts + 4) : 0;
	if((size >= 8) && (entries <= (size - 8) / 8)) {
		uint64_t total = 0;
		for(uint32_t i = 0; i < entries; i++) {
			total += GetBE32(stts + 8 + 8 * (size_t)i);
		}
		if((total > 0) && (total <= FI_HEIF_MAX_FRAMES)) {
			seq->durations = (uint32_t*)malloc((size_t)total * sizeof(uint32_t));
			if(seq->durations) {
				uint32_t k = 0;
				for(uint32_t i = 0; i < entries; i++) {
					const uint32_t count = GetBE32(stts + 8 + 8 * (size_t)i);
					const uint32_t delta = GetBE32(stts + 12 + 8 * (size_t)i);
					for(uint32_t c = 0; c < count; c++) {
						seq->durations[k++] = delta;
					}
				}
				seq->frames = (int)total;
				bResult = TRUE;
			}
		}
	}
	free(stts);
	if(bResult) {
		ReorderDurations(s, stbl, seq);
	}
	return bResult;
}

/** 'hvcC' depth/chroma and 'colr' ICC: libheif skips these for tracks */
static void
ReadSampleEntry(HEIFStream *s, const HEIFBox *stbl, HEIFSequence *seq) {
	HEIFBox stsd, entry, child;
	if(!FindBox(s, stbl->payload, stbl->end, FI_HEIF_FOURCC('s','t','s','d'), &stsd)) {
		return;
	}
	// after the full box header and the entry count
	if(!ReadBox(s, stsd.payload + 8, stsd.end, &entry)) {
		return;
	}
	// VisualSampleEntry: 78 bytes of fields first (14496-12, 12.1.3)
	if(entry.end - entry.payload < 78) {
		return;
	}
	const BOOL hevc = (SampleEntryFormat(entry.type) == heif_compression_HEVC) ? TRUE : FALSE;
	uint64_t offset = entry.payload + 78;
	for(int n = 0; (n < FI_HEIF_MAX_BOXES) && ReadBox(s, offset, entry.end, &child); n++) {
		if(hevc && (child.type == FI_HEIF_FOURCC('h','v','c','C')) && (child.end - child.payload >= 18)) {
			// hvcC (14496-15 8.3.3.1): chroma = byte16 & 3, depth - 8 = byte17 & 7
			BYTE hvcc[18];
			if(ReadAt(s, child.payload, hvcc, sizeof(hvcc))) {
				seq->mono = ((hvcc[16] & 3) == 0) ? TRUE : FALSE;
				seq->bits = (hvcc[17] & 7) + 8;
			}
		} else if((child.type == FI_HEIF_FOURCC('c','o','l','r')) && !seq->icc && (child.end - child.payload > 4)) {
			BYTE type[4];
			if(ReadAt(s, child.payload, type, 4) &&
			   ((GetBE32(type) == FI_HEIF_FOURCC('p','r','o','f')) || (GetBE32(type) == FI_HEIF_FOURCC('r','I','C','C')))) {
				const uint64_t length = child.end - child.payload - 4;
				if(length <= (uint64_t)FI_HEIF_MAX_ICC) {
					seq->icc = (BYTE*)malloc((size_t)length);
					if(seq->icc && ReadAt(s, child.payload + 4, seq->icc, (size_t)length)) {
						seq->icc_size = (size_t)length;
					} else {
						free(seq->icc);
						seq->icc = NULL;
					}
				}
			}
		}
		offset = child.end;
	}
}

static BOOL
ReadTrackBoxes(HEIFStream *s, HEIFSequence *seq) {
	HEIFBox moov, trak, box, mdia, minf, stbl;
	if(!FindBox(s, 0, StreamEnd(s), FI_HEIF_FOURCC('m','o','o','v'), &moov)) {
		return FALSE;
	}
	uint64_t offset = moov.payload;
	for(int n = 0; (n < FI_HEIF_MAX_BOXES) && ReadBox(s, offset, moov.end, &trak); n++) {
		offset = trak.end;
		if(trak.type != FI_HEIF_FOURCC('t','r','a','k')) {
			continue;
		}
		// tkhd: track ID after two 32-bit (v0) or 64-bit (v1) times
		BYTE tkhd[24];
		if(!FindBox(s, trak.payload, trak.end, FI_HEIF_FOURCC('t','k','h','d'), &box) ||
		   (box.end - box.payload < sizeof(tkhd)) || !ReadAt(s, box.payload, tkhd, sizeof(tkhd))) {
			continue;
		}
		if(GetBE32(tkhd + ((tkhd[0] == 1) ? 20 : 12)) != seq->track_id) {
			continue;
		}
		if(!FindBox(s, trak.payload, trak.end, FI_HEIF_FOURCC('m','d','i','a'), &mdia) ||
		   !FindBox(s, mdia.payload, mdia.end, FI_HEIF_FOURCC('m','i','n','f'), &minf) ||
		   !FindBox(s, minf.payload, minf.end, FI_HEIF_FOURCC('s','t','b','l'), &stbl)) {
			return FALSE;
		}
		if(!ReadDurations(s, &stbl, seq)) {
			return FALSE;
		}
		ReadSampleEntry(s, &stbl, seq);
		return TRUE;
	}
	return FALSE;
}

static void
FreeSequence(HEIFSequence *seq) {
	if(seq->track) {
		heif_track_release(seq->track);
	}
	if(seq->image) {
		heif_image_release(seq->image);
	}
	free(seq->durations);
	free(seq->icc);
	memset(seq, 0, sizeof(HEIFSequence));
	seq->image_page = -1;
}

static BOOL
OpenSequence(HEIFContext *ctx, BOOL *decodable) {
	HEIFSequence *seq = &ctx->seq;
	*decodable = FALSE;
	if(!heif_context_has_sequence(ctx->ctx)) {
		return FALSE;
	}
	seq->track_id = ChooseTrack(ctx->ctx);
	if(seq->track_id == 0) {
		return FALSE;
	}
	heif_track *track = heif_context_get_track(ctx->ctx, seq->track_id);
	if(!track) {
		return FALSE;
	}
	uint16_t width = 0;
	uint16_t height = 0;
	const BOOL visual = (heif_track_get_image_resolution(track, &width, &height).code == heif_error_Ok) ? TRUE : FALSE;
	seq->width = width;
	seq->height = height;
	seq->has_alpha = heif_track_has_alpha_channel(track) ? TRUE : FALSE;
	seq->timescale = heif_track_get_timescale(track);
	// edit list repeats: 1 = none, UINT32_MAX = forever, 0 = play once
	const uint32_t repetitions = heif_track_get_number_of_repetitions(track);
	if((repetitions == heif_sequence_track_number_of_repetitions_infinite) || (repetitions > 0x7FFFFFFF)) {
		seq->loop = 0;
	} else if(repetitions == 0) {
		seq->loop = 1;
	} else {
		seq->loop = (LONG)repetitions;
	}
	const heif_compression_format format = SampleEntryFormat(heif_track_get_sample_entry_type_of_first_cluster(track));
	*decodable = ((format != heif_compression_undefined) && heif_have_decoder_for_format(format)) ? TRUE : FALSE;
	heif_track_release(track);

	if(!visual || (width == 0) || (height == 0)) {
		return FALSE;
	}
	return ReadTrackBoxes(&ctx->stream, seq);
}

// ==========================================================
// Plugin Implementation
// ==========================================================

static const char * DLL_CALLCONV
Format() {
	return "HEIF";
}

static const char * DLL_CALLCONV
Description() {
	return "High Efficiency Image File Format";
}

static const char * DLL_CALLCONV
Extension() {
	return "heic,heif,hif,heics,heifs";
}

static const char * DLL_CALLCONV
RegExpr() {
	return NULL;
}

static const char * DLL_CALLCONV
MimeType() {
	return "image/heic";
}

static BOOL
IsBrand(const BYTE *b, const char *brand) {
	return (memcmp(b, brand, 4) == 0) ? TRUE : FALSE;
}

static BOOL DLL_CALLCONV
Validate(FreeImageIO *io, fi_handle handle) {
	BYTE buffer[4096];

	if(io->read_proc(buffer, 1, 8, handle) != 8) {
		return FALSE;
	}
	if(memcmp(buffer + 4, "ftyp", 4) != 0) {
		return FALSE;
	}
	const unsigned box_size = ((unsigned)buffer[0] << 24) | ((unsigned)buffer[1] << 16) | ((unsigned)buffer[2] << 8) | (unsigned)buffer[3];
	// 16 = box header + major brand + minor version
	if((box_size < 16) || (box_size > sizeof(buffer))) {
		return FALSE;
	}
	if(io->read_proc(buffer + 8, 1, box_size - 8, handle) != box_size - 8) {
		return FALSE;
	}

	BOOL hevc = FALSE;		// HEVC: this plugin's
	BOOL av1 = FALSE;		// AV1: the AVIF plugin's
	BOOL heif = FALSE;		// structural brand only
	for(unsigned offset = 8; offset + 4 <= box_size; offset += 4) {
		if(offset == 12) {
			// the minor version
			continue;
		}
		const BYTE *b = buffer + offset;
		if(IsBrand(b, "heic") || IsBrand(b, "heix") || IsBrand(b, "hevc") || IsBrand(b, "hevx") ||
		   IsBrand(b, "heim") || IsBrand(b, "heis") || IsBrand(b, "hevm") || IsBrand(b, "hevs")) {
			hevc = TRUE;
		} else if(IsBrand(b, "avif") || IsBrand(b, "avis")) {
			av1 = TRUE;
		} else if(IsBrand(b, "mif1") || IsBrand(b, "mif2") || IsBrand(b, "mif3") || IsBrand(b, "msf1") || IsBrand(b, "miaf")) {
			heif = TRUE;
		}
	}
	if(hevc) {
		return TRUE;
	}
	if(av1) {
		return FALSE;
	}
	// no codec brand: claim it; Load reports an unsupported payload
	return heif;
}

static BOOL DLL_CALLCONV
SupportsExportDepth(int depth) {
	return FALSE;
}

static BOOL DLL_CALLCONV
SupportsExportType(FREE_IMAGE_TYPE type) {
	return FALSE;
}

static BOOL DLL_CALLCONV
SupportsICCProfiles() {
	return TRUE;
}

static BOOL DLL_CALLCONV
SupportsNoPixels() {
	return TRUE;
}

// ----------------------------------------------------------

static void DLL_CALLCONV
Close(FreeImageIO *io, fi_handle handle, void *data) {
	HEIFContext *ctx = (HEIFContext*)data;
	if(ctx) {
		// the track references the context: free it first
		FreeSequence(&ctx->seq);
		if(ctx->ctx) {
			heif_context_free(ctx->ctx);
		}
		free(ctx->pages);
		free(ctx);
	}
}

static heif_context *
CreateContext(HEIFContext *ctx) {
	heif_context *hctx = heif_context_alloc();
	if(!hctx) {
		FreeImage_OutputMessageProc(s_format_id, FI_MSG_ERROR_MEMORY);
		return NULL;
	}
	// lift libheif's size/memory limits (gigapixel); frames are capped instead
	heif_security_limits *limits = heif_context_get_security_limits(hctx);
	if(limits) {
		limits->max_image_size_pixels = 0;
		limits->max_memory_block_size = 0;
		limits->max_total_memory = 0;
		limits->max_sequence_frames = FI_HEIF_MAX_FRAMES;
	}
	// tiles of a grid image are decoded in parallel
	heif_context_set_max_decoding_threads(hctx, ctx->threads);

	// rewind: a re-parse finds the stream where the last frame left it
	HEIF_Seek(0, &ctx->stream);
	const heif_error error = heif_context_read_from_reader(hctx, &s_reader, &ctx->stream, NULL);
	if(error.code != heif_error_Ok) {
		ReportError("Cannot parse the file", error);
		heif_context_free(hctx);
		return NULL;
	}
	return hctx;
}

static void * DLL_CALLCONV
Open(FreeImageIO *io, fi_handle handle, BOOL read) {
	if(!read) {
		// this plugin cannot write
		return NULL;
	}

	HEIFContext *ctx = (HEIFContext*)calloc(1, sizeof(HEIFContext));
	if(!ctx) {
		FreeImage_OutputMessageProc(s_format_id, FI_MSG_ERROR_MEMORY);
		return NULL;
	}

	// --- the stream ---

	HEIFStream *s = &ctx->stream;
	s->io = io;
	s->handle = handle;
	s->base = io->tell_proc(handle);
	if(s->base < 0) {
		s->base = 0;
	}
	if(io->seek_proc(handle, 0, SEEK_END) == 0) {
		const INT64 end = io->tell_proc(handle);
		if(end >= s->base) {
			s->size = (uint64_t)(end - s->base);
			s->size_known = TRUE;
		}
	}
	// libheif needs the exact length: probe for it
	if(!s->size_known) {
		HEIF_MeasureStream(s);
	}
	io->seek_proc(handle, s->base, SEEK_SET);
	s->position = 0;

	// --- the container ---

	ctx->threads = GetProcessorCount();
	ctx->seq.image_page = -1;
	ctx->ctx = CreateContext(ctx);
	if(!ctx->ctx) {
		Close(io, handle, ctx);
		return NULL;
	}

	// --- the top-level images, primary first ---

	// page 0 even when a broken file makes it a thumbnail
	heif_item_id primary = 0;
	const BOOL has_primary = (heif_context_get_primary_image_ID(ctx->ctx, &primary).code == heif_error_Ok) ? TRUE : FALSE;
	const int count = heif_context_get_number_of_top_level_images(ctx->ctx);
	ctx->pages = (heif_item_id*)calloc((size_t)(count > 0 ? count : 0) + 1, sizeof(heif_item_id));
	if(!ctx->pages) {
		FreeImage_OutputMessageProc(s_format_id, FI_MSG_ERROR_MEMORY);
		Close(io, handle, ctx);
		return NULL;
	}
	int n = 0;
	if(has_primary) {
		ctx->pages[n++] = primary;
	}
	if(count > 0) {
		heif_item_id *top = ctx->pages + n;
		const int got = heif_context_get_list_of_top_level_image_IDs(ctx->ctx, top, count);
		for(int i = 0; i < got; i++) {
			if(!has_primary || (top[i] != primary)) {
				ctx->pages[n++] = top[i];
			}
		}
	}
	ctx->page_count = n;

	// --- or the frames of an image sequence ---

	// both: images if the track is undecodable, else by major brand (libavif's rule)
	BOOL decodable = FALSE;
	if(OpenSequence(ctx, &decodable)) {
		const uint32_t brand = ReadMajorBrand(s);
		if(ctx->page_count <= 0) {
			ctx->frames = TRUE;
		} else if(!decodable) {
			ctx->frames = FALSE;
		} else if(IsSequenceBrand(brand)) {
			ctx->frames = TRUE;
		} else {
			ctx->frames = IsImageBrand(brand) ? FALSE : TRUE;
		}
	}
	if(ctx->frames) {
		ctx->page_count = ctx->seq.frames;
	} else {
		const BOOL has_sequence = heif_context_has_sequence(ctx->ctx) ? TRUE : FALSE;
		FreeSequence(&ctx->seq);
		if(ctx->page_count <= 0) {
			FreeImage_OutputMessageProc(s_format_id, has_sequence ? "The file contains no image, and its image sequence cannot be read" : "The file contains no image");
			Close(io, handle, ctx);
			return NULL;
		}
	}

	return ctx;
}

static int DLL_CALLCONV
PageCount(FreeImageIO *io, fi_handle handle, void *data) {
	HEIFContext *ctx = (HEIFContext*)data;
	if(!ctx || !ctx->ctx) {
		return 0;
	}
	return (ctx->page_count > 0) ? ctx->page_count : 1;
}

static FIBITMAP *
LoadHeader(const HEIFContext *ctx, const heif_image_handle *handle) {
	HEIFOutput out;
	ChooseOutput(handle, TRUE, &out);

	FIBITMAP *dib = AllocateOutput(TRUE, &out, heif_image_handle_get_width(handle), heif_image_handle_get_height(handle));
	if(dib) {
		AttachMetadata(dib, handle);
		AttachThumbnail(ctx, dib, handle);
	}
	return dib;
}

static FIBITMAP *
LoadPixels(const HEIFContext *ctx, const heif_image_handle *handle) {
	HEIFOutput out;
	heif_image *image = NULL;
	FIBITMAP *dib = NULL;

	heif_decoding_options *options = CreateDecodingOptions(ctx, handle);
	if(!options) {
		FreeImage_OutputMessageProc(s_format_id, FI_MSG_ERROR_MEMORY);
		return NULL;
	}

	// greyscale first; colour when libheif has no greyscale path
	BOOL allow_grey = TRUE;
	for(;;) {
		ChooseOutput(handle, allow_grey, &out);
		const heif_error error = heif_decode_image(handle, &image, out.colorspace, out.chroma, options);
		if((error.code == heif_error_Ok) && image) {
			break;
		}
		if(image) {
			heif_image_release(image);
			image = NULL;
		}
		if(out.grey && (error.code == heif_error_Unsupported_feature)) {
			allow_grey = FALSE;
			continue;
		}
		ReportError("Cannot decode the image", error);
		heif_decoding_options_free(options);
		return NULL;
	}
	heif_decoding_options_free(options);

	heif_error warnings[4];
	const int n = heif_image_get_decoding_warnings(image, 0, warnings, 4);
	for(int i = 0; i < n; i++) {
		ReportError("Warning", warnings[i]);
	}

	// the decoded image, not the handle, decides size and depth
	const BOOL premultiplied = (out.has_alpha && (heif_image_handle_is_premultiplied_alpha(handle) || heif_image_is_premultiplied_alpha(image))) ? TRUE : FALSE;
	dib = ImageToBitmap(image, &out, premultiplied, 0, 0);
	heif_image_release(image);

	if(dib) {
		AttachMetadata(dib, handle);
		AttachThumbnail(ctx, dib, handle);
	}
	return dib;
}

// ----------------------------------------------------------
//   Image sequences: the frames
// ----------------------------------------------------------

static void
DropTrack(HEIFSequence *seq) {
	if(seq->track) {
		heif_track_release(seq->track);
		seq->track = NULL;
	}
	seq->next = 0;
}

/** forward only; going back needs a fresh parse of the file */
static BOOL
PrepareTrack(HEIFContext *ctx, int page) {
	HEIFSequence *seq = &ctx->seq;
	if(seq->track && (page >= seq->next)) {
		return TRUE;
	}
	DropTrack(seq);
	if(seq->dirty) {
		heif_context *fresh = CreateContext(ctx);
		if(!fresh) {
			return FALSE;
		}
		heif_context_free(ctx->ctx);
		ctx->ctx = fresh;
		seq->dirty = FALSE;
	}
	seq->track = heif_context_get_track(ctx->ctx, seq->track_id);
	if(!seq->track) {
		FreeImage_OutputMessageProc(s_format_id, "Cannot access track %u", (unsigned)seq->track_id);
		return FALSE;
	}
	return TRUE;
}

/** caps a frame decode at 2x the file + 1 MB: libheif can loop forever */
static void
SetReadBudget(HEIFStream *s) {
	s->budget = (s->size_known && (s->size < (UINT64_MAX >> 2))) ? 2 * s->size + (1u << 20) : 0;
	s->spent = 0;
	s->overspent = FALSE;
}

static void
ClearReadBudget(HEIFStream *s) {
	s->budget = 0;
}

/** NULL drops the track; *retry_in_colour: no greyscale path, nothing reported */
static heif_image *
DecodeFrame(HEIFContext *ctx, int page, const HEIFOutput *out, BOOL playback, BOOL *retry_in_colour) {
	HEIFSequence *seq = &ctx->seq;
	*retry_in_colour = FALSE;
	if(!PrepareTrack(ctx, page)) {
		return NULL;
	}
	heif_decoding_options *options = CreateDecodingOptions(ctx, NULL);
	if(!options) {
		FreeImage_OutputMessageProc(s_format_id, FI_MSG_ERROR_MEMORY);
		return NULL;
	}

	HEIFStream *s = &ctx->stream;
	heif_error error = heif_error_success;
	while(seq->next < page) {
		heif_image *skipped = NULL;
		seq->dirty = TRUE;
		SetReadBudget(s);
		error = heif_track_decode_next_image(seq->track, &skipped, heif_colorspace_undefined, heif_chroma_undefined, options);
		ClearReadBudget(s);
		if(skipped) {
			heif_image_release(skipped);
		}
		if(error.code != heif_error_Ok) {
			break;
		}
		seq->next++;
	}
	heif_image *image = NULL;
	if(error.code == heif_error_Ok) {
		options->convert_hdr_to_8bit = playback ? 1 : 0;
		seq->dirty = TRUE;
		SetReadBudget(s);
		error = heif_track_decode_next_image(seq->track, &image, out->colorspace, out->chroma, options);
		ClearReadBudget(s);
	}
	heif_decoding_options_free(options);
	if((error.code == heif_error_Ok) && image) {
		seq->next++;
		return image;
	}
	if(image) {
		heif_image_release(image);
	}

	const int failed = seq->next;
	DropTrack(seq);
	if(s->overspent) {
		FreeImage_OutputMessageProc(s_format_id, "Cannot decode frame %d: the decoder gave no frame back for the whole track", failed);
		return NULL;
	}
	if(out->grey && (failed == page) && (error.code == heif_error_Unsupported_feature)) {
		*retry_in_colour = TRUE;
		return NULL;
	}
	FreeImage_OutputMessageProc(s_format_id, "Cannot decode frame %d: %s", failed, error.message ? error.message : "unknown error");
	return NULL;
}

static FIBITMAP *
LoadFrame(HEIFContext *ctx, int page, int flags) {
	HEIFSequence *seq = &ctx->seq;
	const BOOL header_only = ((flags & FIF_LOAD_NOPIXELS) == FIF_LOAD_NOPIXELS) ? TRUE : FALSE;
	const BOOL playback = ((flags & HEIF_PLAYBACK) == HEIF_PLAYBACK) ? TRUE : FALSE;
	HEIFOutput out;
	ChooseFrameOutput(seq, playback, &out);

	FIBITMAP *dib = NULL;
	if(header_only) {
		dib = AllocateOutput(TRUE, &out, seq->width, seq->height);
	} else {
		const BOOL kept = (seq->image && (seq->image_page == page) &&
		                   (seq->image_out.colorspace == out.colorspace) && (seq->image_out.chroma == out.chroma)) ? TRUE : FALSE;
		if(!kept) {
			if(seq->image) {
				heif_image_release(seq->image);
				seq->image = NULL;
				seq->image_page = -1;
			}
			BOOL retry = FALSE;
			heif_image *image = DecodeFrame(ctx, page, &out, playback, &retry);
			if(!image && retry) {
				// no greyscale path: decode this and later frames in colour
				seq->no_grey = TRUE;
				ChooseFrameOutput(seq, playback, &out);
				image = DecodeFrame(ctx, page, &out, playback, &retry);
			}
			if(!image) {
				return NULL;
			}
			heif_error warnings[4];
			const int n = heif_image_get_decoding_warnings(image, 0, warnings, 4);
			for(int i = 0; i < n; i++) {
				ReportError("Warning", warnings[i]);
			}
			seq->image = image;
			seq->image_page = page;
			seq->image_out = out;
		}
		// crop to the sample entry size: x265 pads small or odd frames
		HEIFOutput frame_out = seq->image_out;
		const BOOL premultiplied = (frame_out.has_alpha && heif_image_is_premultiplied_alpha(seq->image)) ? TRUE : FALSE;
		dib = ImageToBitmap(seq->image, &frame_out, premultiplied, seq->width, seq->height);
	}
	if(dib) {
		AttachFrameMetadata(dib, seq, page);
	}
	return dib;
}

static FIBITMAP * DLL_CALLCONV
Load(FreeImageIO *io, fi_handle handle, int page, int flags, void *data) {
	HEIFContext *ctx = (HEIFContext*)data;
	if(!ctx || !ctx->ctx) {
		return NULL;
	}
	if(page < 0) {
		page = 0;
	}
	if(page >= ctx->page_count) {
		FreeImage_OutputMessageProc(s_format_id, "Page %d does not exist: the file has %d %s", page, ctx->page_count, ctx->frames ? "frame(s)" : "image(s)");
		return NULL;
	}
	if(ctx->frames) {
		return LoadFrame(ctx, page, flags);
	}

	heif_image_handle *image_handle = NULL;
	const heif_error error = heif_context_get_image_handle(ctx->ctx, ctx->pages[page], &image_handle);
	if((error.code != heif_error_Ok) || !image_handle) {
		ReportError("Cannot access the image", error);
		return NULL;
	}

	const BOOL header_only = ((flags & FIF_LOAD_NOPIXELS) == FIF_LOAD_NOPIXELS) ? TRUE : FALSE;
	FIBITMAP *dib = header_only ? LoadHeader(ctx, image_handle) : LoadPixels(ctx, image_handle);

	heif_image_handle_release(image_handle);
	return dib;
}

// ==========================================================
//	 Init
// ==========================================================

void DLL_CALLCONV
InitHEIF(Plugin *plugin, int format_id) {
	s_format_id = format_id;

	plugin->format_proc = Format;
	plugin->description_proc = Description;
	plugin->extension_proc = Extension;
	plugin->regexpr_proc = RegExpr;
	plugin->open_proc = Open;
	plugin->close_proc = Close;
	plugin->pagecount_proc = PageCount;
	plugin->pagecapability_proc = NULL;
	plugin->load_proc = Load;
	plugin->save_proc = NULL;
	plugin->validate_proc = Validate;
	plugin->mime_proc = MimeType;
	plugin->supports_export_bpp_proc = SupportsExportDepth;
	plugin->supports_export_type_proc = SupportsExportType;
	plugin->supports_icc_profiles_proc = SupportsICCProfiles;
	plugin->supports_no_pixels_proc = SupportsNoPixels;
}
