// ==========================================================
// APNG (Animated PNG) Loader and Writer
//
// This file is part of FreeImage 3
//
// COVERED CODE IS PROVIDED UNDER THIS LICENSE ON AN "AS IS" BASIS, WITHOUT WARRANTY
// OF ANY KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, WITHOUT LIMITATION, WARRANTIES
// THAT THE COVERED CODE IS FREE OF DEFECTS, MERCHANTABLE, FIT FOR A PARTICULAR PURPOSE
// OR NON-INFRINGING. THE ENTIRE RISK AS TO THE QUALITY AND PERFORMANCE OF THE COVERED
// CODE IS WITH YOU. SHOULD ANY COVERED CODE PROVE DEFECTIVE IN ANY RESPECT, YOU (NOT
// THE INITIAL DEVELOPER OR ANY OTHER CONTRIBUTOR) ASSUME THE COST OF ANY NECESSARY
// SERVICING, REPAIR OR CORRECTION. THIS DISCLAIMER OF WARRANTY CONSTITUTES AN ESSENTIAL
// PART OF THIS LICENSE. NO USE OF ANY COVERED CODE IS AUTHORIZED HEREUNDER EXCEPT UNDER
// THIS DISCLAIMER.
//
// Use at your own risk!
//
// Code generated by Marius Șucan with Anthropic Claude
// ==========================================================

// frames are rebuilt as standalone PNGs and decoded by FIF_PNG
// spec: PNG Third Edition, 11.3.4

#ifdef _MSC_VER
#pragma warning (disable : 4786) // identifier was truncated to 'number' characters
#endif

#include "FreeImage.h"
#include "Utilities.h"
#include "Plugin.h"

#include "../Metadata/FreeImageTag.h"

#undef PNG_Z_DEFAULT_COMPRESSION	// already used in ../LibPNG/pnglibconf.h

#include "../ZLib/zlib.h"
#include "../LibPNG/png.h"

// ==========================================================
// Plugin Interface
// ==========================================================

static int s_format_id;

// ==========================================================
// Format constants
// ==========================================================

#define APNG_DISPOSE_OP_NONE		0
#define APNG_DISPOSE_OP_BACKGROUND	1	//! clear to transparent black
#define APNG_DISPOSE_OP_PREVIOUS	2	//! restore what was there before

#define APNG_BLEND_OP_SOURCE		0	//! overwrite, alpha included
#define APNG_BLEND_OP_OVER			1	//! alpha-composite over

// FIMD_ANIMATION "DisposalMethod" uses GIF's numbering
#define GIF_DISPOSAL_UNSPECIFIED	0
#define GIF_DISPOSAL_LEAVE			1
#define GIF_DISPOSAL_BACKGROUND		2
#define GIF_DISPOSAL_PREVIOUS		3

#define APNG_MAX_CHUNK_LENGTH		0x7FFFFFFFUL

// ==========================================================
// Chunk model
// ==========================================================

// one frame; data is its concatenated IDAT/fdAT payloads (a zlib stream)
struct APNGFrame {
	DWORD width, height;
	DWORD x_offset, y_offset;
	WORD delay_num, delay_den;
	BYTE dispose_op, blend_op;
	std::vector<BYTE> data;

	APNGFrame() : width(0), height(0), x_offset(0), y_offset(0), delay_num(0), delay_den(100),
		dispose_op(APNG_DISPOSE_OP_NONE), blend_op(APNG_BLEND_OP_SOURCE) {
	}
};

struct APNGinfo {
	BOOL read;

	// ---------- reading ----------

	BYTE ihdr[13];					//! IHDR payload, reused with each frame's size
	DWORD canvas_width;
	DWORD canvas_height;
	std::vector<BYTE> ancillary;	//! PLTE + ancillary chunks, replayed into every frame
	std::vector<APNGFrame> frames;
	DWORD num_plays;				//! 0 means loop forever
	BOOL animated;					//! FALSE for a plain PNG

	// APNG_PLAYBACK cache; previous_canvas only for APNG_DISPOSE_OP_PREVIOUS
	FIBITMAP *canvas;
	FIBITMAP *previous_canvas;
	int canvas_page;				//! the frame `canvas` shows, -1 when there is none

	// ---------- writing ----------

	FIBITMAP *pending;				//! first page, held until a second arrives
	int pending_flags;				//! its save flags
	int out_pages;					//! pages taken by Save()
	std::vector<BYTE> out_ancillary; //! frame 0's ancillary chunks
	std::vector<APNGFrame> out_frames;
	DWORD out_width, out_height;	//! grown to hold every frame
	DWORD out_plays;
	FIBITMAP *out_previous;			//! previous full frame; NULL = do not diff

	APNGinfo() : read(FALSE), canvas_width(0), canvas_height(0), num_plays(0), animated(FALSE),
		canvas(NULL), previous_canvas(NULL), canvas_page(-1),
		pending(NULL), pending_flags(0), out_pages(0), out_width(0), out_height(0), out_plays(0),
		out_previous(NULL) {
		memset(ihdr, 0, sizeof(ihdr));
	}

	~APNGinfo() {
		if(canvas) FreeImage_Unload(canvas);
		if(previous_canvas) FreeImage_Unload(previous_canvas);
		if(pending) FreeImage_Unload(pending);
		if(out_previous) FreeImage_Unload(out_previous);
	}
};

// ==========================================================
// Byte order and chunk helpers (PNG is big endian)
// ==========================================================

static inline DWORD
GetDWORD(const BYTE *p) {
	return ((DWORD)p[0] << 24) | ((DWORD)p[1] << 16) | ((DWORD)p[2] << 8) | (DWORD)p[3];
}

static inline WORD
GetWORD(const BYTE *p) {
	return (WORD)(((WORD)p[0] << 8) | (WORD)p[1]);
}

static inline void
PutDWORD(BYTE *p, DWORD value) {
	p[0] = (BYTE)(value >> 24);
	p[1] = (BYTE)(value >> 16);
	p[2] = (BYTE)(value >> 8);
	p[3] = (BYTE)value;
}

static inline void
PutWORD(BYTE *p, WORD value) {
	p[0] = (BYTE)(value >> 8);
	p[1] = (BYTE)value;
}

static void
AppendChunk(std::vector<BYTE>& out, const char *type, const BYTE *data, size_t length) {
	BYTE header[8];
	PutDWORD(header, (DWORD)length);
	memcpy(header + 4, type, 4);
	out.insert(out.end(), header, header + 8);
	if(length > 0) {
		out.insert(out.end(), data, data + length);
	}

	uLong crc = crc32(0, (const Bytef*)type, 4);
	if(length > 0) {
		crc = crc32(crc, (const Bytef*)data, (uInt)length);
	}
	BYTE trailer[4];
	PutDWORD(trailer, (DWORD)crc);
	out.insert(out.end(), trailer, trailer + 4);
}

// payload in two pieces: fdAT's sequence number, then the data
static BOOL
WriteChunk(FreeImageIO *io, fi_handle handle, const char *type, const BYTE *prefix, size_t prefix_length, const BYTE *data, size_t length) {
	const size_t total = prefix_length + length;
	if(total > APNG_MAX_CHUNK_LENGTH) {
		return FALSE;
	}

	BYTE header[8];
	PutDWORD(header, (DWORD)total);
	memcpy(header + 4, type, 4);
	if(io->write_proc(header, 1, 8, handle) != 8) {
		return FALSE;
	}

	uLong crc = crc32(0, (const Bytef*)type, 4);
	if(prefix_length > 0) {
		if(io->write_proc((void*)prefix, 1, (unsigned)prefix_length, handle) != prefix_length) {
			return FALSE;
		}
		crc = crc32(crc, (const Bytef*)prefix, (uInt)prefix_length);
	}
	if(length > 0) {
		if(io->write_proc((void*)data, 1, (unsigned)length, handle) != length) {
			return FALSE;
		}
		crc = crc32(crc, (const Bytef*)data, (uInt)length);
	}

	BYTE trailer[4];
	PutDWORD(trailer, (DWORD)crc);
	return (io->write_proc(trailer, 1, 4, handle) == 4) ? TRUE : FALSE;
}

// append in bounded steps; a short read leaves the buffer untouched, or keeps what it read
static BOOL
ReadBytes(FreeImageIO *io, fi_handle handle, std::vector<BYTE>& out, DWORD length, BOOL keep_partial = FALSE) {
	const DWORD step = 64 * 1024;
	const size_t start = out.size();

	DWORD done = 0;
	while(done < length) {
		const DWORD n = MIN(step, length - done);
		out.resize(start + done + n);
		const unsigned got = io->read_proc(&out[start + done], 1, n, handle);
		if(got != n) {
			out.resize(keep_partial ? (start + done + got) : start);
			return FALSE;
		}
		done += n;
	}
	return TRUE;
}

// ==========================================================
// Reading: parsing the container
// ==========================================================

// TRUE if acTL comes before IDAT; leaves the stream position moved
BOOL
APNG_IsAnimatedStream(FreeImageIO *io, fi_handle handle) {
	BYTE signature[8];

	if(io->read_proc(signature, 1, 8, handle) != 8) {
		return FALSE;
	}
	if(png_sig_cmp(signature, (png_size_t)0, 8) != 0) {
		return FALSE;
	}

	for(int guard = 0; guard < 1024; guard++) {
		BYTE header[8];
		if(io->read_proc(header, 1, 8, handle) != 8) {
			return FALSE;
		}
		const DWORD length = GetDWORD(header);
		if(length > APNG_MAX_CHUNK_LENGTH - 4) {
			return FALSE;
		}
		if(memcmp(header + 4, "acTL", 4) == 0) {
			return TRUE;
		}
		if((memcmp(header + 4, "IDAT", 4) == 0) || (memcmp(header + 4, "IEND", 4) == 0)) {
			return FALSE;
		}
		if(io->seek_proc(handle, (INT64)(length + 4), SEEK_CUR) != 0) {
			return FALSE;
		}
	}

	return FALSE;
}

// parse a 26-byte fcTL; FALSE unless the frame lies inside the canvas
static BOOL
ParseFrameControl(const BYTE *payload, DWORD canvas_width, DWORD canvas_height, APNGFrame *frame) {
	frame->width    = GetDWORD(payload + 4);
	frame->height   = GetDWORD(payload + 8);
	frame->x_offset = GetDWORD(payload + 12);
	frame->y_offset = GetDWORD(payload + 16);
	frame->delay_num = GetWORD(payload + 20);
	frame->delay_den = GetWORD(payload + 22);
	frame->dispose_op = payload[24];
	frame->blend_op = payload[25];

	if((frame->width == 0) || (frame->height == 0)) {
		return FALSE;
	}
	// written this way round, neither sum can overflow
	if((frame->x_offset > canvas_width - frame->width) || (frame->y_offset > canvas_height - frame->height)) {
		return FALSE;
	}
	if(frame->width > canvas_width || frame->height > canvas_height) {
		return FALSE;
	}
	if(frame->dispose_op > APNG_DISPOSE_OP_PREVIOUS) {
		return FALSE;
	}
	if(frame->blend_op > APNG_BLEND_OP_OVER) {
		return FALSE;
	}
	// "if the denominator is 0, it is to be treated as if it were 100"
	if(frame->delay_den == 0) {
		frame->delay_den = 100;
	}
	return TRUE;
}

// broken animation chunks: keep the default image as a single page
static BOOL
ParseStream(FreeImageIO *io, fi_handle handle, APNGinfo *info) {
	BYTE signature[8];

	if(io->read_proc(signature, 1, 8, handle) != 8) {
		return FALSE;
	}
	if(png_sig_cmp(signature, (png_size_t)0, 8) != 0) {
		return FALSE;
	}

	std::vector<BYTE> default_image;	//! IDAT stream; a frame only if an fcTL preceded it
	APNGFrame default_frame;
	BOOL have_ihdr = FALSE;
	BOOL have_actl = FALSE;
	BOOL seen_idat = FALSE;
	BOOL idat_is_frame = FALSE;
	BOOL broken = FALSE;				//! animation chunks inconsistent
	BOOL cut = FALSE;					//! the file ends inside image data, which the PNG loader salvages
	DWORD expected_seq = 0;				//! shared fcTL/fdAT sequence, no gaps
	int current = -1;					//! the frame fdAT payloads belong to

	for(;;) {
		BYTE header[8];
		if(io->read_proc(header, 1, 8, handle) != 8) {
			break;
		}
		const DWORD length = GetDWORD(header);
		const BYTE *type = header + 4;
		if(length > APNG_MAX_CHUNK_LENGTH) {
			break;
		}
		DWORD consumed = 0;				//! payload bytes read below

		if(memcmp(type, "IHDR", 4) == 0) {
			if(have_ihdr || (length != 13) || (io->read_proc(info->ihdr, 1, 13, handle) != 13)) {
				return FALSE;
			}
			consumed = 13;
			info->canvas_width = GetDWORD(info->ihdr);
			info->canvas_height = GetDWORD(info->ihdr + 4);
			if((info->canvas_width == 0) || (info->canvas_height == 0) ||
			   (info->canvas_width > 0x7FFFFFFF) || (info->canvas_height > 0x7FFFFFFF)) {
				return FALSE;
			}
			have_ihdr = TRUE;

		} else if(memcmp(type, "IDAT", 4) == 0) {
			if(!have_ihdr) {
				return FALSE;
			}
			seen_idat = TRUE;
			if(!ReadBytes(io, handle, default_image, length, TRUE)) {
				cut = TRUE;
				break;
			}
			consumed = length;

		} else if(memcmp(type, "acTL", 4) == 0) {
			BYTE payload[8];
			// a second acTL breaks the animation; one after IDAT is ignored
			if((length == 8) && (io->read_proc(payload, 1, 8, handle) == 8)) {
				consumed = 8;
				if(have_actl) {
					broken = TRUE;
				} else if(!seen_idat) {
					// num_frames is advisory; the fcTL chunks decide
					info->num_plays = GetDWORD(payload + 4);
					have_actl = TRUE;
				}
			}

		} else if(memcmp(type, "fcTL", 4) == 0) {
			BYTE payload[26];
			if(!have_ihdr) {
				return FALSE;
			}
			if((length != 26) || (io->read_proc(payload, 1, 26, handle) != 26)) {
				broken = TRUE;
			} else {
				consumed = 26;
				APNGFrame frame;
				if(GetDWORD(payload) != expected_seq) {
					broken = TRUE;
				} else if(!ParseFrameControl(payload, info->canvas_width, info->canvas_height, &frame)) {
					broken = TRUE;
				} else if(!seen_idat) {
					// an fcTL before IDAT must cover the whole canvas
					if(idat_is_frame || (frame.x_offset != 0) || (frame.y_offset != 0) ||
					   (frame.width != info->canvas_width) || (frame.height != info->canvas_height)) {
						broken = TRUE;
					} else {
						expected_seq++;
						default_frame = frame;
						idat_is_frame = TRUE;
					}
				} else {
					expected_seq++;
					info->frames.push_back(frame);
					current = (int)info->frames.size() - 1;
				}
			}

		} else if(memcmp(type, "fdAT", 4) == 0) {
			BYTE sequence[4];
			if((length < 4) || (current < 0) || (io->read_proc(sequence, 1, 4, handle) != 4)) {
				broken = TRUE;
			} else {
				consumed = 4;
				if(GetDWORD(sequence) != expected_seq) {
					broken = TRUE;
				} else {
					expected_seq++;
					if(!ReadBytes(io, handle, info->frames[current].data, length - 4, TRUE)) {
						cut = TRUE;
						break;
					}
					consumed = length;
				}
			}

		} else if(memcmp(type, "IEND", 4) == 0) {
			break;

		} else if((memcmp(type, "PLTE", 4) == 0) || ((type[0] & 0x20) != 0)) {
			// PLTE and ancillary chunks are replayed ahead of every frame
			const size_t start = info->ancillary.size();
			info->ancillary.insert(info->ancillary.end(), header, header + 8);
			if(!ReadBytes(io, handle, info->ancillary, length + 4)) {
				// truncated chunk: keep what came before it
				info->ancillary.resize(start);
				break;
			}
			continue;	// CRC already read

		} else {
			// unknown critical chunk: refuse the file
			return FALSE;
		}

		// skip the rest of the payload and the CRC
		if(io->seek_proc(handle, (INT64)(length - consumed) + 4, SEEK_CUR) != 0) {
			break;
		}
	}

	if(!have_ihdr || default_image.empty()) {
		return FALSE;
	}

	// drop trailing frames without data; a gap mid-way breaks the animation
	while(!info->frames.empty() && info->frames.back().data.empty()) {
		info->frames.pop_back();
	}
	for(size_t i = 0; i < info->frames.size(); i++) {
		if(info->frames[i].data.empty()) {
			broken = TRUE;
		}
	}

	info->animated = (have_actl && !broken && (idat_is_frame || !info->frames.empty())) ? TRUE : FALSE;

	if(cut) {
		FreeImage_OutputMessageProc(s_format_id, "Warning: the file is cut short; the frames it holds are kept");
	}

	if(info->animated) {
		if(idat_is_frame) {
			default_frame.data.swap(default_image);
			info->frames.insert(info->frames.begin(), default_frame);
		}
	} else {
		// plain or broken APNG: the default image as one page
		info->frames.clear();
		APNGFrame frame;
		frame.width = info->canvas_width;
		frame.height = info->canvas_height;
		frame.data.swap(default_image);
		info->frames.push_back(frame);
		info->num_plays = 0;
	}

	return TRUE;
}

// ==========================================================
// Reading: frames
// ==========================================================

// rebuild a frame as a standalone PNG and decode it with FIF_PNG
static FIBITMAP *
DecodeFrame(APNGinfo *info, int page, int flags) {
	const APNGFrame& frame = info->frames[page];
	if(frame.data.empty() || (frame.data.size() > APNG_MAX_CHUNK_LENGTH)) {
		// one IDAT chunk: 31-bit length limit
		return NULL;
	}

	static const BYTE signature[8] = { 137, 80, 78, 71, 13, 10, 26, 10 };

	std::vector<BYTE> png;
	png.reserve(8 + 25 + info->ancillary.size() + frame.data.size() + 12 + 12);
	png.insert(png.end(), signature, signature + 8);

	BYTE ihdr[13];
	memcpy(ihdr, info->ihdr, 13);
	PutDWORD(ihdr, frame.width);
	PutDWORD(ihdr + 4, frame.height);
	AppendChunk(png, "IHDR", ihdr, 13);

	png.insert(png.end(), info->ancillary.begin(), info->ancillary.end());

	AppendChunk(png, "IDAT", &frame.data[0], frame.data.size());
	AppendChunk(png, "IEND", NULL, 0);

	if(png.size() > 0xFFFFFFFFUL) {
		return NULL;
	}

	FIMEMORY *hmem = FreeImage_OpenMemory(&png[0], (DWORD)png.size());
	if(hmem == NULL) {
		return NULL;
	}
	FIBITMAP *dib = FreeImage_LoadFromMemory(FIF_PNG, hmem, flags);
	FreeImage_CloseMemory(hmem);

	return dib;
}

static void
ClearRegion(FIBITMAP *canvas, DWORD x, DWORD y, DWORD width, DWORD height) {
	const DWORD canvas_height = FreeImage_GetHeight(canvas);
	for(DWORD row = 0; row < height; row++) {
		BYTE *line = FreeImage_GetScanLine(canvas, canvas_height - 1 - (y + row));
		memset(line + (size_t)x * 4, 0, (size_t)width * 4);
	}
}

// (x, y) counts from the top; both bitmaps are bottom-up
static void
CompositeFrame(FIBITMAP *canvas, FIBITMAP *frame, DWORD x, DWORD y, BYTE blend_op) {
	const DWORD canvas_height = FreeImage_GetHeight(canvas);
	const DWORD width = FreeImage_GetWidth(frame);
	const DWORD height = FreeImage_GetHeight(frame);

	for(DWORD row = 0; row < height; row++) {
		const BYTE *src = FreeImage_GetScanLine(frame, height - 1 - row);
		BYTE *dst = FreeImage_GetScanLine(canvas, canvas_height - 1 - (y + row)) + (size_t)x * 4;

		if(blend_op == APNG_BLEND_OP_SOURCE) {
			memcpy(dst, src, (size_t)width * 4);
			continue;
		}

		// OVER operator, scaled by 255 to stay in integers
		for(DWORD col = 0; col < width; col++) {
			const unsigned sa = src[FI_RGBA_ALPHA];
			if(sa == 255) {
				memcpy(dst, src, 4);
			} else if(sa != 0) {
				const unsigned da = dst[FI_RGBA_ALPHA];
				const unsigned weight = da * (255 - sa);			// the background's share, x255
				const unsigned alpha = sa * 255 + weight;			// the result's alpha, x255
				if(alpha == 0) {
					dst[FI_RGBA_RED] = dst[FI_RGBA_GREEN] = dst[FI_RGBA_BLUE] = dst[FI_RGBA_ALPHA] = 0;
				} else {
					// rounded, not truncated: truncation drifts over long animations
					const unsigned half = alpha / 2;
					dst[FI_RGBA_RED]   = (BYTE)((src[FI_RGBA_RED]   * sa * 255 + dst[FI_RGBA_RED]   * weight + half) / alpha);
					dst[FI_RGBA_GREEN] = (BYTE)((src[FI_RGBA_GREEN] * sa * 255 + dst[FI_RGBA_GREEN] * weight + half) / alpha);
					dst[FI_RGBA_BLUE]  = (BYTE)((src[FI_RGBA_BLUE]  * sa * 255 + dst[FI_RGBA_BLUE]  * weight + half) / alpha);
					dst[FI_RGBA_ALPHA] = (BYTE)((alpha + 127) / 255);
				}
			}
			src += 4;
			dst += 4;
		}
	}
}

static void
DisposeFrame(APNGinfo *info, int page) {
	const APNGFrame& frame = info->frames[page];

	switch(frame.dispose_op) {
		case APNG_DISPOSE_OP_BACKGROUND:
			ClearRegion(info->canvas, frame.x_offset, frame.y_offset, frame.width, frame.height);
			break;

		case APNG_DISPOSE_OP_PREVIOUS:
			if(info->previous_canvas != NULL) {
				FreeImage_Unload(info->canvas);
				info->canvas = info->previous_canvas;
				info->previous_canvas = NULL;
			}
			break;

		default:
			break;
	}
}

// composited canvas at a frame; going backwards restarts from frame 0
static FIBITMAP *
RenderFrame(APNGinfo *info, int page, int flags) {
	if((info->canvas != NULL) && (info->canvas_page == page)) {
		return FreeImage_Clone(info->canvas);
	}

	int start;
	if((info->canvas != NULL) && (info->canvas_page >= 0) && (info->canvas_page < page)) {
		start = info->canvas_page + 1;
	} else {
		// each play starts from a fully transparent black canvas
		if(info->canvas != NULL) {
			FreeImage_Unload(info->canvas);
		}
		if(info->previous_canvas != NULL) {
			FreeImage_Unload(info->previous_canvas);
			info->previous_canvas = NULL;
		}
		info->canvas_page = -1;
		info->canvas = FreeImage_Allocate(info->canvas_width, info->canvas_height, 32, FI_RGBA_RED_MASK, FI_RGBA_GREEN_MASK, FI_RGBA_BLUE_MASK);
		if(info->canvas == NULL) {
			return NULL;
		}
		start = 0;
	}

	for(int i = start; i <= page; i++) {
		if(i > 0) {
			DisposeFrame(info, i - 1);
		}

		FIBITMAP *raw = DecodeFrame(info, i, flags & ~(APNG_PLAYBACK | FIF_LOAD_NOPIXELS));
		if(raw == NULL) {
			info->canvas_page = -1;		// do not hand out a half drawn canvas later
			return NULL;
		}
		FIBITMAP *frame32 = FreeImage_ConvertTo32Bits(raw);
		FreeImage_Unload(raw);
		if(frame32 == NULL) {
			info->canvas_page = -1;
			return NULL;
		}

		const APNGFrame& frame = info->frames[i];
		if((FreeImage_GetWidth(frame32) != frame.width) || (FreeImage_GetHeight(frame32) != frame.height)) {
			// fcTL and frame size disagree
			FreeImage_Unload(frame32);
			info->canvas_page = -1;
			return NULL;
		}

		if(frame.dispose_op == APNG_DISPOSE_OP_PREVIOUS) {
			if(info->previous_canvas != NULL) {
				FreeImage_Unload(info->previous_canvas);
			}
			info->previous_canvas = FreeImage_Clone(info->canvas);
		}

		CompositeFrame(info->canvas, frame32, frame.x_offset, frame.y_offset, (i == 0) ? APNG_BLEND_OP_SOURCE : frame.blend_op);
		FreeImage_Unload(frame32);

		info->canvas_page = i;
	}

	return FreeImage_Clone(info->canvas);
}

static BOOL
SetAnimTag(FIBITMAP *dib, const char *key, WORD id, FREE_IMAGE_MDTYPE type, DWORD count, DWORD length, const void *value) {
	BOOL bResult = FALSE;
	FITAG *tag = FreeImage_CreateTag();
	if(tag) {
		FreeImage_SetTagKey(tag, key);
		FreeImage_SetTagID(tag, id);
		FreeImage_SetTagType(tag, type);
		FreeImage_SetTagCount(tag, count);
		FreeImage_SetTagLength(tag, length);
		FreeImage_SetTagValue(tag, value);
		TagLib& s = TagLib::instance();
		FreeImage_SetTagDescription(tag, s.getTagDescription(TagLib::ANIMATION, id));
		bResult = FreeImage_SetMetadata(FIMD_ANIMATION, dib, key, tag);
		FreeImage_DeleteTag(tag);
	}
	return bResult;
}

static BOOL
GetAnimTag(FIBITMAP *dib, const char *key, FREE_IMAGE_MDTYPE type, FITAG **tag) {
	if(FreeImage_GetMetadata(FIMD_ANIMATION, dib, key, tag)) {
		if((FreeImage_GetTagType(*tag) == type) && (FreeImage_GetTagValue(*tag) != NULL)) {
			return TRUE;
		}
	}
	return FALSE;
}

// FrameTime in ms; DisposalMethod in GIF numbering
static void
SetFrameMetadata(FIBITMAP *dib, const APNGinfo *info, int page) {
	const APNGFrame& frame = info->frames[page];

	// delay_num/delay_den seconds, rounded to ms
	LONG duration = (LONG)(((DWORD)frame.delay_num * 1000 + frame.delay_den / 2) / frame.delay_den);
	WORD left = (WORD)MIN(frame.x_offset, (DWORD)0xFFFF);
	WORD top = (WORD)MIN(frame.y_offset, (DWORD)0xFFFF);
	BYTE disposal = (frame.dispose_op == APNG_DISPOSE_OP_BACKGROUND) ? GIF_DISPOSAL_BACKGROUND :
					(frame.dispose_op == APNG_DISPOSE_OP_PREVIOUS) ? GIF_DISPOSAL_PREVIOUS : GIF_DISPOSAL_LEAVE;
	BYTE blend = (frame.blend_op == APNG_BLEND_OP_SOURCE) ? 1 : 0;

	SetAnimTag(dib, "FrameTime", ANIMTAG_FRAMETIME, FIDT_LONG, 1, 4, &duration);
	SetAnimTag(dib, "FrameLeft", ANIMTAG_FRAMELEFT, FIDT_SHORT, 1, 2, &left);
	SetAnimTag(dib, "FrameTop", ANIMTAG_FRAMETOP, FIDT_SHORT, 1, 2, &top);
	SetAnimTag(dib, "DisposalMethod", ANIMTAG_DISPOSALMETHOD, FIDT_BYTE, 1, 1, &disposal);
	SetAnimTag(dib, "BlendMethod", ANIMTAG_BLENDMETHOD, FIDT_BYTE, 1, 1, &blend);

	// canvas and loop count on every frame, so deleting page 0 keeps them
	{
		WORD logicalwidth = (WORD)MIN(info->canvas_width, (DWORD)0xFFFF);
		WORD logicalheight = (WORD)MIN(info->canvas_height, (DWORD)0xFFFF);
		LONG loop = (LONG)info->num_plays;
		SetAnimTag(dib, "LogicalWidth", ANIMTAG_LOGICALWIDTH, FIDT_SHORT, 1, 2, &logicalwidth);
		SetAnimTag(dib, "LogicalHeight", ANIMTAG_LOGICALHEIGHT, FIDT_SHORT, 1, 2, &logicalheight);
		SetAnimTag(dib, "Loop", ANIMTAG_LOOP, FIDT_LONG, 1, 4, &loop);
	}
}

// ==========================================================
// Writing: compressing a frame
// ==========================================================

static void
error_handler(png_structp png_ptr, const char *error) {
	FreeImage_OutputMessageProc(s_format_id, error);
	png_longjmp(png_ptr, 1);
}

static void
warning_handler(png_structp png_ptr, const char *warning) {
	(png_structp)png_ptr;
	(char*)warning;
}

static void
_WriteVectorProc(png_structp png_ptr, png_bytep data, png_size_t size) {
	std::vector<BYTE> *out = (std::vector<BYTE>*)png_get_io_ptr(png_ptr);
	try {
		out->insert(out->end(), data, data + size);
	} catch(...) {
		png_error(png_ptr, "Out of memory");
	}
}

static void
_FlushVectorProc(png_structp png_ptr) {
	(png_structp)png_ptr;
}

/**
Compress a 32-bit dib to an RGBA PNG in memory.
@return Returns TRUE if successful, returns FALSE otherwise
*/
static BOOL
CompressFrame(FIBITMAP *dib, int flags, BOOL with_metadata, std::vector<BYTE>& png) {
	png_structp png_ptr = png_create_write_struct(PNG_LIBPNG_VER_STRING, (png_voidp)NULL, error_handler, warning_handler);
	if(png_ptr == NULL) {
		return FALSE;
	}
	png_infop info_ptr = png_create_info_struct(png_ptr);
	if(info_ptr == NULL) {
		png_destroy_write_struct(&png_ptr, (png_infopp)NULL);
		return FALSE;
	}

	// only plain values across setjmp: longjmp skips destructors
	if(setjmp(png_jmpbuf(png_ptr))) {
		png_destroy_write_struct(&png_ptr, &info_ptr);
		return FALSE;
	}

	png_set_write_fn(png_ptr, &png, _WriteVectorProc, _FlushVectorProc);

	const png_uint_32 width = (png_uint_32)FreeImage_GetWidth(dib);
	const png_uint_32 height = (png_uint_32)FreeImage_GetHeight(dib);

	png_set_IHDR(png_ptr, info_ptr, width, height, 8, PNG_COLOR_TYPE_RGBA,
		PNG_INTERLACE_NONE, PNG_COMPRESSION_TYPE_BASE, PNG_FILTER_TYPE_BASE);

	const int zlib_level = flags & 0x0F;
	if((zlib_level >= 1) && (zlib_level <= 9)) {
		png_set_compression_level(png_ptr, zlib_level);
	} else if((flags & PNG_Z_NO_COMPRESSION) == PNG_Z_NO_COMPRESSION) {
		png_set_compression_level(png_ptr, Z_NO_COMPRESSION);
	}
	png_set_compression_strategy(png_ptr, Z_FILTERED);
	png_set_filter(png_ptr, 0, PNG_FILTER_NONE | PNG_FILTER_SUB | PNG_FILTER_UP | PNG_FILTER_PAETH);

	if(with_metadata) {
		const png_uint_32 res_x = (png_uint_32)FreeImage_GetDotsPerMeterX(dib);
		const png_uint_32 res_y = (png_uint_32)FreeImage_GetDotsPerMeterY(dib);
		if((res_x > 0) && (res_y > 0)) {
			png_set_pHYs(png_ptr, info_ptr, res_x, res_y, PNG_RESOLUTION_METER);
		}
		FIICCPROFILE *iccProfile = FreeImage_GetICCProfile(dib);
		if(iccProfile->size && iccProfile->data) {
			png_set_option(png_ptr, PNG_SKIP_sRGB_CHECK_PROFILE, 1);
			png_set_iCCP(png_ptr, info_ptr, "Embedded Profile", 0, (png_const_bytep)iccProfile->data, iccProfile->size);
		}
	}

	png_write_info(png_ptr, info_ptr);

#if FREEIMAGE_COLORORDER == FREEIMAGE_COLORORDER_BGR
	png_set_bgr(png_ptr);
#endif

	for(png_uint_32 k = 0; k < height; k++) {
		png_write_row(png_ptr, FreeImage_GetScanLine(dib, height - k - 1));
	}

	png_write_end(png_ptr, info_ptr);
	png_destroy_write_struct(&png_ptr, &info_ptr);

	return TRUE;
}

/**
Split a PNG into its image data and ancillary chunks.
@return Returns TRUE if successful, returns FALSE otherwise
*/
static BOOL
SplitPNG(const std::vector<BYTE>& png, std::vector<BYTE> *ancillary, std::vector<BYTE>& data) {
	size_t pos = 8;		// past the signature

	while(pos + 8 <= png.size()) {
		const DWORD length = GetDWORD(&png[pos]);
		if((length > APNG_MAX_CHUNK_LENGTH) || (pos + 12 + length > png.size())) {
			return FALSE;
		}
		const BYTE *type = &png[pos + 4];

		if(memcmp(type, "IDAT", 4) == 0) {
			data.insert(data.end(), png.begin() + (pos + 8), png.begin() + (pos + 8 + length));
		} else if(memcmp(type, "IEND", 4) == 0) {
			return !data.empty();
		} else if(memcmp(type, "IHDR", 4) != 0) {
			if(ancillary != NULL) {
				ancillary->insert(ancillary->end(), png.begin() + pos, png.begin() + (pos + 12 + length));
			}
		}

		pos += 12 + length;
	}

	return FALSE;
}

// bounding box of the differences; FALSE if identical
static BOOL
DifferenceRegion(FIBITMAP *current, FIBITMAP *previous, DWORD *out_x, DWORD *out_y, DWORD *out_width, DWORD *out_height) {
	const DWORD width = FreeImage_GetWidth(current);
	const DWORD height = FreeImage_GetHeight(current);

	DWORD left = width, right = 0, top = height, bottom = 0;

	for(DWORD row = 0; row < height; row++) {
		const DWORD *src = (const DWORD*)FreeImage_GetScanLine(current, height - 1 - row);
		const DWORD *ref = (const DWORD*)FreeImage_GetScanLine(previous, height - 1 - row);
		if(memcmp(src, ref, (size_t)width * 4) == 0) {
			continue;
		}
		if(row < top) {
			top = row;
		}
		bottom = row;
		for(DWORD col = 0; col < left; col++) {
			if(src[col] != ref[col]) {
				left = col;
				break;
			}
		}
		for(DWORD col = width; col > right; col--) {
			if(src[col - 1] != ref[col - 1]) {
				right = col;
				break;
			}
		}
	}

	if(right <= left) {
		return FALSE;
	}

	*out_x = left;
	*out_y = top;
	*out_width = right - left;
	*out_height = bottom - top + 1;

	return TRUE;
}

// TRUE if the dib carries any frame tag; untagged fields keep defaults
static BOOL
ReadFrameTags(FIBITMAP *dib, APNGFrame *frame) {
	FITAG *tag = NULL;
	BOOL tagged = FALSE;

	frame->width = FreeImage_GetWidth(dib);
	frame->height = FreeImage_GetHeight(dib);
	frame->delay_num = 100;
	frame->delay_den = 1000;

	if(GetAnimTag(dib, "FrameLeft", FIDT_SHORT, &tag)) {
		frame->x_offset = *(WORD*)FreeImage_GetTagValue(tag);
		tagged = TRUE;
	}
	if(GetAnimTag(dib, "FrameTop", FIDT_SHORT, &tag)) {
		frame->y_offset = *(WORD*)FreeImage_GetTagValue(tag);
		tagged = TRUE;
	}
	if(GetAnimTag(dib, "FrameTime", FIDT_LONG, &tag)) {
		// ms, stored exactly with a denominator of 1000
		const LONG delay = *(LONG*)FreeImage_GetTagValue(tag);
		frame->delay_num = (WORD)((delay < 0) ? 0 : MIN(delay, (LONG)0xFFFF));
		tagged = TRUE;
	}
	if(GetAnimTag(dib, "DisposalMethod", FIDT_BYTE, &tag)) {
		const BYTE disposal = *(BYTE*)FreeImage_GetTagValue(tag);
		frame->dispose_op = (disposal == GIF_DISPOSAL_BACKGROUND) ? APNG_DISPOSE_OP_BACKGROUND :
							(disposal == GIF_DISPOSAL_PREVIOUS) ? APNG_DISPOSE_OP_PREVIOUS : APNG_DISPOSE_OP_NONE;
		tagged = TRUE;
	}
	if(GetAnimTag(dib, "BlendMethod", FIDT_BYTE, &tag)) {
		// the tag is GIF's way round: 1 means do not blend
		frame->blend_op = (*(BYTE*)FreeImage_GetTagValue(tag) != 0) ? APNG_BLEND_OP_SOURCE : APNG_BLEND_OP_OVER;
		tagged = TRUE;
	}
	if(FreeImage_GetMetadata(FIMD_ANIMATION, dib, "LogicalWidth", &tag) ||
	   FreeImage_GetMetadata(FIMD_ANIMATION, dib, "LogicalHeight", &tag) ||
	   FreeImage_GetMetadata(FIMD_ANIMATION, dib, "Loop", &tag)) {
		tagged = TRUE;
	}

	return tagged;
}

// canvas and loop count, from the first frame
static void
ReadAnimationTags(FIBITMAP *dib, const APNGFrame *frame, DWORD *width, DWORD *height, DWORD *plays) {
	FITAG *tag = NULL;

	*width = frame->width;
	*height = frame->height;
	if(GetAnimTag(dib, "LogicalWidth", FIDT_SHORT, &tag)) {
		*width = *(WORD*)FreeImage_GetTagValue(tag);
	}
	if(GetAnimTag(dib, "LogicalHeight", FIDT_SHORT, &tag)) {
		*height = *(WORD*)FreeImage_GetTagValue(tag);
	}
	if(GetAnimTag(dib, "Loop", FIDT_LONG, &tag)) {
		const LONG loop = *(LONG*)FreeImage_GetTagValue(tag);
		*plays = (loop > 0) ? (DWORD)loop : 0;
	}
}

/**
Normalize, diff, compress and queue one page for Close().
@return Returns TRUE if successful, returns FALSE otherwise
*/
static BOOL
AddFrame(APNGinfo *info, FIBITMAP *dib, int flags, BOOL is_first) {
	// one IHDR for all frames: always 8-bit RGBA
	FIBITMAP *frame32 = FreeImage_ConvertTo32Bits(dib);
	if(frame32 == NULL) {
		FIBITMAP *standard = FreeImage_ConvertToStandardType(dib, TRUE);
		if(standard != NULL) {
			frame32 = FreeImage_ConvertTo32Bits(standard);
			FreeImage_Unload(standard);
		}
	}
	if(frame32 == NULL) {
		FreeImage_OutputMessageProc(s_format_id, FI_MSG_ERROR_UNSUPPORTED_FORMAT);
		return FALSE;
	}

	APNGFrame frame;
	ReadFrameTags(dib, &frame);
	frame.width = FreeImage_GetWidth(frame32);
	frame.height = FreeImage_GetHeight(frame32);

	if(is_first) {
		ReadAnimationTags(dib, &frame, &info->out_width, &info->out_height, &info->out_plays);
	}
	// frames may enlarge the canvas; it is written in Close()
	info->out_width = MAX(info->out_width, frame.x_offset + frame.width);
	info->out_height = MAX(info->out_height, frame.y_offset + frame.height);

	// full-canvas SOURCE frames are stored as their changed rectangle (exact)
	FIBITMAP *encoded = frame32;
	const BOOL replaces_canvas =
		(frame.x_offset == 0) && (frame.y_offset == 0) &&
		(frame.blend_op == APNG_BLEND_OP_SOURCE) && (frame.dispose_op == APNG_DISPOSE_OP_NONE) &&
		(frame.width == info->out_width) && (frame.height == info->out_height);

	if(replaces_canvas && !is_first && (info->out_previous != NULL) &&
	   (FreeImage_GetWidth(info->out_previous) == frame.width) && (FreeImage_GetHeight(info->out_previous) == frame.height)) {
		DWORD x = 0, y = 0, width = 0, height = 0;
		if(DifferenceRegion(frame32, info->out_previous, &x, &y, &width, &height)) {
			if((width < frame.width) || (height < frame.height)) {
				FIBITMAP *cropped = FreeImage_Copy(frame32, (int)x, (int)y, (int)(x + width), (int)(y + height));
				if(cropped != NULL) {
					encoded = cropped;
					frame.x_offset = x;
					frame.y_offset = y;
					frame.width = width;
					frame.height = height;
				}
			}
		} else {
			// unchanged frame: store one pixel over itself
			FIBITMAP *cropped = FreeImage_Copy(frame32, 0, 0, 1, 1);
			if(cropped != NULL) {
				encoded = cropped;
				frame.width = 1;
				frame.height = 1;
			}
		}
	}

	BOOL bResult = FALSE;
	{
		std::vector<BYTE> png;
		if(CompressFrame(encoded, flags, is_first, png)) {
			bResult = SplitPNG(png, is_first ? &info->out_ancillary : NULL, frame.data);
		}
	}

	if(encoded != frame32) {
		FreeImage_Unload(encoded);
	}

	if(!bResult) {
		FreeImage_Unload(frame32);
		return FALSE;
	}

	// keep for diffing while the canvas equals the frame
	if(info->out_previous != NULL) {
		FreeImage_Unload(info->out_previous);
		info->out_previous = NULL;
	}
	if(replaces_canvas) {
		info->out_previous = frame32;
	} else {
		FreeImage_Unload(frame32);
	}

	try {
		info->out_frames.push_back(APNGFrame());
	} catch(std::bad_alloc&) {
		return FALSE;
	}
	APNGFrame& stored = info->out_frames.back();
	stored.width = frame.width;
	stored.height = frame.height;
	stored.x_offset = frame.x_offset;
	stored.y_offset = frame.y_offset;
	stored.delay_num = frame.delay_num;
	stored.delay_den = frame.delay_den;
	stored.dispose_op = frame.dispose_op;
	stored.blend_op = frame.blend_op;
	stored.data.swap(frame.data);

	return TRUE;
}

// transparent default image, for a first frame smaller than the canvas
static BOOL
CompressBackdrop(DWORD width, DWORD height, int flags, std::vector<BYTE>& data) {
	FIBITMAP *dib = FreeImage_Allocate(width, height, 32, FI_RGBA_RED_MASK, FI_RGBA_GREEN_MASK, FI_RGBA_BLUE_MASK);
	if(dib == NULL) {
		return FALSE;
	}
	std::vector<BYTE> png;
	const BOOL bResult = CompressFrame(dib, flags, FALSE, png) ? SplitPNG(png, NULL, data) : FALSE;
	FreeImage_Unload(dib);
	return bResult;
}

/**
Write the file; frame 0 goes in IDAT only if it covers the canvas.
@return Returns TRUE if successful, returns FALSE otherwise
*/
static BOOL
WriteAnimation(FreeImageIO *io, fi_handle handle, APNGinfo *info, int flags) {
	static const BYTE signature[8] = { 137, 80, 78, 71, 13, 10, 26, 10 };

	if(io->write_proc((void*)signature, 1, 8, handle) != 8) {
		return FALSE;
	}

	BYTE ihdr[13];
	PutDWORD(ihdr, info->out_width);
	PutDWORD(ihdr + 4, info->out_height);
	ihdr[8] = 8;						// bit depth
	ihdr[9] = PNG_COLOR_TYPE_RGBA;
	ihdr[10] = PNG_COMPRESSION_TYPE_BASE;
	ihdr[11] = PNG_FILTER_TYPE_BASE;
	ihdr[12] = PNG_INTERLACE_NONE;
	if(!WriteChunk(io, handle, "IHDR", NULL, 0, ihdr, 13)) {
		return FALSE;
	}

	if(!info->out_ancillary.empty()) {
		const size_t size = info->out_ancillary.size();
		if(FreeImage_WriteBytes(io, handle, &info->out_ancillary[0], size) != size) {
			return FALSE;
		}
	}

	BYTE actl[8];
	PutDWORD(actl, (DWORD)info->out_frames.size());
	PutDWORD(actl + 4, info->out_plays);
	if(!WriteChunk(io, handle, "acTL", NULL, 0, actl, 8)) {
		return FALSE;
	}

	const APNGFrame& first = info->out_frames[0];
	const BOOL first_is_default = (first.x_offset == 0) && (first.y_offset == 0) &&
		(first.width == info->out_width) && (first.height == info->out_height);

	if(!first_is_default) {
		std::vector<BYTE> backdrop;
		if(!CompressBackdrop(info->out_width, info->out_height, flags, backdrop)) {
			return FALSE;
		}
		if(!WriteChunk(io, handle, "IDAT", NULL, 0, &backdrop[0], backdrop.size())) {
			return FALSE;
		}
	}

	DWORD sequence = 0;
	for(size_t i = 0; i < info->out_frames.size(); i++) {
		const APNGFrame& frame = info->out_frames[i];

		BYTE fctl[26];
		PutDWORD(fctl, sequence++);
		PutDWORD(fctl + 4, frame.width);
		PutDWORD(fctl + 8, frame.height);
		PutDWORD(fctl + 12, frame.x_offset);
		PutDWORD(fctl + 16, frame.y_offset);
		PutWORD(fctl + 20, frame.delay_num);
		PutWORD(fctl + 22, frame.delay_den);
		fctl[24] = frame.dispose_op;
		fctl[25] = frame.blend_op;
		if(!WriteChunk(io, handle, "fcTL", NULL, 0, fctl, 26)) {
			return FALSE;
		}

		if((i == 0) && first_is_default) {
			if(!WriteChunk(io, handle, "IDAT", NULL, 0, &frame.data[0], frame.data.size())) {
				return FALSE;
			}
		} else {
			BYTE prefix[4];
			PutDWORD(prefix, sequence++);
			if(!WriteChunk(io, handle, "fdAT", prefix, 4, &frame.data[0], frame.data.size())) {
				return FALSE;
			}
		}
	}

	return WriteChunk(io, handle, "IEND", NULL, 0, NULL, 0);
}

// ==========================================================
// Plugin Implementation
// ==========================================================

static const char * DLL_CALLCONV
Format() {
	return "APNG";
}

static const char * DLL_CALLCONV
Description() {
	return "Animated Portable Network Graphics";
}

static const char * DLL_CALLCONV
Extension() {
	return "apng,png";
}

static const char * DLL_CALLCONV
RegExpr() {
	return NULL;
}

static const char * DLL_CALLCONV
MimeType() {
	return "image/apng";
}

static BOOL DLL_CALLCONV
Validate(FreeImageIO *io, fi_handle handle) {
	return APNG_IsAnimatedStream(io, handle);
}

static BOOL DLL_CALLCONV
SupportsExportDepth(int depth) {
	return (
			(depth == 1) ||
			(depth == 4) ||
			(depth == 8) ||
			(depth == 24) ||
			(depth == 32)
		);
}

static BOOL DLL_CALLCONV
SupportsExportType(FREE_IMAGE_TYPE type) {
	return (
		(type == FIT_BITMAP) ||
		(type == FIT_UINT16) ||
		(type == FIT_RGB16) ||
		(type == FIT_RGBA16)
	);
}

static BOOL DLL_CALLCONV
SupportsICCProfiles() {
	return TRUE;
}

static BOOL DLL_CALLCONV
SupportsNoPixels() {
	return TRUE;
}

// ----------------------------------------------------------

static void * DLL_CALLCONV
Open(FreeImageIO *io, fi_handle handle, BOOL read) {
	APNGinfo *info = new(std::nothrow) APNGinfo;
	if(info == NULL) {
		return NULL;
	}
	info->read = read;

	if(read) {
		BOOL bResult = FALSE;
		try {
			bResult = ParseStream(io, handle, info);
		} catch(std::bad_alloc&) {
			bResult = FALSE;
		}
		if(!bResult) {
			FreeImage_OutputMessageProc(s_format_id, "Invalid or corrupted PNG file");
			delete info;
			return NULL;
		}
	}

	return info;
}

static void DLL_CALLCONV
Close(FreeImageIO *io, fi_handle handle, void *data) {
	APNGinfo *info = (APNGinfo*)data;
	if(info == NULL) {
		return;
	}

	// written here: acTL needs the final frame count
	if(!info->read) {
		try {
			if(info->pending != NULL) {
				APNGFrame described;
				if(!ReadFrameTags(info->pending, &described)) {
					// a lone untagged page is written as a plain PNG
					if(!FreeImage_SaveToHandle(FIF_PNG, info->pending, io, handle, info->pending_flags)) {
						FreeImage_OutputMessageProc(s_format_id, "Failed to write the output file");
					}
				} else if(!AddFrame(info, info->pending, info->pending_flags, TRUE)) {
					// a tagged page is a 1-frame animation, keeping its tags
					FreeImage_OutputMessageProc(s_format_id, "Failed to write the output file");
				}
				FreeImage_Unload(info->pending);
				info->pending = NULL;
			}
			if(!info->out_frames.empty()) {
				if(!WriteAnimation(io, handle, info, info->pending_flags)) {
					FreeImage_OutputMessageProc(s_format_id, "Failed to write the output file");
				}
			}
		} catch(std::bad_alloc&) {
			FreeImage_OutputMessageProc(s_format_id, FI_MSG_ERROR_MEMORY);
		}
	}

	delete info;
}

// ----------------------------------------------------------

static int DLL_CALLCONV
PageCount(FreeImageIO *io, fi_handle handle, void *data) {
	APNGinfo *info = (APNGinfo*)data;
	return (info != NULL) ? (int)info->frames.size() : 0;
}

// ----------------------------------------------------------

static FIBITMAP * DLL_CALLCONV
Load(FreeImageIO *io, fi_handle handle, int page, int flags, void *data) {
	APNGinfo *info = (APNGinfo*)data;
	if((info == NULL) || !info->read) {
		return NULL;
	}

	// FreeImage_Load asks for page -1
	if(page == -1) {
		page = 0;
	}
	if((page < 0) || (page >= (int)info->frames.size())) {
		return NULL;
	}

	try {
		const BOOL header_only = ((flags & FIF_LOAD_NOPIXELS) == FIF_LOAD_NOPIXELS) ? TRUE : FALSE;
		const BOOL playback = (info->animated && ((flags & APNG_PLAYBACK) == APNG_PLAYBACK)) ? TRUE : FALSE;

		FIBITMAP *dib = NULL;
		if(playback) {
			dib = header_only ?
				FreeImage_AllocateHeader(TRUE, info->canvas_width, info->canvas_height, 32, FI_RGBA_RED_MASK, FI_RGBA_GREEN_MASK, FI_RGBA_BLUE_MASK) :
				RenderFrame(info, page, flags);
		} else {
			dib = DecodeFrame(info, page, flags & ~APNG_PLAYBACK);
		}
		if(dib == NULL) {
			return NULL;
		}

		if(info->animated) {
			SetFrameMetadata(dib, info, page);
		}

		return dib;

	} catch(std::bad_alloc&) {
		FreeImage_OutputMessageProc(s_format_id, FI_MSG_ERROR_MEMORY);
		return NULL;
	}
}

// ----------------------------------------------------------

static BOOL DLL_CALLCONV
Save(FreeImageIO *io, FIBITMAP *dib, fi_handle handle, int page, int flags, void *data) {
	APNGinfo *info = (APNGinfo*)data;
	if((info == NULL) || (dib == NULL) || info->read) {
		return FALSE;
	}

	// refuse here: Close() cannot report failure
	{
		const FREE_IMAGE_TYPE image_type = FreeImage_GetImageType(dib);
		if(!FreeImage_HasPixels(dib) || !SupportsExportType(image_type) ||
		   ((image_type == FIT_BITMAP) && !SupportsExportDepth(FreeImage_GetBPP(dib)))) {
			FreeImage_OutputMessageProc(s_format_id, FI_MSG_ERROR_UNSUPPORTED_FORMAT);
			return FALSE;
		}
	}

	try {
		// hold page 0: a second page makes this an animation
		if(info->out_pages == 0) {
			info->pending = FreeImage_Clone(dib);
			if(info->pending == NULL) {
				FreeImage_OutputMessageProc(s_format_id, FI_MSG_ERROR_DIB_MEMORY);
				return FALSE;
			}
			info->pending_flags = flags;
			info->out_pages = 1;
			return TRUE;
		}

		if(info->pending != NULL) {
			FIBITMAP *first = info->pending;
			info->pending = NULL;
			const BOOL bResult = AddFrame(info, first, info->pending_flags, TRUE);
			FreeImage_Unload(first);
			if(!bResult) {
				return FALSE;
			}
		}

		info->out_pages++;
		return AddFrame(info, dib, flags, FALSE);

	} catch(std::bad_alloc&) {
		FreeImage_OutputMessageProc(s_format_id, FI_MSG_ERROR_MEMORY);
		return FALSE;
	}
}

// ==========================================================
//   Init
// ==========================================================

void DLL_CALLCONV
InitAPNG(Plugin *plugin, int format_id) {
	s_format_id = format_id;

	plugin->format_proc = Format;
	plugin->description_proc = Description;
	plugin->extension_proc = Extension;
	plugin->regexpr_proc = RegExpr;
	plugin->open_proc = Open;
	plugin->close_proc = Close;
	plugin->pagecount_proc = PageCount;
	plugin->pagecapability_proc = NULL;
	plugin->load_proc = Load;
	plugin->save_proc = Save;
	plugin->validate_proc = Validate;
	plugin->mime_proc = MimeType;
	plugin->supports_export_bpp_proc = SupportsExportDepth;
	plugin->supports_export_type_proc = SupportsExportType;
	plugin->supports_icc_profiles_proc = SupportsICCProfiles;
	plugin->supports_no_pixels_proc = SupportsNoPixels;
}
